/* ==============================================================
   Rainmaker X · app · account, profile and membership
   Open-an-account page, brokerage account (cash, positions, ledger, statements), join,
   sign-in, My Profile and the printable statement.
   ============================================================== */
'use strict';

// Open a brokerage account (members who have none). Instant in the prototype.
function viewOpenAccount(main) {
  const pr = D.profile();
  main.innerHTML = `<div class="page wide">
    ${pageHead({ icon: PH.account, title: 'Open a brokerage account', tag: 'No account yet', tagClass: 'status', sub: 'You are a member of Rainmaker X, but you do not have a brokerage account. You need one to hold cash, reserve funds for bids and settle trades. Opening one takes a minute; verification can follow later.', stats: [['Step 1', 'Choose the account'], ['Step 2', 'Registration and tax status'], ['Step 3', 'Link a bank (optional)'], ['Then', 'Fund it and start bidding']] })}
    <div class="two-col"><form class="card" id="open-primary"><div class="card-head"><span class="label">Account application</span><span class="badge status">Demo · opens instantly</span></div><div class="card-body stack" style="gap:12px">
      <div class="field"><label>Account type</label><select name="type">${D.ACCOUNT_TYPES.map(t => `<option>${t}</option>`).join('')}</select></div>
      <div class="field"><label>Registration name</label><input name="name" value="${esc(pr.name)}" required></div>
      <div class="grid-2"><div class="field"><label>Tax status</label><select name="tax"><option>W-9 (US person)</option><option>W-8BEN (non-US individual)</option><option>W-8BEN-E (non-US entity)</option></select></div><div class="field"><label>Bank to link (optional)</label><input name="bank" placeholder="e.g. Chase ···4410"></div></div>
      <label class="check"><input type="checkbox" name="agree" required> I have read the brokerage account agreement, the privacy notice and the private-securities risk disclosure.</label>
      <div class="row"><button class="btn" type="submit">Open account</button><a class="btn outline" href="#/representatives">Talk to a representative first</a></div>
      <div class="small muted">Prototype: nothing is submitted anywhere. In production this starts KYC / AML and the account is opened by compliance.</div></div></form>
    <div class="stack"><div class="card"><div class="card-head"><span class="label">What you get</span></div><div class="card-body alt-how">${[['Cash and buying power', 'A ledger for wires in and out, with cash reserved automatically for your open bids.'], ['Positions', 'Every private share or SPV unit we record for you, at the RX price.'], ['Settlement', 'Escrow, ROFR tracking and transfer with the company\'s transfer agent, step by step.'], ['Statements', 'Monthly statements, tax lots and documents in one place.']].map((t, i) => `<div class="alt-step"><span class="n">${i + 1}</span><div><b>${t[0]}</b><div class="muted small">${t[1]}</div></div></div>`).join('')}</div></div>
      <div class="card card-body small gold-rule">Rainmaker Securities, LLC is an introducing broker. Private shares are held in book-entry with the issuer's transfer agent or inside a Rainmaker SPV; your cash sits in escrow until a trade closes.</div></div></div></div>`;
  main.querySelector('#open-primary').addEventListener('submit', e => { e.preventDefault(); const f = e.target; D.openPrimaryAccount({ type: f.type.value, name: f.name.value.trim(), bank: f.bank.value.trim(), taxStatus: f.tax.value.split(' ')[0] + ' on file' }); toast('Brokerage account opened'); go('#/account'); render(); });
}
// Filters on the "Your accounts" list (page-local, not saved).
const acctF = { q: '', status: 'all', type: 'all' };
// Brokerage account: switcher, cash, buying power, positions, settlements, ledger, funding, statements.
// Several accounts per member; switching, opening and closing are for verified (accredited) investors only (Ben, Sep 30 2026).
function viewAccount(main, sub) {
  if (!D.hasAccount()) return viewOpenAccount(main);
  const allAccts = D.accounts(); const accts = D.openAccounts(); const a = D.currentAccount(); const canMgr = D.canManageAccounts(); const primary = D.isPrimary(a); const pr = D.profile(); const rep_ = D.rep(pr.rep);
  const holdings = D.holdings(a); const spvH = primary ? D.spvHoldings() : []; const pv = holdings.reduce((s, h) => s + h.value, 0) + spvH.reduce((s, h) => s + h.value, 0);
  const cash = D.cashBalance(a), reserved = D.reservedCash(a), bp = D.buyingPower(a);
  const ledger = D.cashLedger(a); const open = primary ? D.settlements().filter(x => x.stage < D.SETTLE_STEPS[x.counterparty === 'desk' ? 'desk' : 'market'].length - 1) : []; const subsOpen = primary ? D.openSpvSubs() : [];   // SPV subscriptions in progress (sign → escrow → units issued)
  const live = primary ? D.myOrders().filter(o => o.status === 'live') : [];
  const regName = a.name || pr.name; const shownAccts = D.filterAccounts(acctF);
  const switcher = accts.length > 1 && canMgr ? `<div class="acct-switch"><span class="label dim">Open accounts</span>${accts.map(x => `<button type="button" class="acct-tab ${x.number === a.number ? 'on' : ''}" data-acct="${esc(x.number)}"><b>${esc(x.type)}</b><span class="tiny ${x.number === a.number ? '' : 'muted'}">${esc(x.number)}${x.name ? ' · ' + esc(x.name) : ''}${x.primary ? ' · primary' : ''}</span></button>`).join('')}<span class="small muted acct-viewing">Viewing <b>${esc(a.type)}</b> ${esc(a.number)}</span></div>` : '';
  main.innerHTML = `<div class="page wide">
    ${pageHead({ icon: PH.account, title: `Account <span class="acct-num">${esc(a.number)}</span>`, tag: a.status, tagClass: a.status.startsWith('Open') ? 'open' : 'status', sub: `<b>${esc(regName)}</b> · Rainmaker Securities · <b>${esc(a.type)}</b>${primary ? ' (primary)' : ''} · ${accts.length > 1 ? `account ${accts.findIndex(x => x.number === a.number) + 1} of ${accts.length}` : 'your only account'} · opened ${fmtDate(a.opened)} · ${verBadge()}`, actions: `${canMgr ? `<div class="rel"><button class="btn outline sm" id="acct-switch-btn" type="button" title="Switch to another of your open accounts">Switch account ${ICON.chev}</button><div class="menu hidden" id="acct-menu"><div class="menu-head">Open accounts</div>${accts.map(x => `<button type="button" data-acct="${esc(x.number)}" ${x.number === a.number ? 'disabled' : ''}><b>${esc(x.type)}</b>${x.primary ? ' · primary' : ''}<div class="tiny muted">${esc(x.number)}${x.name ? ' · ' + esc(x.name) : ''}${x.number === a.number ? ' · viewing' : ''}</div></button>`).join('')}<button type="button" id="acct-menu-open">${ICON.plus} <b>Open another account</b></button></div></div><button class="btn outline sm" id="acct-open-btn" type="button">${ICON.plus} Open account</button>` : ''}<button class="btn outline sm" id="btn-deposit">Deposit funds</button><button class="btn outline sm" id="btn-withdraw">Withdraw</button><a class="btn outline custom sm" href="#/new/custom">${ICON.sliders} Custom order</a><a class="btn bid sm" href="#/new/bid">${ICON.cart} Place Bid</a>` })}
    ${switcher}
    <div class="kpis" style="grid-template-columns:repeat(5,minmax(0,1fr))">
      <div class="kpi"><span class="label">Cash balance</span><div class="v">${money(cash, 0)}</div><div class="s">settled + pending wires</div></div>
      <div class="kpi"><span class="label">Reserved</span><div class="v">${money(reserved, 0)}</div><div class="s">${live.filter(o => o.side === 'bid').length} live bids${subsOpen.filter(x => x.stage < 2).length ? ` · ${subsOpen.filter(x => x.stage < 2).length} subscription${subsOpen.filter(x => x.stage < 2).length === 1 ? '' : 's'}` : ''}</div></div>
      <div class="kpi"><span class="label">Buying power</span><div class="v ${bp < 0 ? 'down' : ''}">${money(bp, 0)}</div><div class="s">cash minus reservations</div></div>
      <div class="kpi"><span class="label">Positions value</span><div class="v">${money(pv, 0)}</div><div class="s">${holdings.length} companies at RX price${spvH.length ? ` + ${spvH.length} SPV${spvH.length === 1 ? '' : 's'}` : ''}</div></div>
      <div class="kpi gold-rule"><span class="label">Total account value</span><div class="v">${money(pv + cash, 0)}</div><div class="s">positions + cash</div></div>
    </div>
    <div id="cash-forms" class="stack"></div>
    <div class="acct-grid">
      <div class="stack">
        <div class="card"><div class="card-head"><span class="label">Positions</span><a class="link small" href="#/browse">Find more companies</a></div>
          ${holdings.length ? `<table class="table compact"><thead><tr><th>Company</th><th class="num">Shares</th><th class="num">Avg cost</th><th class="num">RX price</th><th class="num">Value</th><th class="num">Gain / loss</th><th></th></tr></thead><tbody>${holdings.map(h => `<tr class="clickable" data-href="#/company/${h.c.id}"><td><span class="row">${logo(h.c, 'sm')}<span><b>${esc(h.c.name)}</b><div class="tiny muted">${esc(h.c.ticker)} · held since ${fmtDate(h.first)}</div></span></span></td><td class="num">${num(h.qty)}</td><td class="num">${money(h.avgCost)}</td><td class="num">${money(h.price)}</td><td class="num strong">${money(h.value, 0)}</td><td class="num ${cls(h.gainPct)}">${money(h.gain, 0)}<div class="tiny">${pct(h.gainPct)}</div></td><td class="num"><span class="row" style="gap:4px;justify-content:flex-end"><a class="btn ask sm" href="#/new/listing/${h.c.id}">${ICON.cash} Sell</a><a class="btn sm" href="#/new/bid/${h.c.id}">${ICON.cart} Buy more</a></span></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No positions yet.</div>'}
          ${spvH.length ? `<div class="label" style="padding:14px 20px 4px">SPV units</div><table class="table compact spv-units-table"><thead><tr><th>Vehicle</th><th class="num">Units</th><th class="num">Avg cost</th><th class="num">Unit value</th><th class="num">Value</th><th class="num">Gain / loss</th><th></th></tr></thead><tbody>${spvH.map(h => { const off = D.spvOffer(h.f); return `<tr class="clickable" data-href="#/fund/${h.f.id}"><td><span class="row"><span class="fund-mark spv">RX</span><span><b>${esc(h.f.name)}</b><div class="tiny muted">${esc(h.f.status)}${off.canSell ? ` · standing bid ${money(off.bid)}` : ' · no standing bid'}</div></span></span></td><td class="num">${num(h.qty)}</td><td class="num">${money(h.avgCost)}</td><td class="num">${money(h.price)}</td><td class="num strong">${money(h.value, 0)}</td><td class="num ${cls(h.gainPct)}">${money(Math.abs(h.gain) < 0.5 ? 0 : h.gain, 0)}<div class="tiny">${pct(Math.abs(h.gainPct) < 0.00005 ? 0 : h.gainPct)}</div></td><td class="num"><span class="row spv-row-actions" style="gap:4px;justify-content:flex-end">${off.canSell ? `<a class="btn ask sm" href="#/fund/${h.f.id}">${ICON.cash} Sell back</a>` : ''}${off.canBuy ? `<a class="btn sm" href="#/fund/${h.f.id}">${ICON.cart} Buy more</a>` : ''}</span></td></tr>`; }).join('')}</tbody></table>` : ''}
          <div class="card-foot small">Private company shares are held in book-entry with the issuer's transfer agent or inside a Rainmaker SPV. Rainmaker Securities, LLC acts as introducing broker and does not take custody of client securities; the account shows the positions we have recorded for you.</div></div>
        ${open.length || subsOpen.length ? `<div class="card"><div class="card-head"><span class="label">Pending settlements</span><a class="link small" href="#/orders/matches">All matches</a></div><div class="card-body stack" style="gap:14px">${subsOpen.map(x => spvSubBlock(x, { compact: true, link: true })).join('')}${open.map(x => { const c = D.company(x.companyId); return `<div><div class="small" style="margin-bottom:6px"><b>${esc(c.name)}</b> · ${x.side === 'buy' ? 'buying' : 'selling'} ${num(x.qty)} @ ${money(x.price)} · ${money(x.gross, 0)}</div>${trackerBlock(x, { compact: true })}</div>`; }).join('')}</div></div>` : ''}
        ${primary ? taxCard() : ''}
        <div class="card"><div class="card-head"><span class="label">Cash activity</span><span class="small muted">${ledger.length} entries</span></div>
          <div class="scroll-y"><table class="table compact ledger"><thead><tr><th>Date</th><th>Type</th><th>Detail</th><th class="num">Amount</th></tr></thead><tbody>${ledger.map(r => `<tr ${r.companyId ? `class="clickable" data-href="#/company/${r.companyId}"` : r.fundId ? `class="clickable" data-href="#/fund/${r.fundId}"` : ''}><td>${fmtDate(r.ts)}</td><td><span class="badge status">${esc(r.kind)}</span>${r.pending ? ' <span class="badge pending">Pending</span>' : ''}</td><td class="dim">${esc(r.note)}</td><td class="amt ${r.amount >= 0 ? 'in' : 'out'}">${r.amount >= 0 ? '+' : '−'}${money(Math.abs(r.amount), 0)}</td></tr>`).join('')}</tbody></table></div></div>
      </div>
      <div class="stack">
        <div class="card"><div class="card-head"><span class="label">Account details</span></div><div class="card-body" style="padding-top:4px;padding-bottom:4px"><table class="kv tight"><tr><th>Account number</th><td class="mono">${esc(a.number)}</td></tr><tr><th>Type</th><td>${esc(a.type)}${primary ? ' · primary' : ''}</td></tr><tr><th>Registration</th><td>${esc(regName)}${primary && pr.firm ? ' · ' + esc(pr.firm) : ''}</td></tr><tr><th>Account holder</th><td>${esc(pr.name)}</td></tr><tr><th>Investor status</th><td>${pr.investorType ? esc(D.INVESTOR_TYPES[pr.investorType]) : 'Not declared'}</td></tr><tr><th>Tax</th><td>${esc(a.taxStatus)}</td></tr><tr><th>Linked bank</th><td>${esc(a.bank)}</td></tr><tr><th>Representative</th><td><a class="link" href="#/representatives">${esc(rep_.name)}</a> · ${esc(rep_.phone)}</td></tr><tr><th>Introducing broker</th><td>Rainmaker Securities, LLC · FINRA / SIPC</td></tr></table></div></div>
        <div class="card"><div class="card-head"><span class="label">Funding instructions</span></div><div class="card-body stack" style="gap:10px"><div class="small muted">Wire to the escrow account below and reference your account number. Funds post the same business day and count toward buying power immediately.</div><div class="wire">Beneficiary: Rainmaker Securities LLC · Client Escrow<br>Bank: First Republic · ABA 321081669<br>Account: 8891 0042 17<br>Reference: ${esc(a.number)}</div></div></div>
        <div class="card"><div class="card-head"><span class="label">Statements &amp; documents</span></div><div class="card-body" style="padding-top:8px;padding-bottom:8px">${D.statements().map(st => `<div class="doc-row between small"><span class="row">${ICON.doc}${esc(st.label)}</span><span class="row"><span class="muted tiny">${fmtDate(st.ts)}</span><a class="btn ghost sm" href="#/account/statement/${st.id}">Open</a></span></div>`).join('')}${D.ACCOUNT_DOCS.map((d, i) => `<div class="doc-row between small"><span class="row">${ICON.doc}${esc(d)}</span><button class="btn ghost sm" data-doc="doc-${i}">View</button></div>`).join('')}</div></div>
        <div class="card" id="acct-card"><div class="card-head af-head"><span class="label">Your accounts</span><span class="row" style="gap:6px;flex-wrap:wrap"><input class="mini" data-acf="q" placeholder="Number, type or name" value="${esc(acctF.q)}" style="width:150px"><select class="mini" data-acf="status"><option value="all" ${acctF.status === 'all' ? 'selected' : ''}>Open + closed</option><option value="open" ${acctF.status === 'open' ? 'selected' : ''}>Open</option><option value="closed" ${acctF.status === 'closed' ? 'selected' : ''}>Closed</option></select><select class="mini" data-acf="type"><option value="all">All types</option>${D.ACCOUNT_TYPES.map(t => `<option ${acctF.type === t ? 'selected' : ''}>${esc(t)}</option>`).join('')}</select></span></div><div class="card-body stack" style="gap:10px">
          <div class="tiny muted">${shownAccts.length} of ${allAccts.length} · ${accts.length} open${allAccts.length - accts.length ? ` · ${allAccts.length - accts.length} closed` : ''}</div>
          ${shownAccts.length ? shownAccts.map(x => { const closed = x.status === 'Closed'; return `<div class="between small acct-row ${closed ? 'closed' : ''}" data-row="${esc(x.number)}"><span><b>${esc(x.type)}</b>${x.name ? ' · ' + esc(x.name) : ''}${x.primary ? ' <span class="badge mine">Primary</span>' : ''}<div class="tiny muted mono">${esc(x.number)}${closed ? ` · closed ${fmtDate(x.closedAt)}` : ` · opened ${fmtDate(x.opened)}`}</div></span><span class="row" style="gap:6px"><span class="badge ${closed ? 'status' : String(x.status).startsWith('Open') ? 'open' : 'pending'}">${esc(x.status)}</span>${closed ? '' : x.number === a.number ? '<span class="tiny muted">Viewing</span>' : canMgr ? `<button class="btn ghost sm" type="button" data-acct="${esc(x.number)}">View</button>` : ''}${!closed && !x.primary && canMgr ? `<button class="btn danger sm" type="button" data-acct-close="${esc(x.number)}">Close</button>` : ''}</span></div>`; }).join('') : '<div class="small muted">No accounts match.</div>'}
          ${canMgr ? `<div class="small muted">Open a joint, trust, entity, IRA or SPV account alongside this one. Each account has its own number, cash, positions and statements; orders and settlements are recorded against the account shown. Closing an account keeps it on record as Closed; empty it first.</div>
          <form id="open-acct" class="stack" style="gap:8px"><div class="field"><label>Open another account</label><select name="type">${D.ACCOUNT_TYPES.map(t => `<option>${t}</option>`).join('')}</select></div><div class="field"><input name="name" placeholder="Account name (e.g. Martin Family Trust)"></div><button class="btn outline sm" type="submit">Start application</button></form>` : `<div class="callout"><b>Additional accounts are for verified accredited investors.</b> Complete <a class="link" href="#/profile/verification">investor verification</a> to open joint, trust, entity, IRA or SPV accounts, switch between them, or close one.</div>`}</div></div>
        <div class="card card-body small gold-rule"><b>How this works for private securities.</b> Unlike listed stock, private shares are not held at a clearing house. When you buy, the seller's shares are re-registered to you (or to an SPV you hold units in) with the company's transfer agent after ROFR clears; when you sell, the reverse. Your cash sits in escrow until close. This account is the ledger for all of that: cash in, reservations for open bids, positions we have recorded, and every settlement.</div>
      </div>
    </div></div>`;
  const forms = main.querySelector('#cash-forms');
  // Deposit / Withdraw (Ben, Oct 5 2026): the wire posts to the account being viewed at once and changes the cash balance; the ledger shows it as Pending for a minute.
  const showForm = kind => { const dep = kind === 'deposit'; forms.innerHTML = `<form class="card card-body mini-form" id="cash-form" style="gap:12px;flex-wrap:wrap"><b style="min-width:150px">${dep ? 'Deposit funds' : 'Withdraw funds'}</b><input name="amount" type="number" min="100" step="100" placeholder="Amount ($)" required><span class="small muted">${dep ? 'from' : 'to'} ${esc(a.bank)} · ${dep ? 'into' : 'from'} ${esc(a.number)}</span><button class="btn sm" type="submit">${dep ? 'Initiate wire' : 'Request withdrawal'}</button><button class="btn ghost sm" type="button" id="cash-cancel">Cancel</button></form><div class="tiny muted" style="margin:6px 0 12px">Simulated in the prototype: the wire posts at once, so cash and buying power change immediately; the ledger marks it Pending for a minute.${dep ? '' : ` You can withdraw up to ${money(D.buyingPower(a), 0)} (cash minus what is reserved for open bids and subscriptions).`}</div>`;
    const f = forms.querySelector('#cash-form'); f.amount.focus(); forms.querySelector('#cash-cancel').onclick = () => { forms.innerHTML = ''; };
    f.addEventListener('submit', e => { e.preventDefault(); const amt = +f.amount.value; const r = dep ? D.deposit(amt, a.number) : D.withdraw(amt, a.number); if (r.error) { toast(r.error, false); return; } toast(`${money(r.amount, 0)} ${dep ? 'deposited to' : 'withdrawn from'} ${r.account} · cash balance ${money(r.balance, 0)}`); render(); }); };
  main.querySelector('#btn-deposit').onclick = () => showForm('deposit');
  main.querySelector('#btn-withdraw').onclick = () => showForm('withdraw');
  if (sub === 'deposit') showForm('deposit');
  const oa = main.querySelector('#open-acct'); if (oa) oa.addEventListener('submit', e => { e.preventDefault(); const f = e.target; const acc = D.openAccount({ type: f.type.value, name: f.name.value.trim() }); if (acc.error) { toast(acc.error, false); return; } toast(`${acc.type} account ${acc.number} opened (demo)`); render(); });
  main.querySelectorAll('[data-acct]').forEach(b => b.onclick = e => { e.stopPropagation(); const r = D.selectAccount(b.dataset.acct); if (r.error) { toast(r.error, false); return; } render(); });
  // Switch account menu + Open account button in the page head.
  const sb = main.querySelector('#acct-switch-btn'); if (sb) { const menu = main.querySelector('#acct-menu'); sb.onclick = e => { e.stopPropagation(); const open = menu.classList.contains('hidden'); document.querySelectorAll('.menu').forEach(m => m.classList.add('hidden')); if (open) menu.classList.remove('hidden'); }; }
  const goOpen = () => { const f = main.querySelector('#open-acct'); if (!f) return; f.scrollIntoView({ behavior: 'smooth', block: 'center' }); f.classList.add('flash'); setTimeout(() => f.type.focus(), 300); };
  const ob = main.querySelector('#acct-open-btn'); if (ob) ob.onclick = goOpen; const omo = main.querySelector('#acct-menu-open'); if (omo) omo.onclick = goOpen;
  // Close an account: inline confirmation (no browser dialog), then Data.closeAccount.
  main.querySelectorAll('[data-acct-close]').forEach(b => b.onclick = () => { const n = b.dataset.acctClose; const row = main.querySelector(`[data-row="${CSS.escape(n)}"]`); row.innerHTML = `<span class="small"><b>Close ${esc(n)}?</b> It stays on record as Closed and cannot be reopened here.</span><span class="row" style="gap:6px"><input class="mini" id="acct-close-why" placeholder="Reason (optional)" style="width:160px"><button class="btn danger sm" type="button" id="acct-close-yes">Confirm close</button><button class="btn ghost sm" type="button" id="acct-close-no">Keep</button></span>`; row.querySelector('#acct-close-no').onclick = () => render(); row.querySelector('#acct-close-yes').onclick = () => { const r = D.closeAccount(n, row.querySelector('#acct-close-why').value.trim()); if (r.error) { toast(r.error, false); return; } toast(`Account ${n} closed`); render(); }; });
  // Filters on the accounts list.
  main.querySelectorAll('[data-acf]').forEach(el => el.addEventListener(el.tagName === 'INPUT' ? 'input' : 'change', () => { acctF[el.dataset.acf] = el.value; const pos = el.selectionStart; const y = window.scrollY; render(); window.scrollTo(0, y); const n = main.querySelector(`[data-acf="${el.dataset.acf}"]`); if (n && el.tagName === 'INPUT') { n.focus(); n.setSelectionRange(pos, pos); } }));
  main.querySelectorAll('[data-doc]').forEach(b => b.onclick = () => toast('Documents are placeholders in this prototype', false));
}

// ---------------- join (membership before verification) ----------------
function viewJoin(main) {
  const pr = D.profile();
  main.innerHTML = `<div class="page narrow">
    <div class="hero" style="grid-template-columns:minmax(0,1.2fr) minmax(0,1fr)"><div><div class="eyebrow">Join Rainmaker X</div><h1>Membership is open to everyone. Live trading is for verified investors.</h1><p>Join now to browse every company, favorite them, set price alerts, message a representative, and submit bids, asks and desk quotes as requests. Complete investor verification whenever you are ready and your pending requests are placed on the book automatically.</p></div>
      <div class="hero-stats" style="grid-template-columns:1fr"><div><span class="label">Member</span><div class="v" style="font-size:18px">Browse · favorites · alerts · messages · requests</div><div class="s">No verification needed</div></div><div><span class="label">Verified investor</span><div class="v" style="font-size:18px">Everything above, live on the book</div><div class="s">Accredited investor, QIB or institution, reviewed by compliance</div></div></div></div>
    <div class="two-col"><form class="card" id="join-form"><div class="card-head"><h2 style="font-size:20px">Create your account</h2></div><div class="card-body stack">
      <div class="grid-2"><div class="field"><label>Full name</label><input name="name" required placeholder="Jane Doe"></div><div class="field"><label>Email</label><input name="email" type="email" required placeholder="jane@example.com"></div></div>
      <div class="grid-2"><div class="field"><label>Firm (optional)</label><input name="firm" placeholder="Family office, fund, employer…"></div><div class="field"><label>I expect to qualify as</label><select name="selfType"><option value="">Not sure yet</option>${Object.entries(D.INVESTOR_TYPES).map(([k, v]) => `<option value="${k}">${v}</option>`).join('')}</select><span class="hint">Self-declared. Compliance verifies separately.</span></div></div>
      <label class="check"><input type="checkbox" required><span>I have read the Form CRS relationship summary and the private securities risk disclosure.</span></label>
      <div class="callout">This demo switches you to a fresh, unverified member so you can see the request flow. <b>${esc(D.signInProfile().name)}</b>'s sample account is kept exactly as it is: "Sign in" (or the profile menu) brings it back.</div>
    </div><div class="card-foot form-foot" style="background:#fff"><a class="btn ghost" href="#/home">Cancel</a><button class="btn" type="submit">Join as a member</button></div></form>
    <div class="stack"><div class="card card-body stack"><span class="label">What happens next</span><div class="how" style="grid-template-columns:1fr;gap:12px"><div><div class="step">1</div><h3>Join</h3><p>Your membership and a limited brokerage account are created instantly.</p></div><div><div class="step">2</div><h3>Submit requests</h3><p>Bids, asks, custom orders, desk quotes, fund allocations and data room access are routed to your primary representative as requests.</p></div><div><div class="step">3</div><h3>Get verified</h3><p>Tell us whether you are an accredited investor, a QIB or an institution. Once compliance approves, requests go live and you trade directly.</p></div></div></div>
      <div class="card card-body small muted">Current profile: <b>${esc(pr.name)}</b> · ${verBadge()}</div></div></div></div>`;
  main.querySelector('#join-form').addEventListener('submit', e => { e.preventDefault(); const f = e.target; D.joinMember({ name: f.name.value.trim(), email: f.email.value.trim(), firm: f.firm.value.trim(), selfType: f.selfType.value }); toast('Welcome to Rainmaker X'); go('#/dashboard'); });
}
// ---------------- sign in / create account ----------------
// The sign-in form, shared by the sign-in page and every locked member page. It always returns to the sample member's
// account (Ben Martin), restored exactly as it was left; the email is prefilled so it is clear whose account it is.
function signInForm() {
  const who = D.signInProfile();
  return `<form class="card-body stack" id="signin-form"><p class="muted" style="margin:0">Sign in to place orders, see your account and message your primary representative.</p><div class="field"><label>Email</label><input name="email" type="email" required value="${esc(who.email || '')}" placeholder="you@example.com"></div><div class="field"><label>Password</label><input name="password" type="password" required placeholder="••••••••"></div><div class="between small"><label class="check" style="font-weight:500"><input type="checkbox" name="remember"><span>Keep me signed in</span></label><a class="link" href="#/signin">Forgot password?</a></div><div class="callout tiny">Prototype: any password signs you in as <b>${esc(who.name)}</b>, the sample member, with everything exactly as you left it. Real sign-in with MFA is part of the backend build.</div><button class="btn block" type="submit">Sign in</button><div class="small muted" style="text-align:center">New to Rainmaker X? <a class="link" href="#/signin/create">Create an account</a> · <button type="button" class="link-btn" id="reset-data-page">Reset demo data</button></div></form>`;
}
// Wire the shared form: submit signs in and continues to `next`; the Reset link puts the sample data back (works signed out).
function wireSignIn(main, next) {
  const f = main.querySelector('#signin-form'); if (f) f.addEventListener('submit', e => { e.preventDefault(); D.signIn(); toast('Welcome back, ' + D.profile().name.split(' ')[0]); const target = next && !next.startsWith('#/signin') ? next : '#/dashboard'; if (location.hash === target) render(); else go(target); });
  const rd = main.querySelector('#reset-data-page'); if (rd) rd.onclick = () => { if (confirm('Reset all locally saved orders, bids and watchlist?')) D.reset(); };
}
function viewSignIn(main, mode, next) {
  const create = mode === 'create';
  main.innerHTML = `<div class="page narrow" style="max-width:520px"><div class="card" style="margin-top:24px"><div class="card-head"><div class="tabs mini"><a class="${create ? '' : 'on'}" href="#/signin" style="text-decoration:none">Sign in</a><a class="${create ? 'on' : ''}" href="#/signin/create" style="text-decoration:none">Create account</a></div></div>
    ${create ? `<div class="card-body stack"><p class="muted" style="margin:0">Anyone can create an account. You can browse, favorite, set alerts, message a representative and submit requests right away; investor verification unlocks live trading.</p><a class="btn block" href="#/join">Create your account</a></div>` : signInForm()}</div></div>`;
  wireSignIn(main, next);
}
// A member page opened while signed out (Ben, Oct 6 2026): the page keeps its place in the nav and its own title, and
// says "Sign in to access" with the sign-in form right there, instead of bouncing to a bare sign-in page.
const LOCK_ICON = { profile: 'client', account: 'account', dashboard: 'orders', orders: 'orders', order: 'order', match: 'settle', messages: 'mail', new: 'order' };
const LOCK_TEXT = { profile: 'your profile, live orders, favorites and investor verification', account: 'your brokerage account: cash, positions, settlements and statements', dashboard: 'your dashboard', orders: 'your orders, requests, arrangements and matches', order: 'this order and the form to match it', match: 'this match and its settlement', messages: 'your messages with your primary representative and Rainmaker Securities', new: 'the order forms' };
function viewLocked(main, route, hash) {
  main.innerHTML = `<div class="page wide">${pageHead({ icon: PH[LOCK_ICON[route]] || PH.account, title: esc(pageLabel(hash)), tag: 'Sign in to access', tagClass: 'pending', sub: `You are signed out. Sign in to see ${LOCK_TEXT[route] || 'this page'}.` })}
    <div class="card locked-card"><div class="card-head"><h3>Sign in to access</h3></div>${signInForm()}</div></div>`;
  document.title = 'Rainmaker X · ' + pageLabel(hash);
  wireSignIn(main, hash);
}

// My Profile: live bids and asks, structured deals, requests, favorites, verification card.
function viewProfile(main) {
  const live = D.myOrders().filter(o => o.status === 'live'); const bids = live.filter(o => o.side === 'bid'), asks = live.filter(o => o.side === 'listing');
  const liveVal = live.reduce((s, o) => s + o.price * o.qty, 0);
  const lbids = D.myListingBids().filter(b => b.status === 'live');
  const arrs = D.arrangements().filter(x => ['submitted', 'structuring', 'term sheet'].includes(x.status));
  const reqs = D.requests().filter(r => r.status === 'pending');
  const myM = D.matchRecords().filter(r => r.mine); const openM = myM.filter(r => r.label === 'Awaiting approval' || r.label === 'Settling');
  const watch = D.state.watchlist.map(id => D.company(id)).filter(Boolean);
  const pr = D.profile();
  main.innerHTML = `<div class="page wide">
    ${pageHead({ icon: `<label class="ph-photo" title="Change profile photo">${pr.photo ? `<img src="${pr.photo}" alt="">` : esc(pr.initials)}<input type="file" accept="image/*" id="photo-in"></label>`, iconClass: pr.photo ? 'photo' : 'txt', title: esc(pr.name), tag: D.canTrade() ? 'Verified investor' : 'Not yet verified', tagClass: D.canTrade() ? 'verified' : 'status', sub: `${pr.email ? esc(pr.email) + ' · ' : ''}<span class="updated" style="display:inline-flex">${updatedStr()}</span>`, actions: `<a class="btn ask sm" href="#/new/listing">${ICON.cash} New ask</a><a class="btn bid sm" href="#/new/bid">${ICON.cart} New bid</a><a class="btn outline custom sm" href="#/new/custom">Custom order</a>`,
      stats: [['Live bids', bids.length + lbids.length, money(bids.reduce((s, o) => s + o.price * o.qty, 0) + lbids.reduce((s, b) => s + b.price * b.qty, 0), 0) + ' reserved'], ['Live asks', asks.length, money(asks.reduce((s, o) => s + o.price * o.qty, 0), 0) + ' offered'], ['Matches', openM.length, `${myM.filter(r => r.label === 'Awaiting approval').length} awaiting approval · ${myM.filter(r => r.label === 'Settling').length} settling`], ['Structured deals', arrs.length, arrs.length ? 'with the desk' : 'options, forwards, special terms'], ['Favorite companies', watch.length, 'starred on Browse']] })}
    <div class="dash" style="grid-template-columns: minmax(0, 1fr) 380px">
      <div class="stack">
        <div class="card"><div class="card-head"><span class="label">Live bids and asks</span><span class="row" style="gap:10px"><span class="small muted">${money(liveVal, 0)} open</span><a class="link small" href="#/orders">My Orders</a></span></div>
          ${orderBook(live, { showCompany: true, empty: 'No live orders. Place a bid or an ask from any company page, or use the buttons above.' })}</div>
        <div class="card"><div class="card-head"><span class="label">Matches</span><span class="row" style="gap:10px"><span class="small muted">${openM.length} open</span><a class="link small" href="#/orders/matches">All matches</a></span></div>${matchesTable(openM.length ? openM : myM.slice(0, 5), { empty: 'No matches yet. When a bid and an ask cross, the match appears here for Rainmaker\'s approval, then settles.' })}</div>
        ${lbids.length ? `<div class="card"><div class="card-head"><span class="label">Your bids on other members' asks</span><span class="small muted">${lbids.length} live</span></div><table class="table compact"><thead><tr><th>Ask</th><th>Company</th><th class="num">Shares</th><th class="num">Your bid</th><th class="num">Total</th><th>Placed</th></tr></thead><tbody>${lbids.map(b => { const c = D.company(b.companyId); return `<tr class="clickable" data-href="#/order/${esc(b.listingId)}"><td><span class="oid">${esc(b.listingId)}</span></td><td><span class="row" style="gap:8px">${logo(c, 'sm')}<b>${esc(c.name)}</b></span></td><td class="num">${num(b.qty)}</td><td class="num px">${money(b.price)}</td><td class="num px">${money(b.price * b.qty, 0)}</td><td class="small">${fmtPlaced(b.created)}</td></tr>`; }).join('')}</tbody></table></div>` : ''}
        <div class="card"><div class="card-head"><span class="label">Options, forwards and special-terms orders</span><a class="btn outline custom sm" href="#/new/custom">New structured deal</a></div>
          ${arrs.length ? arrangementsTable(arrs, false) : '<div class="empty">No structured deals open. Options, forwards, SPV, DP interest and special-terms orders you submit appear here while the desk works them.</div>'}</div>
        ${reqs.length ? `<div class="card"><div class="card-head"><span class="label">Requests awaiting verification</span><a class="link small" href="#/orders">Requests</a></div><table class="table compact"><thead><tr><th>Request</th><th>What</th><th>Submitted</th></tr></thead><tbody>${reqs.map(r => `<tr><td><span class="oid">${esc(r.id)}</span></td><td>${esc(r.what)}</td><td class="small">${fmtPlaced(r.created)}</td></tr>`).join('')}</tbody></table></div>` : ''}
      </div>
      <div class="stack">
        <div class="card co-list fav"><div class="card-head"><span class="label">Favorite companies</span><a class="link small" href="#/browse">Browse</a></div>
          <div class="fav-scroll">${watch.length ? watch.map(c => `<a class="co-row" href="#/company/${c.id}">${companyRow(c, `<span class="co-extra">${starBtn(c)}</span>`)}</a>`).join('') : '<div class="empty">No favorites yet. Star a company on Browse or its page to keep it here.</div>'}</div></div>
      </div>
    </div>
    <div id="profile-details">
      <div class="card" id="verification">${D.renewalDue() ? `<div class="callout coral" style="margin:16px 20px 0"><b>Annual re-certification due ${fmtDate(D.verificationExpiry())}.</b> Re-certify now to keep trading without interruption. <button class="btn sm" data-recertify="1" style="margin-left:8px">Re-certify</button></div>` : ''}${verificationCard()}</div>
    </div>
    </div>`;
}

// ---------------- fees, policy, tracker helpers ----------------

// Printable monthly statement.
function viewStatement(main, id) {
  const st = D.statements().find(s => s.id === id) || D.statements()[0]; const a = D.account(); const pr = D.profile();
  const end = new Date(st.ts); end.setDate(0); const start = new Date(end.getFullYear(), end.getMonth(), 1); const inPeriod = r => r.ts >= start.getTime() && r.ts <= end.getTime() + 86399000;
  const ledger = D.cashLedger().filter(inPeriod); const holdings = D.holdings(); const pv = holdings.reduce((s, h) => s + h.value, 0);
  main.innerHTML = `<div class="page narrow statement"><div class="between no-print" style="margin-bottom:14px"><a class="link small" href="#/account">← Account</a><button class="btn sm" id="print-btn">Print / save PDF</button></div>
    <div class="card card-body stack" style="gap:18px">
      <div class="between"><div><div class="row" style="gap:10px"><span class="brand-mark" style="width:30px;height:30px">${LOGO}</span><b style="font-size:18px">Rainmaker Securities, LLC</b></div><div class="small muted">500 North Michigan Avenue, Suite 600 · Chicago, IL 60611 · Member FINRA / SIPC</div></div><div style="text-align:right"><div class="label">Account statement</div><div style="font-size:18px"><b>${esc(st.label.replace(' statement', ''))}</b></div><div class="small muted">${fmtDate(start.getTime())} – ${fmtDate(end.getTime())}</div></div></div>
      <div class="grid-2"><div><div class="label dim">Account holder</div><div><b>${esc(pr.name)}</b></div><div class="small">${esc(pr.email)}${pr.firm ? ' · ' + esc(pr.firm) : ''}</div></div><div><div class="label dim">Account</div><div><b class="mono">${esc(a.number)}</b> · ${esc(a.type)}</div><div class="small">Representative: ${esc(D.rep(pr.rep).name)}</div></div></div>
      <table class="kv tight"><tr><th>Positions value (at RX price)</th><td class="num">${money(pv, 0)}</td></tr><tr><th>Cash balance</th><td class="num">${money(D.cashBalance(), 0)}</td></tr><tr><th>Reserved for open bids</th><td class="num">${money(D.reservedCash(), 0)}</td></tr><tr><th><b>Total account value</b></th><td class="num strong">${money(pv + D.cashBalance(), 0)}</td></tr></table>
      <div><div class="label dim" style="margin-bottom:6px">Positions</div><table class="table compact"><thead><tr><th>Company</th><th class="num">Shares</th><th class="num">Avg cost</th><th class="num">RX price</th><th class="num">Value</th></tr></thead><tbody>${holdings.map(h => `<tr><td>${esc(h.c.name)} <span class="tiny muted">${esc(h.c.ticker)}</span></td><td class="num">${num(h.qty)}</td><td class="num">${money(h.avgCost)}</td><td class="num">${money(h.price)}</td><td class="num">${money(h.value, 0)}</td></tr>`).join('') || '<tr><td colspan="5" class="muted">No positions</td></tr>'}</tbody></table></div>
      <div><div class="label dim" style="margin-bottom:6px">Cash activity in period</div><table class="table compact ledger"><thead><tr><th>Date</th><th>Type</th><th>Detail</th><th class="num">Amount</th></tr></thead><tbody>${ledger.map(r => `<tr><td>${fmtDate(r.ts)}</td><td>${esc(r.kind)}</td><td class="dim">${esc(r.note)}</td><td class="amt ${r.amount >= 0 ? 'in' : 'out'}">${r.amount >= 0 ? '+' : '−'}${money(Math.abs(r.amount), 0)}</td></tr>`).join('') || '<tr><td colspan="4" class="muted">No cash activity in this period</td></tr>'}</tbody></table></div>
      <div class="disclaimer">Private securities are illiquid and valued at the indicative RX price, which is not a quote. Rainmaker Securities acts as introducing broker; securities are held in book-entry with the issuer's transfer agent or an SPV administrator. Prototype statement on generated sample data.</div>
    </div></div>`;
  main.querySelector('#print-btn').onclick = () => window.print();
}
// ---------------- staff console (representatives, compliance, admin) ----------------
