/* ==============================================================
   Rainmaker X · app · back office
   Rep Desk, staff passcode gate, not-found page, the admin pages (Overview, Verifications,
   Compliance forms, Requests, Orders, Companies, Messages, Clients, Audit) and the client page.
   ============================================================== */
'use strict';

// Rep Desk: requests to work, settling orders, quotes, client notes.
function viewDesk(main) {
  const st = D.marketStats(); const stl = D.allSettlements(); const open = stl.filter(x => !D.settlementDone(x)); const mrows = D.matchRecords(); const pendM = mrows.filter(r => r.status === 'pending');
  const desk = D.deskTrades(); const captured = desk.reduce((s_, t) => s_ + t.capture, 0);
  const demand = D.COMPANIES.map(c => ({ c, s: D.ioiSummary(c.id), asks: D.liveListings(c.id).length, bids: D.liveBids(c.id).length })).sort((a, b) => (b.s.buys + b.s.sells) - (a.s.buys + a.s.sells)).slice(0, 10);
  const clients = D.CLIENTS.map(cl => Object.assign({}, cl)); clients[0].status = D.profile().verification; clients[0].type = D.profile().investorType || 'accredited';
  const badge = s_ => s_ === 'verified' ? '<span class="badge verified">Verified</span>' : s_ === 'pending' ? '<span class="badge pending">Pending review</span>' : '<span class="badge status">Unverified</span>';
  main.innerHTML = `<div class="page">
    ${pageHead({ icon: PH.desk, title: 'Rep Desk', tag: 'Internal', sub: 'What a registered representative sees: open orders, settlements waiting on paperwork, the client book, and where demand is building.', actions: `<a class="btn sm" href="#/admin">Open the console</a><a class="btn outline sm" href="#/representatives">Representatives</a>` })}
    <div class="tiles"><div class="card tile"><span class="label dim">Live asks</span><div class="v">${st.asks}</div><div class="small muted">${compact(st.askValue)} offered</div></div><div class="card tile"><span class="label dim">Live bids</span><div class="v">${st.bids}</div><div class="small muted">${compact(st.bidValue)} demand</div></div><div class="card tile"><span class="label dim">Matches</span><div class="v">${pendM.length}</div><div class="small muted">awaiting approval · ${open.length} settling</div></div><div class="card tile"><span class="label dim">Desk spread captured</span><div class="v up">${money(captured, 0)}</div><div class="small muted">${desk.length} principal trades</div></div></div>
    <div class="dash" style="grid-template-columns: minmax(0,1.3fr) minmax(0,1fr)">
      <div class="stack">
        ${(() => { const rq = D.requests().filter(r => r.status === 'pending'); return `<div class="card"><div class="card-head"><span class="label">Requests from members awaiting verification</span><span class="badge ${rq.length ? 'pending' : 'status'}">${rq.length} open</span></div>${rq.length ? `<table class="table compact"><thead><tr><th>Request</th><th>Client</th><th>What</th><th>Submitted</th></tr></thead><tbody>${rq.map(r => `<tr><td><span class="oid">${esc(r.id)}</span></td><td>${esc(D.profile().name)} <span class="tiny muted">${esc(D.profile().verification)}</span></td><td>${esc(r.what)}</td><td>${fmtPlaced(r.created)}</td></tr>`).join('')}</tbody></table><div class="card-foot small">Work these off the book. They are placed automatically when compliance approves the client (<a class="link" href="#/profile/verification">simulate approval</a>).</div>` : '<div class="card-body small muted">No pending requests.</div>'}</div>`; })()}
        <div class="card"><div class="card-head"><span class="label">Matches</span><span class="muted small">${pendM.length} awaiting approval · ${open.length} settling · <a class="link" href="#/admin/matches">Matches queue</a></span></div>${matchesTable(mrows.filter(r => r.label !== 'Completed').slice(0, 12), { staff: true, empty: 'No open matches.' })}</div>
        <div class="card"><div class="card-head"><span class="label">Demand map · indications of interest</span><a class="link small" href="#/browse">Browse</a></div><table class="table compact"><thead><tr><th>Company</th><th class="num">Buyers</th><th class="num">Top buy price</th><th class="num">Sellers</th><th class="num">Low sell price</th><th class="num">RX price</th><th class="num">Asks / Bids</th></tr></thead><tbody>${demand.map(d => `<tr class="clickable" data-href="#/company/${d.c.id}"><td><span class="row">${logo(d.c, 'sm')}<b>${esc(d.c.name)}</b></span></td><td class="num strong">${d.s.buys}</td><td class="num">${money(d.s.topBuy)}</td><td class="num strong">${d.s.sells}</td><td class="num">${money(d.s.lowSell)}</td><td class="num">${money(D.price(d.c.id))}</td><td class="num">${d.asks} / ${d.bids}</td></tr>`).join('')}</tbody></table></div>
      </div>
      <div class="stack">
        ${(() => { const rr = D.pendingRepRequests(); return `<div class="card"><div class="card-head"><span class="label">Primary representative requests</span><span class="badge ${rr.length ? 'pending' : 'status'}">${rr.length} waiting</span></div>${rr.length ? `<table class="table compact"><tbody>${rr.map(r => `<tr><td><a class="link" href="#/client/${esc(r.clientId)}"><b>${esc(r.clientName)}</b></a><div class="tiny muted">${esc(D.rep(r.from).name)} → <b>${esc(D.rep(r.to).name)}</b> · ${esc(r.by.replace('staff:', ''))} · ${fmtDateShort(r.ts)}</div></td><td class="num"><span class="row" style="justify-content:flex-end;gap:6px"><button class="btn bid sm" type="button" data-rr-approve="${esc(r.id)}">Accept</button><button class="btn danger sm" type="button" data-rr-deny="${esc(r.id)}">Deny</button></span></td></tr>`).join('')}</tbody></table><div class="card-foot small">A member or an administrator proposed you as primary representative. Accepting moves the client, their orders and settlements to you.</div>` : '<div class="card-body muted small">No one is waiting to be taken on.</div>'}</div>`; })()}
        <div class="card"><div class="card-head"><span class="label">Client book</span><span class="muted small">${clients.filter(x => x.status === 'pending').length} awaiting compliance</span></div><table class="table compact"><thead><tr><th>Client</th><th>Type</th><th>Status</th><th>Rep</th></tr></thead><tbody>${clients.map(cl => `<tr><td><b>${esc(cl.name)}</b>${cl.aum ? `<div class="tiny muted">${compact(cl.aum)} on platform</div>` : ''}</td><td class="small">${esc(D.INVESTOR_TYPES[cl.type].split(' (')[0])}</td><td>${badge(cl.status)}</td><td class="small">${esc(D.rep(cl.rep).name.split(' ')[0])}</td></tr>`).join('')}</tbody></table></div>
        <div class="card"><div class="card-head"><span class="label">Client inbox</span><span class="muted small">Messages from ${esc(D.profile().name)}</span></div><div class="card-body stack" style="gap:10px">${(() => { const mine = D.messages().filter(m => m.from === 'you').slice(-4).reverse(); return mine.length ? mine.map(m => { const c = m.companyId ? D.company(m.companyId) : null; return `<div class="inbox-item"><div class="small"><b>${c ? esc(c.name) : 'General'}${m.orderId ? ' · ' + esc(m.orderId) : ''}</b> · ${fmtPlaced(m.ts)}</div><div class="small" style="margin:4px 0 8px">${esc(m.text)}</div><form class="row" data-reply="${esc(m.key)}" data-company="${m.companyId || ''}" data-order="${m.orderId || ''}"><input class="mini" name="text" placeholder="Reply as ${esc(D.rep(D.profile().rep).name.split(' ')[0])}…" style="flex:1" required><button class="btn sm dark" type="submit">Reply</button></form></div>`; }).join('') : '<div class="muted small">No client messages yet.</div>'; })()}</div></div>
        <div class="card"><div class="card-head"><span class="label">Desk activity</span><span class="muted small">Principal trades</span></div>${desk.length ? `<table class="table compact"><thead><tr><th>Company</th><th>Side</th><th class="num">Qty</th><th class="num">Price</th><th class="num">Captured</th></tr></thead><tbody>${desk.slice(0, 8).map(t => { const c = D.company(t.companyId); return `<tr><td>${esc(c.name)}</td><td>${t.side === 'buy' ? 'Sold to client' : 'Bought from client'}</td><td class="num">${num(t.qty)}</td><td class="num">${money(t.price)}</td><td class="num up">${money(t.capture, 0)}</td></tr>`; }).join('')}</tbody></table>` : '<div class="card-body muted small">No desk trades yet.</div>'}</div>
        <div class="card"><div class="card-head"><span class="label">Alerts armed by clients</span></div>${D.alerts().length ? `<table class="table compact"><tbody>${D.alerts().map(a => { const c = D.company(a.companyId); return `<tr><td>${esc(c.name)}</td><td class="small">${esc(D.ALERT_TYPES[a.type])} ${money(a.price)}</td><td>${a.triggered ? '<span class="badge verified">Fired</span>' : '<span class="badge status">Armed</span>'}</td></tr>`; }).join('')}</tbody></table>` : '<div class="card-body muted small">None.</div>'}</div>
      </div>
    </div></div>`;
  main.querySelectorAll('[data-reply]').forEach(f => f.addEventListener('submit', e => { e.preventDefault(); D.sendMessage({ companyId: f.dataset.company || null, orderId: f.dataset.order || null, text: f.text.value.trim(), from: 'rep' }); toast('Reply sent to client'); render(); }));
}


// Not found (also what non-staff see for staff routes).
function viewNotFound(main) { main.innerHTML = `<div class="page narrow" style="max-width:560px"><div class="card card-body stack"><h2>Page not found</h2><p class="muted" style="margin:0">There is nothing at this address.</p><div class="row"><a class="btn sm" href="#/dashboard">Dashboard</a><a class="btn outline sm" href="#/browse">Browse companies</a></div></div></div>`; }
// Staff passcode gate for #/staff/<role>.
function viewStaffGate(main, role) {
  if (!D.ROLES[role] || role === 'client') return viewNotFound(main);
  if (D.role() === role) { go('#/admin'); return; }
  main.innerHTML = `<div class="page narrow" style="max-width:520px"><form class="card gate" id="staff-gate"><div class="card-head"><span class="row" style="gap:10px"><span class="gate-lock">${LOCK}</span><h2 style="font-size:20px">Staff access · ${esc(D.ROLES[role])}</h2></span></div><div class="card-body stack">
    <p class="small muted" style="margin:0">This area holds client, order and compliance records. Access is limited to authorized Rainmaker personnel and every entry is logged.</p>
    <div class="field"><label>Staff passcode</label><input name="code" type="password" autocomplete="off" required placeholder="••••••••"></div>
    <div class="tiny down" id="gate-err"></div>
    <ul class="small muted" style="margin:0;padding-left:18px"><li>The session lives in this tab only and locks after ${Math.round(D.STAFF_IDLE_MS / 60000)} minutes idle.</li><li>Every sign-in, lock, approval and failed attempt is written to the audit log.</li><li>Staff pages are hidden from members and visitors and answer "not found".</li></ul>
    <div class="callout tiny">Prototype passcode: <b>${esc(RX_CONFIG.staff.demoPasscode)}</b>. At launch this is replaced by staff identity with MFA on Rainmaker's servers, and no staff data is sent to a member's browser.</div>
  </div><div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Enter ${esc(D.ROLES[role])} view</button><a class="btn ghost" href="#/dashboard">Cancel</a></div></form></div>`;
  const f = main.querySelector('#staff-gate'); setTimeout(() => f.code.focus(), 0);
  f.addEventListener('submit', e => { e.preventDefault(); const r = D.staffSignIn(role, f.code.value); if (r.error) { main.querySelector('#gate-err').textContent = r.error; f.code.value = ''; f.code.focus(); return; } toast(`Switched to ${D.ROLES[role]} view`); go('#/admin'); });
}

// Back-office tabs: [id, label, permission needed].
const ADMIN_TABS = [['overview', 'Overview'], ['verifications', 'Verifications', 'verifications'], ['requests', 'Requests', 'requests'], ['orders', 'Orders', 'orders.view'], ['matches', 'Matches', 'matches'], ['companies', 'Companies', 'companies'], ['inbox', 'Messages', 'inbox'], ['mailbox', 'Rainmaker mailbox', 'inbox'], ['clients', 'Clients', 'clients'], ['forms', 'Compliance forms', 'forms'], ['audit', 'Activity log', 'audit']];
// Every back-office page is titled by what it is (Orders, Compliance forms, …), never "Console" (Ben, Sep 25 2026).
const ADMIN_META = {
  overview: { t: 'Overview', icon: () => PH.console, sub: 'Everything clients submit lands here: verifications, forms, requests, orders, settlements and messages.' },
  verifications: { t: 'Verifications', icon: () => PH.verify, sub: 'Investor status reviews. Approving a client places their pending requests on the book.' },
  forms: { t: 'Compliance forms', icon: () => PH.forms, sub: 'Accreditation, KYC, tax, subscription, term-sheet and transfer paperwork awaiting a decision.' },
  requests: { t: 'Requests', icon: () => PH.requests, sub: 'Orders submitted by members who are not yet verified, plus structured deals in the desk pipeline.' },
  mailbox: { t: 'Rainmaker mailbox', icon: () => PH.mail, sub: 'Rainmaker Securities as a correspondent: what members send to the firm (support and operations, not to a representative) and what the firm sends out. Representatives\' conversations are monitored under Messages.' },
  orders: { t: 'Orders', icon: () => PH.orders, sub: 'Every bid, ask, custom order and structured deal on the exchange, newest first. Orders carry no settlement state: when two cross, the match appears under Matches and settles there.' },
  matches: { t: 'Matches', icon: () => PH.settle, sub: 'Every clearance event: a buyer and a seller whose orders crossed. Approve a match to notify both parties and open the settlement; open one to record signatures, the broker fee and each closing step.' },
  companies: { t: 'Companies', icon: () => PH.companies, sub: 'Listed companies, transfer policies and fees.' },
  inbox: { t: 'Messages', icon: () => PH.mail, sub: 'Every message from every member, monitored by Rainmaker. Filter by user, representative or sender, or search by keyword.' },
  clients: { t: 'Clients', icon: () => PH.clients, sub: 'The client book: status, representative, assets and activity.' },
  audit: { t: 'Activity log', icon: () => PH.audit, sub: 'Everything that happens on the exchange, newest first: orders, matches, settlements, approvals, staff sessions, messages, exports. Filter by kind, actor, period or keyword.' },
};
// ---- shared filter bar for the back-office tabs. State lives in D.state.adminF[tab]; every list defaults to newest entered first.
function afState(tab, defaults) { const S = D.state.adminF || (D.state.adminF = {}); if (!S[tab]) S[tab] = Object.assign({}, defaults); else Object.keys(defaults).forEach(k => { if (S[tab][k] === undefined) S[tab][k] = defaults[k]; }); return S[tab]; }
// Render the shared back-office filter bar from a field list.
function afBar(F, fields) {
  const opt = (v, l, cur) => `<option value="${esc(String(v))}" ${String(cur) === String(v) ? 'selected' : ''}>${esc(l)}</option>`;
  return `<div class="af-bar">${fields.map(f => f.q != null ? `<input class="mini" data-afq="${f.k}" placeholder="${esc(f.q)}" value="${esc(F[f.k] || '')}" style="width:${f.w || 200}px">` : f.date ? `<label class="af-date" title="${esc(f.title || '')}"><span>${esc(f.date)}</span><input class="mini" type="date" data-afd="${f.k}" value="${esc(F[f.k] || '')}"></label>` : `<select class="mini" data-afs="${f.k}" title="${esc(f.title || '')}">${f.sel.map(([v, l]) => opt(v, l, F[f.k])).join('')}</select>`).join('')}<button class="btn ghost xs" type="button" data-af-clear>Clear</button></div>`;
}
// Hook the filter bar up: write to state.adminF[tab] and re-render.
function wireAf(main, tab, defaults, redraw) {
  const bar = main.querySelector('.af-bar'); if (!bar) return; const F = afState(tab, defaults); const draw = redraw || (() => viewAdmin(main, tab));   // member pages (Market activity) pass their own redraw
  bar.querySelectorAll('[data-afs]').forEach(s => s.onchange = () => { F[s.dataset.afs] = s.value; draw(); });
  bar.querySelectorAll('[data-afd]').forEach(d => d.onchange = () => { F[d.dataset.afd] = d.value; draw(); });   // date inputs: "placed between" (Ben, Oct 1 2026)
  bar.querySelectorAll('[data-afq]').forEach(q => q.addEventListener('input', () => { F[q.dataset.afq] = q.value; const pos = q.selectionStart; draw(); const n = main.querySelector(`[data-afq="${q.dataset.afq}"]`); if (n) { n.focus(); n.setSelectionRange(pos, pos); } }));
  const cl = bar.querySelector('[data-af-clear]'); if (cl) cl.onclick = () => { D.state.adminF[tab] = Object.assign({}, defaults); draw(); };
}
// Case-insensitive keyword match across several values.
const afHas = (q, ...vals) => { q = (q || '').trim().toLowerCase(); return !q || vals.some(v => String(v == null ? '' : v).toLowerCase().includes(q)); };
// Sort a list by the chosen key using the getter map.
const afSort = (list, key, g) => list.slice().sort((a, b) => { const f = g[key] || g.newest; const va = f(a), vb = f(b); return typeof va === 'string' ? va.localeCompare(vb) : va - vb; });
// Representative select options.
const repOpts = () => [['all', 'All representatives']].concat(D.REPS.map(r => [r.id, r.name]));
// Company select options, A–Z.
const coOpts = () => [['all', 'All companies']].concat(D.COMPANIES.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.id, c.name]));
// Settlement status badge.
const stlBadge = s => s ? `<span class="badge ${s === 'Complete' ? 'verified' : 'pending'}">${s}</span>` : '<span class="dim small">—</span>';
// Representative as "First L.".
const repShort = id => { const r = D.rep(id); return r ? esc(r.name.split(' ')[0] + ' ' + r.name.split(' ').slice(-1)[0][0] + '.') : '—'; };
// Whether the New company / Record order forms are open.
let adminNewCo = false; let adminNewOrder = false; let adminNewMail = false;   // compose forms open / closed (Record order, Rainmaker mailbox)
// Orders tab bulk selection (Ben, Oct 1 2026): ids ticked on the Orders list and whether the inline "Remove selected" confirmation is open. Not persisted.
let ordSel = new Set(); let ordRmOpen = false;
// Client select options, A–Z (the member session first).
const clientOpts = () => [['all', 'All clients']].concat(D.clientsList().slice().sort((a, b) => (a.you ? -1 : b.you ? 1 : a.name.localeCompare(b.name))).map(k => [k.id, k.name + (k.you ? ' (member session)' : '')]));
// ---- export buttons (data-export="orders-csv" etc.). The Data layer checks permissions and audits each export.
const EXPORTS = {
  'orders-csv': () => { const r = D.exportOrders(); return r.error ? r : { name: exportName('orders', 'csv'), text: D.toCSV(r.rows, r.columns), mime: 'text/csv', n: r.rows.length, what: 'orders' }; },
  'orders-json': () => { const r = D.exportOrders(); return r.error ? r : { name: exportName('orders', 'json'), text: JSON.stringify(r.rows, null, 2), mime: 'application/json', n: r.rows.length, what: 'orders' }; },
  'forms-csv': () => { const r = D.exportForms(); return r.error ? r : { name: exportName('compliance-forms', 'csv'), text: D.toCSV(r.rows, r.columns), mime: 'text/csv', n: r.rows.length, what: 'forms' }; },
  'forms-json': () => { const r = D.exportForms(); return r.error ? r : { name: exportName('compliance-forms', 'json'), text: JSON.stringify(r.rows, null, 2), mime: 'application/json', n: r.rows.length, what: 'forms' }; },
  'matches-csv': () => { const r = D.exportMatches(); return r.error ? r : { name: exportName('matches', 'csv'), text: D.toCSV(r.rows, r.columns), mime: 'text/csv', n: r.rows.length, what: 'matches' }; },
  'matches-json': () => { const r = D.exportMatches(); return r.error ? r : { name: exportName('matches', 'json'), text: JSON.stringify(r.rows, null, 2), mime: 'application/json', n: r.rows.length, what: 'matches' }; },
  'all-json': () => { const b = D.exportBundle(); return b.error ? b : { name: exportName('all-records', 'json'), text: JSON.stringify(b, null, 2), mime: 'application/json', n: b.counts.orders + b.counts.forms, what: 'records' }; },
};
function wireExports(root) {
  root.querySelectorAll('[data-export]').forEach(btn => btn.onclick = () => {
    const make = EXPORTS[btn.dataset.export]; if (!make) return;
    const r = make(); if (r.error) { toast(r.error, false); return; }
    downloadFile(r.name, r.text, r.mime); toast(`${r.n} ${r.what} downloaded (${r.name})`);
  });
}
// Fee rate as a percentage string.
function feePct(r) { const v = r * 100; return (v % 1 ? v.toFixed(2) : v.toFixed(0)) + '%'; }
// Settlement card for the Console: tracker, contract signatures from both sides, broker fees (adjustable per deal), documents.
function settlementPanel(x) {
  const c = D.company(x.companyId); const done = D.settlementDone(x); const p = x.parties || {}; const f = D.settlementFees(x); const kind = D.settleKind(x);
  const buyerName = x.side === 'buy' ? D.profile().name : (kind === 'desk' ? 'Rainmaker desk (principal)' : 'Buyer · brokered'); const sellerName = x.side === 'sell' ? D.profile().name : (kind === 'desk' ? 'Rainmaker desk (principal)' : 'Seller · brokered');
  const sigRow = (who, name, ts) => `<div class="prow"><span><b>${who}</b> <span class="muted">· ${esc(name)}</span></span>${ts ? `<span class="badge verified">Signed ${fmtDateShort(ts)}</span>` : `<button class="btn outline sm" data-stl-mark="${x.id}" data-what="${who.toLowerCase()}">Record ${who.toLowerCase()} signature</button>`}</div>`;
  return `<div class="pipe-row" id="stl-${esc(x.id)}"><div class="between" style="margin-bottom:8px;flex-wrap:wrap;gap:8px"><span class="row">${logo(c, 'sm')}<b>${esc(c.name)}</b><span class="muted small">${x.side === 'buy' ? 'Client buys' : 'Client sells'} ${num(x.qty)} @ ${money(x.price)} · ${money(x.gross, 0)} gross · ${kind === 'desk' ? 'desk' : 'exchange match'}</span></span><span class="row" style="gap:10px">${stlBadge(D.settlementStatus(x))}<span class="muted small">Entered ${fmtPlaced(x.ts)} · rep ${repShort(D.assignedRep({ mine: true }))}</span></span></div>
    ${trackerBlock(x, { compact: true })}
    <div class="stl-grid"><div class="stl-box"><span class="label dim">Contract signatures</span><div class="tiny muted" style="margin-bottom:4px">Rainmaker has both sides sign the stock transfer agreement before any money moves.</div>${sigRow('Buyer', buyerName, p.buyer)}${sigRow('Seller', sellerName, p.seller)}</div>
    <div class="stl-box"><span class="label dim">Broker fees</span><div class="tiny muted" style="margin-bottom:4px">Default 3% buy side · 2% sell side (min ${money(D.FEES.brokerageMin, 0)}). Adjust per deal.</div>
      <form class="fee-form" data-stl-fee-form="${esc(x.id)}"><div class="field"><label>Buy side %</label><input class="mini" name="buy" type="number" step="0.25" min="0" max="20" value="${(f.buyRate * 100).toFixed(2).replace(/\.?0+$/, '')}" ${p.fees ? 'disabled' : ''}></div><div class="field"><label>Sell side %</label><input class="mini" name="sell" type="number" step="0.25" min="0" max="20" value="${(f.sellRate * 100).toFixed(2).replace(/\.?0+$/, '')}" ${p.fees ? 'disabled' : ''}></div>${p.fees ? '' : '<button class="btn ghost sm" type="submit">Save rates</button>'}</form>
      <div class="prow"><span>Buyer pays <b>${money(f.buy, 0)}</b> · seller pays <b>${money(f.sell, 0)}</b> · total <b>${money(f.total, 0)}</b>${f.custom ? ' <span class="badge custom">Adjusted</span>' : ''}</span>${p.fees ? `<span class="badge verified">Paid ${fmtDateShort(p.fees)}</span>` : `<button class="btn outline sm" data-stl-mark="${x.id}" data-what="fees">Record fee payment</button>`}</div></div></div>
    ${docsBlock(x)}<div class="between" style="margin-top:8px"><span class="tiny muted">${done ? 'Closed ' + fmtDate(x.steps[D.settleSteps(x).length - 1] || x.ts) : 'Next: ' + esc(D.settleSteps(x)[x.stage + 1] || '')}</span>${done ? '<span class="badge verified">Complete</span>' : `<button class="btn outline sm" data-advance="${x.id}">Mark next step done</button>`}</div></div>`;
}
// Hook up the per-deal broker fee forms on settlement panels.
function wireFeeForms(root) { root.querySelectorAll('[data-stl-fee-form]').forEach(f => f.addEventListener('submit', e => { e.preventDefault(); const r = D.setSettlementFees(f.dataset.stlFeeForm, (+f.buy.value || 0) / 100, (+f.sell.value || 0) / 100); if (r.error) { toast(r.error, false); return; } toast('Broker fee rates saved for this deal'); const y = window.scrollY; render(); window.scrollTo(0, y); })); }
// Back office: one page per tab (Overview, Verifications, Compliance forms, Requests, Orders, Companies, Messages, Clients, Audit).
function viewAdmin(main, tab, id) {
  if (!D.isStaff()) { D.accessDenied('#/admin'); return viewNotFound(main); }
  if (tab === 'settlements') { afState('matches', { q: '', status: 'all', company: 'all', rep: 'all', sort: 'newest' }).status = 'settling'; tab = 'matches'; } // Settlements live on matches (Ben, Sep 30 2026)
  if (tab === 'activity') tab = 'audit';
  const tabs = ADMIN_TABS.filter(t => !t[2] || D.can(t[2])); if (!tabs.find(t => t[0] === tab)) tab = 'overview';
  const clients = D.clientsList(); const reqs = D.requests(); const pending = reqs.filter(r => r.status === 'pending'); const stl = D.allSettlements(); const pendM = D.pendingMatches();
  const arrsAll = D.allArrangements(); const arrOpen = arrsAll.filter(x => ['submitted', 'structuring', 'term sheet'].includes(x.status)); const open = stl.filter(x => !D.settlementDone(x));
  const verQueue = clients.filter(c => c.status === 'pending'); const allMsgs = D.allMessages(); const inbox = allMsgs.filter(m => m.from === 'you'); const st = D.marketStats();
  const role = D.role(); const badge = s_ => s_ === 'verified' ? '<span class="badge verified">Verified</span>' : s_ === 'pending' ? '<span class="badge pending">Pending review</span>' : '<span class="badge status">Unverified</span>';
  let body = ''; let DEF = null; let actions = ''; let stats = null;
  if (tab === 'overview') { actions = `<a class="btn outline sm" href="#/desk">Rep Desk</a><a class="btn outline sm" href="#/browse">Browse companies</a>${D.can('audit') ? '<button class="btn outline sm" type="button" data-export="all-json">Download all records</button>' : ''}`;
    body = `<div class="kpis" style="grid-template-columns:repeat(5,minmax(0,1fr))">
      ${D.can('verifications') ? `<a class="kpi" href="#/admin/verifications"><span class="label">Verifications to review</span><div class="v">${verQueue.length}</div><div class="s">${clients.filter(c => c.status === 'unverified').length} unverified members</div></a>` : ''}
      ${D.can('forms') ? `<a class="kpi" href="#/admin/forms"><span class="label">Forms awaiting review</span><div class="v">${D.formsPending()}</div><div class="s">${D.forms().length} compliance forms on file</div></a>` : ''}
      <a class="kpi" href="#/admin/requests"><span class="label">Requests to work</span><div class="v">${pending.length + arrOpen.length}</div><div class="s">${arrOpen.length} structured deals in the desk pipeline</div></a>
      <a class="kpi" href="#/admin/matches"><span class="label">Matches awaiting approval</span><div class="v">${pendM.length}</div><div class="s">${open.length} settling · ${money(open.reduce((s_, x) => s_ + (x.parties && x.parties.fees ? 0 : D.settlementFees(x).total), 0), 0)} fees outstanding</div></a>
      <a class="kpi" href="#/admin/inbox"><span class="label">Client messages</span><div class="v">${inbox.length}</div><div class="s">${inbox.filter(m => Date.now() - m.ts < 2 * DAYMS).length} in the last 2 days · ${new Set(inbox.map(m => m.clientId)).size} users</div></a>
      <a class="kpi" href="#/admin/orders"><span class="label">Live orders on the book</span><div class="v">${st.asks + st.bids}</div><div class="s">${Object.keys(D.state.flags || {}).length} flagged</div></a></div>
    <div class="dash" style="grid-template-columns:minmax(0,1.3fr) minmax(0,1fr)"><div class="stack">
      <div class="card"><div class="card-head"><span class="label">Work queue</span><span class="small muted">Everything clients submit lands here</span></div><div class="todo-list">${[
        ...verQueue.map(c => ({ t: `Verify ${c.name}`, s: `${D.INVESTOR_TYPES[c.type]} · submitted ${fmtDateShort(c.submittedAt)}`, href: '#/admin/verifications', tone: 'coral' })),
        ...(D.can('forms') ? D.forms().filter(f => f.status === 'Awaiting review').slice(0, 4).map(f => ({ t: `${D.FORM_KINDS[f.kind]} · ${f.client ? f.client.name : ''}`, s: f.detail, href: '#/admin/forms', tone: 'coral' })) : []),
        ...pending.map(r => ({ t: `${r.id} · ${r.what}`, s: `From ${D.profile().name} · ${fmtPlaced(r.created)}`, href: '#/admin/requests' })),
        ...D.pendingRepRequests().map(r => ({ t: `Primary rep change · ${r.clientName}`, s: `${D.rep(r.from).name} → ${D.rep(r.to).name} · ${r.by.replace('staff:', '')}`, href: '#/client/' + r.clientId })),
        ...pendM.map(m => ({ t: `Approve match ${m.id} · ${D.company(m.companyId).name}`, s: `${num(m.qty)} @ ${money(m.price)} · ${m.buyerName} buys from ${m.sellerName}`, href: '#/match/' + m.id, tone: 'coral' })),
        ...arrOpen.map(x => ({ t: `${x.id} · ${D.ARRANGEMENT_TYPES[x.type]} · ${x.status}`, s: x.what, href: '#/admin/requests', tone: 'green' })),
        ...open.slice(0, 3).map(x => { const p = x.parties || {}; const need = !p.buyer || !p.seller ? `Waiting on ${!p.buyer && !p.seller ? 'both signatures' : !p.buyer ? 'the buyer\'s signature' : 'the seller\'s signature'}` : !p.fees ? `Broker fees of ${money(D.settlementFees(x).total, 0)} outstanding` : `Next: ${D.settleSteps(x)[x.stage + 1] || ''}`; return { t: `${D.company(x.companyId).name} settlement ${x.id.slice(-6).toUpperCase()}`, s: need, href: '#/order/' + (x.txId || x.id) }; }),
        ...inbox.slice(0, 3).map(m => ({ t: `Message from ${m.clientName}`, s: m.text.slice(0, 90), href: '#/admin/inbox' }))].map(i => `<a class="todo-item ${i.tone || ''}" href="${i.href}"><span class="todo-dot"></span><span class="todo-body"><b>${esc(i.t)}</b><div class="small muted">${esc(i.s)}</div></span></a>`).join('') || '<div class="card-body small muted">Queue is empty.</div>'}</div></div>
      ${auditCard(10)}</div>
      <div class="stack"><div class="card"><div class="card-head"><span class="label">Book of business</span></div><table class="kv tight" style="padding:0 20px"><tr><th>Clients</th><td>${clients.length} · ${clients.filter(c => c.status === 'verified').length} verified</td></tr><tr><th>Assets on platform</th><td>${compact(clients.reduce((s_, c) => s_ + (c.aum || 0), 0))}</td></tr><tr><th>Live asks / bids</th><td>${st.asks} / ${st.bids} · ${compact(st.askValue + st.bidValue)}</td></tr><tr><th>30-day volume</th><td>${compact(st.vol30)} · ${st.tx30} matches</td></tr><tr><th>Desk spread captured</th><td>${money(D.deskTrades().reduce((s_, t) => s_ + t.capture, 0), 0)}</td></tr><tr><th>Broker fees</th><td>${feePct(D.FEES.buy)} buy side · ${feePct(D.FEES.sell)} sell side · adjustable per deal</td></tr><tr><th>Companies listed</th><td>${D.COMPANIES.length}</td></tr></table></div>
      <div class="card"><div class="card-head"><span class="label">Your permissions · ${esc(D.ROLES[role])}</span></div><div class="card-body tags">${D.STAFF_PERMS[role].map(p => `<span class="tag">${esc(p)}</span>`).join('')}</div></div></div></div>`; }

  if (tab === 'verifications') { DEF = { q: '', status: 'all', rep: 'all', sort: 'newest' }; const F = afState(tab, DEF);
    const list = afSort(clients.filter(c => (F.status === 'all' || c.status === F.status) && (F.rep === 'all' || c.rep === F.rep) && afHas(F.q, c.name, c.email, D.INVESTOR_TYPES[c.type])), F.sort, { newest: c => -(c.submittedAt || 0), oldest: c => c.submittedAt || 0, name: c => c.name, rep: c => D.rep(c.rep).name });
    stats = [['Pending review', verQueue.length], ['Verified', clients.filter(c => c.status === 'verified').length], ['Unverified', clients.filter(c => c.status === 'unverified').length]];
    body = `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Client name or email' }, { k: 'status', sel: [['all', 'All statuses'], ['pending', 'Pending review'], ['verified', 'Verified'], ['unverified', 'Unverified']] }, { k: 'rep', sel: repOpts() }, { k: 'sort', sel: [['newest', 'Newest submitted'], ['oldest', 'Oldest submitted'], ['name', 'Client A–Z'], ['rep', 'By representative']] }])}<span class="small muted">${list.length} of ${clients.length}</span></div>${list.length ? `<table class="table"><thead><tr><th>Client</th><th>Declared as</th><th>Basis</th><th>Rep</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>${list.map(c => `<tr><td><a class="link" style="text-decoration:none" href="#/client/${c.id}"><b>${esc(c.name)}</b></a>${c.you ? ' <span class="badge mine">You</span>' : ''}<div class="tiny muted">${esc(c.email)}</div></td><td class="small">${esc(D.INVESTOR_TYPES[c.type] || c.type)}</td><td class="small">${(c.basis || []).join(', ') || '—'}</td><td class="small rep-cell">${repShort(c.rep)}</td><td class="small">${c.submittedAt ? fmtPlaced(c.submittedAt) : '—'}</td><td>${badge(c.status)}${c.note ? `<div class="tiny muted">${esc(c.note)}</div>` : ''}</td><td class="num"><span class="row" style="justify-content:flex-end;gap:6px">${c.status === 'pending' ? `<button class="btn bid sm" data-ver-approve="${c.id}">Approve</button><button class="btn danger sm" data-ver-reject="${c.id}">Send back</button>` : c.status === 'verified' ? `<button class="btn ghost sm" data-ver-reject="${c.id}">Revoke</button>` : '<span class="tiny muted">Waiting on client</span>'}</span></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No clients match these filters.</div>'}<div class="card-foot small">Approving a client places their approved and pending requests on the book. Sending back notifies them with your note.</div></div>`; }

  if (tab === 'requests') { DEF = { q: '', status: 'all', company: 'all', sort: 'newest' }; const F = afState(tab, DEF);
    const rq = afSort(reqs.filter(r => (F.status === 'all' || (F.status === 'open' ? r.status === 'pending' : F.status === 'closed' ? r.status !== 'pending' : r.status === F.status)) && (F.company === 'all' || r.companyId === F.company) && afHas(F.q, r.id, r.what, r.note, D.profile().name, r.companyId && D.company(r.companyId) ? D.company(r.companyId).name : '')), F.sort, { newest: r => -r.created, oldest: r => r.created, company: r => r.companyId && D.company(r.companyId) ? D.company(r.companyId).name : 'zzz', status: r => r.status });
    const ar = afSort(arrsAll.filter(a => (F.status === 'all' || (F.status === 'open' ? ['submitted', 'structuring', 'term sheet'].includes(a.status) : F.status === 'closed' ? !['submitted', 'structuring', 'term sheet'].includes(a.status) : a.status === F.status)) && (F.company === 'all' || a.companyId === F.company) && afHas(F.q, a.id, a.what, a.note, D.ARRANGEMENT_TYPES[a.type], a.companyId && D.company(a.companyId) ? D.company(a.companyId).name : '')), F.sort, { newest: a => -a.created, oldest: a => a.created, company: a => a.companyId && D.company(a.companyId) ? D.company(a.companyId).name : 'zzz', status: a => a.status });
    stats = [['Requests pending', pending.length], ['Structured deals open', arrOpen.length], ['Total', reqs.length + arrsAll.length]];
    body = `<div class="card" style="margin-bottom:18px"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Ref, client or terms', w: 220 }, { k: 'status', sel: [['all', 'All statuses'], ['open', 'Open'], ['closed', 'Decided'], ['pending', 'Pending'], ['approved', 'Approved'], ['converted', 'Converted'], ['rejected', 'Declined'], ['term sheet', 'Term sheet'], ['executed', 'Executed']] }, { k: 'company', sel: coOpts() }, { k: 'sort', sel: [['newest', 'Newest entered'], ['oldest', 'Oldest entered'], ['company', 'Company A–Z'], ['status', 'By status']] }])}<span class="small muted">${rq.length + ar.length} of ${reqs.length + arrsAll.length}</span></div></div>
      <div class="card" style="margin-bottom:18px"><div class="card-head"><span class="label">Structured arrangements · desk pipeline</span><span class="small muted">${ar.length} shown · rep ${repShort(D.profile().rep)}</span></div>${ar.length ? arrangementsTable(ar, true) : '<div class="empty">No structured deals match.</div>'}</div>
      <div class="card"><div class="card-head"><span class="label">Requests from members awaiting verification</span><span class="small muted">${rq.length} shown</span></div>${rq.length ? `<table class="table"><thead><tr><th>Request</th><th>Client</th><th>Rep</th><th>What</th><th>Entered</th><th>Status</th><th></th></tr></thead><tbody>${rq.map(r => `<tr><td><span class="oid">${esc(r.id)}</span></td><td><a class="link" style="text-decoration:none" href="#/client/you">${esc(D.profile().name)}</a><div class="tiny muted">${badge(D.profile().verification)}</div></td><td class="small rep-cell">${repShort(D.profile().rep)}</td><td>${esc(r.what)}${r.note ? `<div class="tiny muted">Client note: ${esc(r.note)}</div>` : ''}${r.staffNote ? `<div class="tiny muted">Staff: ${esc(r.staffNote)}</div>` : ''}</td><td class="small">${fmtPlaced(r.created)}</td><td><span class="badge ${r.status === 'converted' || r.status === 'approved' ? 'verified' : r.status === 'pending' ? 'pending' : 'status'}">${esc(r.status)}</span></td><td class="num"><span class="row" style="justify-content:flex-end;gap:6px">${r.status === 'pending' ? `<button class="btn bid sm" data-req-approve="${r.id}">Approve</button><button class="btn danger sm" data-req-reject="${r.id}">Decline</button><a class="btn ghost sm" href="#/admin/inbox/you">Message</a>` : ''}</span></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No requests match.</div>'}</div>`; }

  if (tab === 'orders') { DEF = { q: '', side: 'all', status: 'all', company: 'all', kind: 'all', rep: 'all', client: 'all', investor: 'all', value: 'all', from: '', to: '', sort: 'newest' }; const F = afState(tab, DEF);
    // One list for everything a client can enter: standard orders, custom orders and structured deals (options, forwards, SPVs, special terms, DP, liquid, own).
    const rows = D.orderRecords();   // one list for standard, custom and structured orders (data/api-exports.js)
    const shown = afSort(rows.filter(r => (F.status === 'all' || r.status === F.status) && (F.side === 'all' || r.side === F.side) && (F.company === 'all' || (r.c && r.c.id === F.company)) && (F.kind === 'all' || r.kind === F.kind) && (F.rep === 'all' || r.rep === F.rep) && (F.client === 'all' || r.cl.id === F.client) && D.investorMatches(r.cl.id, F.investor) && D.inValueBucket(r.total, F.value) && D.placedBetween(r.ts, F.from, F.to) && afHas(F.q, r.id, r.c ? r.c.name : '', r.cl.name, r.a ? r.a.what : '')), F.sort, { newest: r => -r.ts, oldest: r => r.ts, company: r => r.c ? r.c.name : 'zzz', client: r => r.cl.name, rep: r => D.rep(r.rep).name, value: r => -r.total, valueLow: r => r.total });
    actions = `<button class="btn sm" type="button" id="ord-new">${ICON.plus} Record order</button><button class="btn outline sm" type="button" data-export="orders-csv">Export CSV</button><button class="btn outline sm" type="button" data-export="orders-json">Export JSON</button>`;
    const cnt = k => rows.filter(r => r.status === k).length; stats = [['Live', cnt('live'), rows.filter(r => r.label === 'Partially filled').length + ' partially filled'], ['Filled', cnt('filled')], ['Cancelled', cnt('cancelled')], ['Matches', D.matches().length, pendM.length + ' awaiting approval']];
    const row = r => `<tr class="clickable ${r.status === 'filled' ? 'done' : ''} ${ordSel.has(r.id) ? 'selected' : ''}" data-href="${r.href}">${canRemove ? `<td class="sel">${r.status === 'live' ? `<input type="checkbox" data-ord-sel="${esc(r.id)}" ${ordSel.has(r.id) ? 'checked' : ''} aria-label="Select ${esc(r.id)}">` : ''}</td>` : ''}<td><span class="row" style="gap:6px"><span class="badge ${r.side === 'ask' ? 'listing' : 'bid'}">${r.side === 'ask' ? 'Ask' : 'Bid'}</span>${r.o ? customBadge(r.o) + fillBadge(r.o) : r.a ? `<span class="badge custom" title="Structured deal">${esc(D.ARRANGEMENT_TYPES[r.a.type])}</span>` : ''}<span class="oid">${esc(r.id)}</span></span></td><td>${r.c ? `<span class="row" style="gap:8px">${logo(r.c, 'sm')}<b>${esc(r.c.name)}</b></span>` : '<span class="dim">—</span>'}</td><td class="small"><a class="link" style="text-decoration:none" href="#/client/${r.cl.id}">${esc(r.cl.name)}</a></td><td class="small rep-cell">${repShort(r.rep)}</td><td class="num">${r.qty ? num(r.qty) : '—'}</td><td class="num px">${r.price ? money(r.price) : '—'}</td><td class="num px">${r.total ? money(r.total, 0) : '—'}</td><td class="small" style="white-space:nowrap">${fmtPlaced(r.ts)}</td><td><span class="badge ${r.status === 'live' ? 'open' : r.status === 'filled' ? 'verified' : 'status'}">${esc(r.label)}</span>${r.matches && r.matches.length ? `<div class="tiny muted">${r.matches.map(m => `<a class="link" href="#/match/${esc(m.id)}">${esc(m.id)}</a>`).join(', ')}</div>` : removedNote(r)}</td><td class="num">${r.status === 'live' ? `<span class="row" style="justify-content:flex-end;gap:6px">${canEdit ? `<button class="btn ghost sm" type="button" data-ord-edit="${esc(r.id)}" title="Change shares, price, validity or terms">Edit</button>` : ''}${canRemove ? `<button class="btn danger sm" type="button" data-ord-rm="${esc(r.id)}" title="Take this order off the book (kept as Cancelled)">Remove</button>` : ''}</span>` : ''}</td></tr>`;
    // Staff can edit (shares, price, validity, terms) or remove (with a reason) any live order; both audited (Ben, Sep 30 2026).
    const canEdit = D.can('orders.edit'), canRemove = D.can('orders.remove');
    const removedNote = r => r.status === 'cancelled' ? (r.o && r.o.cancelReason ? `<div class="tiny muted">${esc(r.o.cancelReason)}</div>` : r.a && r.a.staffNote ? `<div class="tiny muted">${esc(r.a.staffNote)}</div>` : '') : r.status === 'live' && ((r.o && r.o.edited) || (r.a && r.a.edited)) ? '<div class="tiny muted">Edited by Rainmaker</div>' : '';
    const recClients = clients.filter(k => k.status === 'verified' || k.you);
    const recForm = `<div class="${adminNewOrder ? '' : 'hidden'}" id="ord-new-wrap"><form class="card" id="ord-form" style="margin-bottom:18px"><div class="card-head"><span class="label">Record an order for a client</span><button class="btn ghost sm" type="button" id="ord-new-x">Close</button></div><div class="card-body stack" style="gap:10px">
      <div class="small muted">For orders taken by phone or email. Bids and asks go straight onto the book as live orders under the client's name; options, forwards and special-terms deals are recorded as live structured deals with the desk.</div>
      <div class="grid-3"><div class="field"><label>Client</label><select name="client">${recClients.map(k => `<option value="${k.id}">${esc(k.name)}${k.you ? ' (member session)' : ''}</option>`).join('')}</select></div><div class="field"><label>Order type</label><select name="kind">${Object.entries(D.RECORD_KINDS).map(([k, l]) => `<option value="${k}">${l}</option>`).join('')}</select></div><div class="field"><label>Company</label><select name="company">${D.COMPANIES.slice().sort((x, y) => x.name.localeCompare(y.name)).map(c => `<option value="${c.id}">${esc(c.name)} · ${esc(c.ticker)}</option>`).join('')}</select></div></div>
      <div class="grid-3"><div class="field ord-side hidden"><label>Side</label><select name="side"><option value="buy">Buy</option><option value="sell">Sell</option></select></div><div class="field"><label>Shares</label><input name="qty" type="number" min="1" step="1" placeholder="5,000"></div><div class="field"><label class="ord-price-lbl">Price per share ($)</label><input name="price" type="number" min="0" step="0.01" placeholder="42.00"></div></div>
      <div class="grid-3 ord-std"><div class="field"><label>Share class</label><select name="shareType"><option>Common</option><option>Preferred</option></select></div><div class="field"><label>Transfer type</label><select name="transferType"><option>Direct</option><option>SPV</option><option>Forward</option></select></div><div class="field"><label>Valid for (days)</label><input name="days" type="number" min="1" value="30"></div></div>
      <div class="grid-3 ord-std"><div class="field"><label>Order type</label><select name="fill">${Object.entries(D.FILL_RULES).map(([k, l]) => `<option value="${k}">${l}</option>`).join('')}</select></div><div class="field ord-min hidden"><label>Minimum shares per fill</label><input name="minFill" type="number" min="1" step="1" placeholder="1,000"></div></div>
      <div class="grid-3 ord-opt hidden"><div class="field"><label>Call / put</label><select name="optType"><option value="call">Call</option><option value="put">Put</option></select></div><div class="field"><label>Strike ($)</label><input name="strike" type="number" min="0" step="0.01" placeholder="50.00"></div><div class="field"><label>Term (months)</label><input name="months" type="number" min="1" value="12"></div></div>
      <div class="field ord-terms hidden"><label>Special terms</label><input name="terms" placeholder="e.g. collar 40–55, contingent on ROFR waiver, two tranches"></div>
      <div class="field"><label>Note (kept on the order)</label><input name="note" placeholder="Taken by phone at 10:40, client confirmed by email"></div></div>
      <div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Record as live</button><span class="small muted" style="margin-left:10px">Audited as ${esc(D.ROLES[role])}.</span></div></form></div>`;
    // Bulk actions (Ben, Oct 1 2026): tick rows (or every live order the filters show), then remove them all with one reason, confirmed inline.
    const liveShown = shown.filter(r => r.status === 'live'); const liveIds = liveShown.map(r => r.id); const allTicked = liveIds.length > 0 && liveIds.every(id => ordSel.has(id)); const selRows = rows.filter(r => ordSel.has(r.id) && r.status === 'live');
    const selBar = canRemove && ordSel.size ? `<div class="card ord-selbar" id="ord-selbar"><div class="between" style="flex-wrap:wrap;gap:8px"><span class="row" style="gap:10px"><b>${selRows.length} selected</b><span class="small muted">${[...new Set(selRows.map(r => r.cl.name))].slice(0, 3).map(esc).join(', ')}${new Set(selRows.map(r => r.cl.name)).size > 3 ? ' and others' : ''}</span></span><span class="row" style="gap:6px">${ordRmOpen ? '' : `<button class="btn danger sm" type="button" id="ord-rm-open">Remove selected</button>`}<button class="btn ghost sm" type="button" id="ord-sel-clear">Clear selection</button></span></div>
      ${ordRmOpen ? `<form class="ord-rm-confirm" id="ord-rm-form"><div class="small">Remove <b>${selRows.length}</b> live ${selRows.length === 1 ? 'order' : 'orders'} from the book? They stay listed as Cancelled with the reason, every one is audited as ${esc(D.ROLES[role])}, and members whose orders are affected are notified.</div><div class="row" style="gap:8px;flex-wrap:wrap;margin-top:8px"><input class="mini" name="why" style="flex:1;min-width:260px" value="Does not meet listing standards." placeholder="Reason (recorded in the activity log)"><button class="btn danger sm" type="submit">Remove ${selRows.length} ${selRows.length === 1 ? 'order' : 'orders'}</button><button class="btn ghost sm" type="button" id="ord-rm-cancel">Cancel</button></div></form>` : ''}</div>` : '';
    body = recForm + '<div id="ord-edit-wrap"></div>' + selBar + `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'ID, company or client', w: 170 }, { k: 'side', sel: [['all', 'Bids + asks'], ['bid', 'Bids'], ['ask', 'Asks']] }, { k: 'status', sel: [['all', 'All statuses'], ['live', 'Live'], ['filled', 'Filled'], ['cancelled', 'Cancelled']] }, { k: 'kind', sel: [['all', 'Standard + custom + structured'], ['standard', 'Standard'], ['custom', 'Custom'], ['structured', 'Structured deals']] }, { k: 'company', sel: coOpts() }, { k: 'client', sel: clientOpts(), title: 'Client' }, { k: 'investor', sel: Object.entries(D.INVESTOR_FILTERS), title: 'Investor class: qualified = verified accredited investor, QIB or institution' }, { k: 'value', sel: D.valueOpts(), title: 'Order value = shares × price' }, { k: 'rep', sel: repOpts() }, { k: 'from', date: 'Placed from', title: 'Entered on or after this date' }, { k: 'to', date: 'to', title: 'Entered on or before this date' }, { k: 'sort', sel: [['newest', 'Newest entered'], ['oldest', 'Oldest entered'], ['company', 'Company A–Z'], ['client', 'Client A–Z'], ['rep', 'By representative'], ['value', 'Largest value'], ['valueLow', 'Smallest value']] }])}<span class="small muted">${shown.length} of ${rows.length}</span></div>${shown.length ? `<table class="table compact ob"><thead><tr>${canRemove ? `<th class="sel"><input type="checkbox" id="ord-sel-all" ${allTicked ? 'checked' : ''} ${liveIds.length ? '' : 'disabled'} title="${liveIds.length ? `Select all ${liveIds.length} live orders shown` : 'No live orders in this view'}" aria-label="Select all live orders shown"></th>` : ''}<th>Order</th><th>Company</th><th>Client</th><th>Rep</th><th class="num">Shares</th><th class="num">Price / sh</th><th class="num">Total</th><th>Entered</th><th>Status</th>${canEdit || canRemove ? '<th></th>' : ''}</tr></thead><tbody>${shown.slice(0, 200).map(row).join('')}</tbody></table>` : '<div class="empty">No orders match these filters.</div>'}${shown.length > 200 ? '<div class="card-foot small muted">Showing the first 200. Narrow the filters to see the rest.</div>' : '<div class="card-foot small muted">Orders carry no settlement state. When a bid and an ask cross, both are lowered by the matched quantity and the match goes to <a class="link" href="#/admin/matches">Matches</a> for approval; signatures, fees, escrow and transfer are recorded there.</div>'}</div>`; }

  if (tab === 'companies') { DEF = { q: '', sort: 'name' }; const F = afState(tab, DEF); actions = `<button class="btn sm" type="button" id="co-new">${ICON.plus} New company</button>`;
    const list = afSort(D.COMPANIES.filter(c => afHas(F.q, c.name, c.ticker, c.sector)), F.sort, { name: c => c.name, newest: c => -(c.listedAt || 0), liquidity: c => -(D.liveListings(c.id).length + D.liveBids(c.id).length), price: c => -D.price(c.id) });
    stats = [['Listed', D.COMPANIES.length], ['Highly liquid', D.COMPANIES.filter(c => c.liquid).length], ['Added by staff', D.COMPANIES.filter(c => c.listedAt).length]];
    body = `<div class="${adminNewCo ? '' : 'hidden'}" id="co-new-wrap"><form class="card" id="co-form" style="margin-bottom:18px"><div class="card-head"><span class="label">New company</span><button class="btn ghost sm" type="button" id="co-new-x">Close</button></div><div class="card-body stack" style="gap:10px"><div class="grid-2"><div class="field"><label>Name</label><input name="name" required placeholder="Helios Energy"></div><div class="field"><label>Ticker</label><input name="ticker" required maxlength="4" placeholder="HLE"></div></div><div class="grid-2"><div class="field"><label>Sector</label><input name="sector" placeholder="Energy"></div><div class="field"><label>RX price at listing ($)</label><input name="base" type="number" step="0.01" min="0.01" required placeholder="24.00"></div></div><div class="field"><label>Description</label><textarea name="desc" style="height:70px" placeholder="What the company does"></textarea></div><div class="grid-2"><div class="field"><label>Industries (comma separated)</label><input name="industries" placeholder="Energy, Hardware"></div><div class="field"><label>Investors (comma separated)</label><input name="investors" placeholder="a16z, Khosla"></div></div><div class="grid-2"><div class="field"><label>Last round</label><input name="series" placeholder="Series C"></div><div class="field"><label>Post-money</label><input name="post" placeholder="$1.2b"></div></div><label class="check"><input type="checkbox" name="liquid"><span>Mark as highly liquid (RX50-style badge)</span></label></div><div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Add to exchange</button></div></form></div><div id="co-edit-wrap"></div>
      <div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Company, ticker or sector', w: 220 }, { k: 'sort', sel: [['name', 'Company A–Z'], ['newest', 'Newest listed'], ['liquidity', 'Most live orders'], ['price', 'Highest RX price']] }])}<span class="small muted">${list.length} of ${D.COMPANIES.length}</span></div><table class="table compact"><thead><tr><th>Company</th><th class="num">RX price</th><th class="num">Asks / bids</th><th>Policy</th><th>Listed</th><th></th></tr></thead><tbody>${list.map(c => `<tr><td><a class="link" style="text-decoration:none" href="#/company/${c.id}"><span class="row">${logo(c, 'sm')}<b>${esc(c.name)}</b>${c.liquid ? rx50() : ''}</span></a><div class="tiny muted">${esc(c.ticker)} · ${esc(c.sector)}</div></td><td class="num">${money(D.price(c.id))}</td><td class="num">${D.liveListings(c.id).length} / ${D.liveBids(c.id).length}</td><td class="small">${esc(c.policy.label)}<div class="tiny muted">fee ${money(c.policy.transferFee || 0, 0)} · ${c.policy.settleDays}d</div></td><td class="small">${c.listedAt ? fmtDateShort(c.listedAt) : '<span class="dim">Catalog</span>'}</td><td class="num"><span class="row" style="justify-content:flex-end;gap:6px"><button class="btn ghost sm" data-co-edit="${c.id}">Edit</button><button class="btn danger sm" data-co-remove="${c.id}">Remove</button></span></td></tr>`).join('')}</tbody></table></div>`; }

  if (tab === 'inbox') { DEF = { q: '', user: 'all', from: 'all', rep: 'all', sort: 'newest' }; const F = afState(tab, DEF); if (id && (id === 'you' || clients.find(c => c.id === id))) F.user = id;
    const WHO = { you: 'Client', rep: 'Representative', desk: 'Desk', compliance: 'Compliance', support: 'Rainmaker support', cp: 'Counterparty (brokered)' };
    const users = Array.from(new Map(allMsgs.map(m => [m.clientId, m.clientName])).entries()).sort((a, b) => a[1].localeCompare(b[1]));
    const shown = afSort(allMsgs.filter(m => (F.user === 'all' || m.clientId === F.user) && (F.from === 'all' || m.from === F.from) && (F.rep === 'all' || m.rep === F.rep) && afHas(F.q, m.text, m.clientName, m.companyId && D.company(m.companyId) ? D.company(m.companyId).name : '', m.orderId, m.attachments ? m.attachments.map(a => a.name).join(' ') : '')), F.sort, { newest: m => -m.ts, oldest: m => m.ts, user: m => m.clientName + m.ts, company: m => m.companyId && D.company(m.companyId) ? D.company(m.companyId).name : 'zzz' });
    actions = `<button class="btn outline sm" type="button" id="msg-csv" title="Download the messages shown as a CSV file">Download CSV</button>`;
    stats = [['Messages', allMsgs.length], ['Users', users.length], ['From clients, last 2 days', inbox.filter(m => Date.now() - m.ts < 2 * DAYMS).length], ['Attachments', allMsgs.filter(m => m.attachments && m.attachments.length).length]];
    main._msgCsv = shown;
    body = `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Keyword, user, company, order or file', w: 240 }, { k: 'user', sel: [['all', 'All users']].concat(users.map(([id_, n]) => [id_, n])) }, { k: 'from', sel: [['all', 'Everyone']].concat(Object.entries(WHO).map(([k, l]) => [k, l])) }, { k: 'rep', sel: repOpts() }, { k: 'sort', sel: [['newest', 'Newest first'], ['oldest', 'Oldest first'], ['user', 'User A–Z'], ['company', 'Company A–Z']] }])}<span class="muted small">${shown.length} of ${allMsgs.length} · replies go out as ${esc(D.rep(D.profile().rep).name)}</span></div><div class="card-body stack" style="gap:10px">${shown.length ? shown.slice(0, 60).map(m => { const c = m.companyId ? D.company(m.companyId) : null; return `<div class="inbox-item"><div class="small between" style="flex-wrap:wrap;gap:6px"><span><span class="badge ${m.from === 'you' ? 'bid' : m.from === 'support' ? 'custom' : 'status'}">${WHO[m.from] || esc(m.from)}</span> <a class="link" href="#/client/${m.clientId}"><b>${esc(m.clientName)}</b></a> · ${m.to === 'support' ? 'to Rainmaker Securities support' : c ? esc(c.name) : m.key === 'support' ? 'Rainmaker Securities support' : 'General'}${m.orderId ? ' · ' + esc(m.orderId) : ''} · rep ${repShort(m.rep)}</span><span class="muted">${fmtPlaced(m.ts)}</span></div><div class="small" style="margin:4px 0 8px">${esc(m.text)}</div>${m.attachments && m.attachments.length ? `<div class="attach-list msg-att">${attachChips(m.attachments)}</div>` : ''}${m.from === 'you' && m.clientId === 'you' ? `<form class="row" data-reply="${esc(m.key)}" data-company="${m.companyId || ''}" data-order="${m.orderId || ''}" data-support="${m.to === 'support' ? '1' : ''}"><input class="mini" name="text" placeholder="Reply…" style="flex:1" required><button class="btn sm dark" type="submit">Reply${m.to === 'support' ? ' as support' : ''}</button></form>` : m.sample && m.from === 'you' ? '<div class="tiny muted">Sample client · replies are not simulated in the prototype.</div>' : ''}</div>`; }).join('') : '<div class="muted small">No messages match.</div>'}${shown.length > 60 ? '<div class="small muted">Showing the first 60. Narrow the filters or download the CSV for the rest.</div>' : ''}</div></div>`; }

  if (tab === 'mailbox') { DEF = { q: '', folder: 'inbox', user: 'all', sort: 'newest' }; const F = afState(tab, DEF);
    // The firm's own mailbox: Inbox (members writing to Rainmaker Securities), Sent (what the firm sent), Compose (to any client).
    const inboxAll = D.firmInbox(), sentAll = D.firmSent(); const src = F.folder === 'sent' ? sentAll : inboxAll;
    const users = Array.from(new Map(inboxAll.concat(sentAll).map(m => [m.clientId, m.clientName])).entries()).sort((a, b) => a[1].localeCompare(b[1]));
    const shown = afSort(src.filter(m => (F.user === 'all' || m.clientId === F.user) && afHas(F.q, m.text, m.clientName, m.companyId && D.company(m.companyId) ? D.company(m.companyId).name : '')), F.sort, { newest: m => -m.ts, oldest: m => m.ts, user: m => m.clientName + m.ts, unread: m => (m.firmRead ? 1 : 0) * 1e15 - m.ts });
    actions = `<button class="btn sm" type="button" id="mb-new">${ICON.plus} New message</button><a class="btn outline sm" href="#/admin/inbox">Representatives' messages</a>`;
    stats = [['Inbox', inboxAll.length], ['Unread', D.firmUnread()], ['Sent', sentAll.length], ['Mailbox', esc(D.SUPPORT.email), esc(D.SUPPORT.phone + ' · ' + D.SUPPORT.hours)]];
    const coSel = (name, cur) => `<select name="${name}"><option value="">No company</option>${D.COMPANIES.slice().sort((x, y) => x.name.localeCompare(y.name)).map(c => `<option value="${c.id}"${cur === c.id ? ' selected' : ''}>${esc(c.name)}</option>`).join('')}</select>`;
    const compose = `<div class="${adminNewMail ? '' : 'hidden'}" id="mb-new-wrap"><form class="card" id="mb-form" style="margin-bottom:18px"><div class="card-head"><span class="label">New message from Rainmaker Securities</span><button class="btn ghost sm" type="button" id="mb-new-x">Close</button></div><div class="card-body stack" style="gap:10px">
      <div class="grid-2"><div class="field"><label>To</label><select name="client">${clients.map(k => `<option value="${k.id}">${esc(k.name)}${k.you ? ' (member session)' : ''}</option>`).join('')}</select></div><div class="field"><label>About (optional)</label>${coSel('company', '')}</div></div>
      <div class="field"><label>Message</label><textarea name="text" required style="height:90px" placeholder="Sent as Rainmaker Securities, not as a representative."></textarea></div></div>
      <div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Send from Rainmaker</button><span class="small muted" style="margin-left:10px">The member sees it in Messages under Rainmaker Securities support. Audited as ${esc(D.ROLES[role])}.</span></div></form></div>`;
    const item = m => { const c = m.companyId ? D.company(m.companyId) : null; const sent = F.folder === 'sent'; return `<div class="inbox-item ${!sent && !m.firmRead ? 'row-wait' : ''}"><div class="small between" style="flex-wrap:wrap;gap:6px"><span>${sent ? `<span class="badge custom">Rainmaker</span> to <a class="link" href="#/client/${esc(m.clientId)}"><b>${esc(m.clientName)}</b></a>` : `<span class="badge bid">Member</span> <a class="link" href="#/client/${esc(m.clientId)}"><b>${esc(m.clientName)}</b></a> to Rainmaker Securities`}${c ? ' · ' + esc(c.name) : ''}${!sent && !m.firmRead ? ' · <b>unread</b>' : ''}${sent && m.by ? ` · sent by ${esc(m.by.replace('staff:', ''))}` : ''}</span><span class="muted">${fmtPlaced(m.ts)}</span></div><div class="small" style="margin:4px 0 8px">${esc(m.text)}</div>${m.attachments && m.attachments.length ? `<div class="attach-list msg-att">${attachChips(m.attachments)}</div>` : ''}${sent ? '' : `<form class="row" data-mb-reply="${esc(m.id)}" data-client="${esc(m.clientId)}" data-company="${m.companyId || ''}"><input class="mini" name="text" placeholder="Reply as Rainmaker Securities…" style="flex:1" required><button class="btn sm dark" type="submit">Reply</button>${m.firmRead ? '' : `<button class="btn ghost sm" type="button" data-mb-read="${esc(m.id)}">Mark read</button>`}</form>`}</div>`; };
    body = compose + `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'folder', sel: [['inbox', 'Inbox'], ['sent', 'Sent']] }, { k: 'q', q: 'Keyword, member or company', w: 220 }, { k: 'user', sel: [['all', 'All members']].concat(users.map(([id_, n]) => [id_, n])) }, { k: 'sort', sel: [['newest', 'Newest first'], ['oldest', 'Oldest first'], ['unread', 'Unread first'], ['user', 'Member A–Z']] }])}<span class="muted small">${shown.length} of ${src.length}</span></div><div class="card-body stack" style="gap:10px">${shown.length ? shown.slice(0, 60).map(item).join('') : `<div class="muted small">${F.folder === 'sent' ? 'Nothing sent yet. Use New message.' : 'No messages to the firm match.'}</div>`}${shown.length > 60 ? '<div class="small muted">Showing the first 60. Narrow the filters for the rest.</div>' : ''}</div></div>`; }

  if (tab === 'clients') { DEF = { q: '', status: 'all', rep: 'all', type: 'all', sort: 'name' }; const F = afState(tab, DEF);
    const list = afSort(clients.filter(c => (F.status === 'all' || c.status === F.status) && (F.rep === 'all' || c.rep === F.rep) && (F.type === 'all' || c.type === F.type) && afHas(F.q, c.name, c.email, c.firm)), F.sort, { name: c => c.name, newest: c => -(c.submittedAt || 0), assets: c => -(c.aum || 0), rep: c => D.rep(c.rep).name });
    stats = [['Clients', clients.length], ['Verified', clients.filter(c => c.status === 'verified').length], ['Assets on platform', compact(clients.reduce((s_, c) => s_ + (c.aum || 0), 0))]];
    body = `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Name, email or firm' }, { k: 'status', sel: [['all', 'All statuses'], ['verified', 'Verified'], ['pending', 'Pending review'], ['unverified', 'Unverified']] }, { k: 'type', sel: [['all', 'All investor types']].concat(Object.entries(D.INVESTOR_TYPES).map(([k, l]) => [k, l.split(' (')[0]])) }, { k: 'rep', sel: repOpts() }, { k: 'sort', sel: [['name', 'Client A–Z'], ['newest', 'Newest joined'], ['assets', 'Largest assets'], ['rep', 'By representative']] }])}<span class="muted small">${list.length} of ${clients.length}</span></div>${list.length ? `<table class="table"><thead><tr><th>Client</th><th>Type</th><th>Status</th><th>Rep</th><th>Joined</th><th class="num">Assets</th><th class="num">Cash</th><th class="num">Live orders</th><th class="num">Requests</th></tr></thead><tbody>${list.map(c => `<tr class="clickable" data-href="#/client/${c.id}"><td><b>${esc(c.name)}</b>${c.you ? ' <span class="badge mine">You</span>' : ''}<div class="tiny muted">${esc(c.email)}</div></td><td class="small">${esc(D.INVESTOR_TYPES[c.type].split(' (')[0])}</td><td>${badge(c.status)}</td><td class="small rep-cell">${repShort(c.rep)}</td><td class="small">${c.submittedAt ? fmtDateShort(c.submittedAt) : '—'}</td><td class="num">${compact(c.aum || 0)}</td><td class="num">${compact(c.cash || 0)}</td><td class="num">${c.liveOrders}</td><td class="num">${c.requests}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">No clients match.</div>'}</div>`; }

  if (tab === 'matches') { DEF = { q: '', status: 'all', company: 'all', rep: 'all', sort: 'newest' }; const F = afState(tab, DEF);
    // Every match (clearance event): approve or decline pending ones here; open one for the settlement panel.
    const rows = D.matchRecords();
    const lab = r => r.label === 'Awaiting approval' ? 'pending' : r.label === 'Settling' ? 'settling' : r.label === 'Completed' ? 'completed' : 'declined';
    const shown = afSort(rows.filter(r => (F.status === 'all' || lab(r) === F.status) && (F.company === 'all' || r.c.id === F.company) && (F.rep === 'all' || r.rep === F.rep) && afHas(F.q, r.id, r.c.name, r.buyer.name, r.seller.name, r.m ? r.m.bidId : '', r.m ? r.m.askId : '')), F.sort, { newest: r => -r.ts, oldest: r => r.ts, company: r => r.c.name, value: r => -r.gross, status: r => ({ pending: 0, settling: 1, completed: 2, declined: 3 })[lab(r)] });
    actions = `<button class="btn outline sm" type="button" data-export="matches-csv">Export CSV</button><button class="btn outline sm" type="button" data-export="matches-json">Export JSON</button>`;
    const feesDue = rows.filter(r => r.settlement && r.label === 'Settling').reduce((s_, r) => s_ + (r.settlement.parties && r.settlement.parties.fees ? 0 : D.settlementFees(r.settlement).total), 0);
    const subs = D.spvSubs(); const subsDue = subs.filter(x => x.status === 'open' && x.stage === 2);
    stats = [['Awaiting approval', pendM.length, 'clearance events to review'], ['Settling', rows.filter(r => r.label === 'Settling').length], ['Completed', rows.filter(r => r.label === 'Completed').length], ['Declined', rows.filter(r => r.label === 'Declined').length], ['Broker fees outstanding', money(feesDue, 0), 'on matches settling'], ['SPV subscriptions', subs.filter(x => x.status === 'open').length, subsDue.length + ' awaiting units']];
    const subsCard = subs.length ? `<div class="card" style="margin-bottom:20px"><div class="card-head"><h3 style="margin:0;font-size:15px">SPV subscriptions</h3><span class="small muted">Members buying units from Rainmaker's inventory: once the agreement is signed and escrow funded, issue the units (or decline and return the escrow)</span></div><div class="card-body stack" style="gap:18px">${subs.map(x => spvSubBlock(x, { compact: true, link: true })).join('')}</div></div>` : '';
    body = subsCard + `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Match, order, company or party', w: 220 }, { k: 'status', sel: [['all', 'All statuses'], ['pending', 'Awaiting approval'], ['settling', 'Settling'], ['completed', 'Completed'], ['declined', 'Declined']] }, { k: 'company', sel: coOpts() }, { k: 'rep', sel: repOpts() }, { k: 'sort', sel: [['newest', 'Newest matched'], ['oldest', 'Oldest matched'], ['status', 'Awaiting first'], ['value', 'Largest value'], ['company', 'Company A–Z']] }])}<span class="small muted">${shown.length} of ${rows.length}</span></div>${matchesTable(shown.slice(0, 200), { staff: true, empty: 'No matches match these filters.' })}<div class="card-foot small muted">A match is created the moment a bid and an ask cross with both fill rules met; both orders are lowered at once. Approving it notifies the buyer and the seller that a party matched with them and opens the settlement (signatures, broker fee, escrow, transfer). Declining returns the quantity to both orders.</div></div>`; }

  if (tab === 'audit') { DEF = { q: '', kind: 'all', actor: 'all', when: 'all', sort: 'newest' }; const F = afState(tab, DEF);
    // Activity log: every audited event with filters by kind (prefix before the dot), actor, period and keyword.
    const log = D.auditLog(); const kindOf = a => (a.type || '').split('.')[0]; const KIND_LABEL = { order: 'Orders', match: 'Matches', settlement: 'Settlements', negotiation: 'Negotiations', request: 'Requests', arrangement: 'Structured deals', verification: 'Verifications', form: 'Compliance forms', staff: 'Staff sessions', access: 'Access denied', company: 'Companies', account: 'Accounts', mail: 'Rainmaker mailbox', messages: 'Messages', export: 'Exports', watchlist: 'Watchlist', alert: 'Alerts', join: 'Membership', profile: 'Profile' };
    const kinds = Array.from(new Set(log.map(kindOf))).sort(); const actors = Array.from(new Set(log.map(a => a.actor))).sort();
    const since = { today: Date.now() - DAYMS, week: Date.now() - 7 * DAYMS, month: Date.now() - 30 * DAYMS }[F.when] || 0;
    const shown = afSort(log.filter(a => (F.kind === 'all' || kindOf(a) === F.kind) && (F.actor === 'all' || a.actor === F.actor) && a.ts >= since && afHas(F.q, a.type, a.detail, a.actor, a.ip)), F.sort, { newest: a => -a.ts, oldest: a => a.ts, type: a => a.type + a.ts, actor: a => a.actor + a.ts });
    main._actCsv = shown; actions = `<button class="btn outline sm" type="button" id="act-csv">Download CSV</button>`;
    stats = [['Events', log.length], ['Today', log.filter(a => Date.now() - a.ts < DAYMS).length], ['Matches', log.filter(a => kindOf(a) === 'match').length], ['Staff actions', log.filter(a => String(a.actor).startsWith('staff:')).length], ['Access denied', log.filter(a => a.type === 'access.denied' || a.type === 'staff.denied').length]];
    body = `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Keyword, order, match or client', w: 220 }, { k: 'kind', sel: [['all', 'All kinds']].concat(kinds.map(k => [k, KIND_LABEL[k] || k])) }, { k: 'actor', sel: [['all', 'Everyone']].concat(actors.map(a => [a, a.replace('staff:', 'Staff · ')])) }, { k: 'when', sel: [['all', 'Any time'], ['today', 'Last 24 hours'], ['week', 'Last 7 days'], ['month', 'Last 30 days']] }, { k: 'sort', sel: [['newest', 'Newest first'], ['oldest', 'Oldest first'], ['type', 'By kind'], ['actor', 'By actor']] }])}<span class="small muted">${shown.length} of ${log.length}</span></div>${shown.length ? `<table class="table compact audit"><thead><tr><th>When</th><th>Kind</th><th>Event</th><th>Detail</th><th>Actor</th></tr></thead><tbody>${shown.slice(0, 300).map(a => `<tr><td class="tiny muted" style="white-space:nowrap">${fmtPlaced(a.ts)}</td><td class="small">${esc(KIND_LABEL[kindOf(a)] || kindOf(a))}</td><td><span class="badge status">${esc(a.type)}</span></td><td class="small">${esc(a.detail)}</td><td class="tiny muted" style="white-space:nowrap">${esc(a.actor)} · ${esc(a.ip)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">No activity matches these filters.</div>'}${shown.length > 300 ? '<div class="card-foot small muted">Showing the first 300. Narrow the filters or download the CSV for the rest.</div>' : ''}</div>`; }

  if (tab === 'forms') { DEF = { q: '', status: 'all', kind: 'all', sort: 'newest' }; const F = afState(tab, DEF); const forms = D.forms(); const wait = forms.filter(f => f.status === 'Awaiting review');
    const list = afSort(forms.filter(f => (F.status === 'all' || f.status === F.status) && (F.kind === 'all' || f.kind === F.kind) && afHas(F.q, f.id, f.detail, f.client ? f.client.name : '', D.FORM_KINDS[f.kind])), F.sort, { newest: f => -f.submitted, oldest: f => f.submitted, client: f => f.client ? f.client.name : 'zzz', kind: f => D.FORM_KINDS[f.kind], status: f => ({ 'Awaiting review': 0, Returned: 1, Approved: 2 })[f.status] });
    const fb = f => f.status === 'Approved' ? `<span class="badge verified">Approved</span><div class="tiny muted">${fmtDateShort(f.reviewedAt)}${f.by ? ' · ' + esc(f.by) : ''}</div>` : f.status === 'Returned' ? `<span class="badge custom">Returned</span><div class="tiny muted">${fmtDateShort(f.reviewedAt)}</div>` : '<span class="badge pending">Awaiting review</span>';
    stats = [['Awaiting review', wait.length], ['Approved', forms.filter(f => f.status === 'Approved').length], ['Returned', forms.filter(f => f.status === 'Returned').length]];
    actions = `<button class="btn outline sm" type="button" data-export="forms-csv">Export CSV</button><button class="btn outline sm" type="button" data-export="forms-json">Export JSON</button>`;
    body = `<div class="card"><div class="card-head af-head">${afBar(F, [{ k: 'q', q: 'Client, form or detail' }, { k: 'status', sel: [['all', 'All statuses'], ['Awaiting review', 'Awaiting review'], ['Approved', 'Approved'], ['Returned', 'Returned']] }, { k: 'kind', sel: [['all', 'All form types']].concat(Object.entries(D.FORM_KINDS)) }, { k: 'sort', sel: [['newest', 'Newest submitted'], ['oldest', 'Oldest submitted'], ['status', 'Awaiting first'], ['client', 'Client A–Z'], ['kind', 'Form type']] }])}<span class="small muted">${list.length} of ${forms.length}</span></div>${list.length ? `<table class="table compact"><thead><tr><th>Form</th><th>Client</th><th>Detail</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>${list.map(f => `<tr class="${f.status === 'Awaiting review' ? 'row-wait' : ''}"><td><b>${esc(D.FORM_KINDS[f.kind])}</b><div class="tiny muted">${esc(f.id.toUpperCase())}</div></td><td>${f.client ? `<a class="link" style="text-decoration:none" href="#/client/${f.client.id}">${esc(f.client.name)}</a>` : '—'}</td><td class="small">${esc(f.detail)}${f.note ? `<div class="tiny muted">Compliance: ${esc(f.note)}</div>` : ''}${f.href ? ` <a class="link tiny" href="${f.href}">Open</a>` : ''}</td><td class="small">${fmtPlaced(f.submitted)}</td><td>${fb(f)}</td><td class="num"><span class="row" style="justify-content:flex-end;gap:6px">${f.status === 'Awaiting review' ? `<button class="btn bid sm" data-form-approve="${f.id}">Approve</button><button class="btn danger sm" data-form-return="${f.id}">Return</button>` : `<button class="btn ghost sm" data-form-reopen="${f.id}">Reopen</button>`}</span></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No forms match.</div>'}</div>`; }

  const meta = ADMIN_META[tab] || ADMIN_META.overview;
  main.innerHTML = `<div class="page wide">${pageHead({ icon: meta.icon(), title: esc(meta.t), tag: `${esc(D.ROLES[role])} view`, tagClass: 'status', sub: meta.sub, actions, stats })}
    ${body}</div>`;
  document.title = `Rainmaker X · ${meta.t}`;
  main.querySelectorAll('[data-reply]').forEach(f => f.addEventListener('submit', e => { e.preventDefault(); const sup = f.dataset.support === '1'; D.sendMessage({ companyId: f.dataset.company || null, orderId: f.dataset.order || null, text: f.text.value.trim(), from: sup ? 'support' : 'rep', to: sup ? 'support' : undefined }); toast('Reply sent to client'); render(); }));
  if (DEF) wireAf(main, tab, DEF);
  wireExports(main);
  const acsv = main.querySelector('#act-csv'); if (acsv) acsv.onclick = () => { const cols = [['when', 'When'], ['type', 'Event'], ['detail', 'Detail'], ['actor', 'Actor'], ['ip', 'IP']]; const rows = (main._actCsv || []).map(a => ({ when: new Date(a.ts).toISOString(), type: a.type, detail: a.detail, actor: a.actor, ip: a.ip })); downloadFile(exportName('activity-log', 'csv'), D.toCSV(rows, cols), 'text/csv'); D.audit && D.audit('export.activity', rows.length + ' rows'); toast(`${rows.length} events downloaded`); };
  const csv = main.querySelector('#msg-csv'); if (csv) csv.onclick = () => { const cols = [['date', 'Date'], ['user', 'User'], ['from', 'From'], ['rep', 'Representative'], ['company', 'Company'], ['order', 'Order'], ['text', 'Message'], ['files', 'Attachments']]; const rows = (main._msgCsv || []).map(m => ({ date: new Date(m.ts).toISOString(), user: m.clientName, from: m.from, rep: D.rep(m.rep) ? D.rep(m.rep).name : '', company: m.companyId && D.company(m.companyId) ? D.company(m.companyId).name : '', order: m.orderId || '', text: m.text, files: (m.attachments || []).map(a => a.name).join('; ') })); downloadFile(exportName('messages', 'csv'), D.toCSV(rows, cols), 'text/csv'); D.audit && D.audit('messages.export', rows.length + ' rows'); toast(`${rows.length} messages downloaded`); };
  wireFeeForms(main);
  const on = main.querySelector('#ord-new'); if (on) { const wrap = main.querySelector('#ord-new-wrap'), f = main.querySelector('#ord-form');
    const showOrd = () => { wrap.classList.toggle('hidden', !adminNewOrder); if (adminNewOrder) { wrap.scrollIntoView({ behavior: 'smooth', block: 'start' }); f.qty.focus(); } };
    on.onclick = () => { adminNewOrder = !adminNewOrder; showOrd(); }; main.querySelector('#ord-new-x').onclick = () => { adminNewOrder = false; showOrd(); };
    const sync = () => { const k = f.kind.value; const std = k === 'bid' || k === 'ask'; f.querySelector('.ord-side').classList.toggle('hidden', std); f.querySelector('.ord-std').classList.toggle('hidden', !std); f.querySelector('.ord-opt').classList.toggle('hidden', k !== 'option'); f.querySelector('.ord-terms').classList.toggle('hidden', !['structured', 'forward', 'spv', 'dp', 'liquid'].includes(k)); f.querySelector('.ord-price-lbl').textContent = k === 'option' ? 'Premium per share ($, optional)' : k === 'forward' ? 'Forward price per share ($)' : k === 'liquid' ? 'Reference price ($)' : 'Price per share ($)'; if (k === 'forward') f.months.value = f.months.value || 6; };
    f.kind.addEventListener('change', sync); sync(); const syncMin = () => f.querySelector('.ord-min').classList.toggle('hidden', f.fill.value !== 'min'); f.fill.addEventListener('change', syncMin); syncMin();
    f.addEventListener('submit', e => { e.preventDefault(); const k = f.kind.value; const res = D.recordOrder({ clientId: f.client.value, kind: k, companyId: f.company.value, side: k === 'ask' ? 'sell' : k === 'bid' ? 'buy' : f.side.value, qty: f.qty.value, price: f.price.value, shareType: f.shareType.value, transferType: f.transferType.value, days: f.days.value, fill: f.fill.value, minFill: f.minFill.value, optType: f.optType.value, strike: f.strike.value, months: f.months.value, terms: f.terms.value.trim(), note: f.note.value.trim() });
      if (res.error) { toast(res.error, false); return; } adminNewOrder = false; toast(`${res.id} recorded as live`); if (k === 'bid' || k === 'ask') go(res.href); else render(); }); }
  // Orders tab bulk selection: tick rows, select every live order the filters show, remove the selection with one reason (inline confirmation, no browser dialog).
  if (tab === 'orders') {
    const redrawKeep = () => { const y = window.scrollY; viewAdmin(main, 'orders'); window.scrollTo(0, y); };
    main.querySelectorAll('[data-ord-sel]').forEach(cb => cb.onchange = () => { if (cb.checked) ordSel.add(cb.dataset.ordSel); else ordSel.delete(cb.dataset.ordSel); redrawKeep(); });
    const all = main.querySelector('#ord-sel-all'); if (all) all.onchange = () => { const ids = Array.from(main.querySelectorAll('[data-ord-sel]')).map(c => c.dataset.ordSel); const live = D.orderRecords().filter(r => r.status === 'live'); const F = afState('orders', DEF);
      // "Select all" means every live order the current filters match, not only the 200 rows on screen.
      const match = live.filter(r => (F.status === 'all' || r.status === F.status) && (F.side === 'all' || r.side === F.side) && (F.company === 'all' || (r.c && r.c.id === F.company)) && (F.kind === 'all' || r.kind === F.kind) && (F.rep === 'all' || r.rep === F.rep) && (F.client === 'all' || r.cl.id === F.client) && D.investorMatches(r.cl.id, F.investor) && D.inValueBucket(r.total, F.value) && D.placedBetween(r.ts, F.from, F.to) && afHas(F.q, r.id, r.c ? r.c.name : '', r.cl.name, r.a ? r.a.what : '')).map(r => r.id);
      (match.length ? match : ids).forEach(id => all.checked ? ordSel.add(id) : ordSel.delete(id)); redrawKeep(); };
    main.querySelectorAll('[data-ord-rm]').forEach(b => b.onclick = e => { e.stopPropagation(); ordSel = new Set([b.dataset.ordRm]); ordRmOpen = true; viewAdmin(main, 'orders'); const sb = main.querySelector('#ord-selbar'); if (sb) sb.scrollIntoView({ behavior: 'smooth', block: 'start' }); });
    const ro = main.querySelector('#ord-rm-open'); if (ro) ro.onclick = () => { ordRmOpen = true; redrawKeep(); const f = main.querySelector('#ord-rm-form'); if (f) f.why.select(); };
    const rc = main.querySelector('#ord-rm-cancel'); if (rc) rc.onclick = () => { ordRmOpen = false; redrawKeep(); };
    const sc = main.querySelector('#ord-sel-clear'); if (sc) sc.onclick = () => { ordSel = new Set(); ordRmOpen = false; redrawKeep(); };
    const rf = main.querySelector('#ord-rm-form'); if (rf) rf.addEventListener('submit', e => { e.preventDefault(); const why = rf.why.value.trim(); if (!why) { toast('Give a reason: it is recorded in the activity log.', false); rf.why.focus(); return; } const res = D.removeOrders([...ordSel], why); if (res.error) { toast(res.error, false); return; } ordSel = new Set(); ordRmOpen = false; toast(`${res.removed.length} ${res.removed.length === 1 ? 'order' : 'orders'} removed from the book${res.failed.length ? ` · ${res.failed.length} skipped (${res.failed[0].error})` : ''}`, !res.failed.length); render(); });
    // Drop ids that are no longer live (removed elsewhere, filled, expired).
    const liveNow = new Set(D.orderRecords().filter(r => r.status === 'live').map(r => r.id)); ordSel.forEach(id => { if (!liveNow.has(id)) ordSel.delete(id); });
  }
  main.querySelectorAll('[data-ord-edit]').forEach(b => b.onclick = () => {
    const r = D.orderRecords().find(x => x.id === b.dataset.ordEdit); if (!r) return; const w = main.querySelector('#ord-edit-wrap'); const o = r.o, a = r.a;
    const days = o ? Math.max(1, Math.ceil((o.expires - Date.now()) / DAYMS)) : 0;
    const sel = (name, opts, cur) => `<select name="${name}">${opts.map(v => `<option${v === cur ? ' selected' : ''}>${v}</option>`).join('')}</select>`;
    const priceLbl = a && a.type === 'option' ? 'Strike ($)' : a && a.type === 'forward' ? 'Forward price ($)' : 'Price per share ($)';
    w.innerHTML = `<form class="card" id="ord-edit" style="margin-bottom:18px"><div class="card-head"><span class="label">Edit ${esc(r.id)} · ${r.side === 'ask' ? 'ask' : 'bid'} · ${esc(r.c ? r.c.name : '')} · ${esc(r.cl.name)}</span><button class="btn ghost sm" type="button" id="ord-edit-x">Close</button></div><div class="card-body stack" style="gap:10px">
      <div class="grid-3"><div class="field"><label>Shares</label><input name="qty" type="number" min="${o ? 1 : 0}" step="1" value="${r.qty || ''}"></div><div class="field"><label>${priceLbl}</label><input name="price" type="number" min="0" step="0.01" value="${r.price || ''}"></div>${o ? `<div class="field"><label>Valid for (days from today)</label><input name="days" type="number" min="1" value="${days}"></div>` : '<div></div>'}</div>
      ${o ? `<div class="grid-3"><div class="field"><label>Share class</label>${sel('shareType', ['Common', 'Preferred'], o.shareType)}</div><div class="field"><label>Transfer type</label>${sel('transferType', ['Direct', 'SPV', 'Forward'], o.transferType)}</div></div><div class="grid-3"><div class="field"><label>Order type</label><select name="fill">${Object.entries(D.FILL_RULES).map(([k, l]) => `<option value="${k}"${D.fillRule(o).fill === k ? ' selected' : ''}>${l}</option>`).join('')}</select></div><div class="field ord-min ${D.fillRule(o).fill === 'min' ? '' : 'hidden'}"><label>Minimum shares per fill</label><input name="minFill" type="number" min="1" step="1" value="${D.fillRule(o).min || ''}"></div></div>` : `<div class="field"><label>Terms (as shown to the desk and the client)</label><textarea name="what" style="height:70px">${esc(a.what || '')}</textarea></div>`}
      <div class="field"><label>Note (kept on the order)</label><input name="note" value="${esc(o ? o.note || (o.recorded && o.recorded.note) || '' : a.note || '')}"></div>
      <div class="small muted">Client, company and side cannot be changed here: remove the order and record it again. Every change is audited as ${esc(D.ROLES[role])}${r.cl.id === 'you' ? ' and the client is notified' : ''}.</div></div>
      <div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Save changes</button><button class="btn danger" type="button" data-ord-rm="${esc(r.id)}" style="margin-left:8px">Remove from book</button></div></form>`;
    w.querySelector('[data-ord-rm]').onclick = () => { ordSel = new Set([r.id]); ordRmOpen = true; viewAdmin(main, 'orders'); };
    w.querySelector('#ord-edit-x').onclick = () => { w.innerHTML = ''; };
    w.querySelector('#ord-edit').addEventListener('submit', e => { e.preventDefault(); const f = e.target; const res = D.updateOrder(r.id, { qty: f.qty.value, price: f.price.value, days: f.days ? f.days.value : '', shareType: f.shareType ? f.shareType.value : '', transferType: f.transferType ? f.transferType.value : '', fill: f.fill ? f.fill.value : '', minFill: f.minFill ? f.minFill.value : '', what: f.what ? f.what.value : null, note: f.note.value.trim() }); if (res.error) { toast(res.error, false); return; } toast(`${r.id} updated: ${res.changes.join(', ')}`); viewAdmin(main, 'orders'); });
    const ef = w.querySelector('select[name=fill]'); if (ef) ef.onchange = () => w.querySelector('.ord-min').classList.toggle('hidden', ef.value !== 'min');
    w.scrollIntoView({ behavior: 'smooth', block: 'start' }); w.querySelector('input[name=qty]').focus(); });
  // Rainmaker mailbox: compose, reply, mark read.
  const mbn = main.querySelector('#mb-new'); if (mbn) { const w = main.querySelector('#mb-new-wrap'); const showMb = () => { w.classList.toggle('hidden', !adminNewMail); if (adminNewMail) { w.scrollIntoView({ behavior: 'smooth', block: 'start' }); w.querySelector('textarea').focus(); } };
    mbn.onclick = () => { adminNewMail = !adminNewMail; showMb(); }; main.querySelector('#mb-new-x').onclick = () => { adminNewMail = false; showMb(); };
    main.querySelector('#mb-form').addEventListener('submit', e => { e.preventDefault(); const f = e.target; const res = D.firmSend({ clientId: f.client.value, companyId: f.company.value || null, text: f.text.value }); if (res.error) { toast(res.error, false); return; } adminNewMail = false; afState('mailbox', {}).folder = 'sent'; toast('Sent from Rainmaker Securities'); viewAdmin(main, 'mailbox'); });
    main.querySelectorAll('[data-mb-reply]').forEach(f => f.addEventListener('submit', e => { e.preventDefault(); const res = D.firmSend({ clientId: f.dataset.client, companyId: f.dataset.company || null, text: f.text.value, replyTo: f.dataset.mbReply }); if (res.error) { toast(res.error, false); return; } toast('Reply sent from Rainmaker Securities'); viewAdmin(main, 'mailbox'); }));
    main.querySelectorAll('[data-mb-read]').forEach(b => b.onclick = () => { D.firmMarkRead(b.dataset.mbRead); viewAdmin(main, 'mailbox'); }); }
  const cn = main.querySelector('#co-new'); if (cn) cn.onclick = () => { adminNewCo = !adminNewCo; const w = main.querySelector('#co-new-wrap'); w.classList.toggle('hidden', !adminNewCo); if (adminNewCo) { w.scrollIntoView({ behavior: 'smooth', block: 'start' }); const n = w.querySelector('input[name=name]'); if (n) n.focus(); } };
  const cnx = main.querySelector('#co-new-x'); if (cnx) cnx.onclick = () => { adminNewCo = false; main.querySelector('#co-new-wrap').classList.add('hidden'); };
  const cf = main.querySelector('#co-form'); if (cf) cf.addEventListener('submit', e => { e.preventDefault(); const f = cf; const r = D.addCompany({ name: f.name.value.trim(), ticker: f.ticker.value.trim(), sector: f.sector.value.trim(), base: +f.base.value, desc: f.desc.value.trim(), industries: f.industries.value, investors: f.investors.value, series: f.series.value.trim(), post: f.post.value.trim(), liquid: f.liquid.checked }); if (r.error) { toast(r.error, false); return; } adminNewCo = false; toast(`${r.company.name} added to the exchange`); go('#/company/' + r.company.id); });
  main.querySelectorAll('[data-co-edit]').forEach(b => b.onclick = () => { const c = D.company(b.dataset.coEdit); const w = main.querySelector('#co-edit-wrap'); w.innerHTML = `<form class="card" id="co-edit" style="margin-bottom:18px"><div class="card-head"><span class="label">Edit ${esc(c.name)}</span><button class="btn ghost sm" type="button" id="co-edit-x">Close</button></div><div class="card-body stack" style="gap:10px"><div class="field"><label>Description</label><textarea name="desc" style="height:80px">${esc(c.desc)}</textarea></div><div class="grid-2"><div class="field"><label>Sector</label><input name="sector" value="${esc(c.sector)}"></div><div class="field"><label>Transfer notes shown to clients</label><input name="info" value="${esc(c.info || '')}"></div></div><div class="grid-2"><div class="field"><label>Company transfer fee ($)</label><input name="fee" type="number" step="100" value="${c.policy.transferFee || 0}"></div><div class="field"><label>Typical settlement (days)</label><input name="settle" type="number" min="1" value="${c.policy.settleDays}"></div></div><label class="check"><input type="checkbox" name="liquid" ${c.liquid ? 'checked' : ''}><span>Highly liquid badge</span></label></div><div class="card-foot form-foot" style="background:#fff"><button class="btn" type="submit">Save changes</button></div></form>`; w.querySelector('#co-edit-x').onclick = () => { w.innerHTML = ''; }; w.querySelector('#co-edit').addEventListener('submit', e => { e.preventDefault(); const f = e.target; D.updateCompany(c.id, { desc: f.desc.value.trim(), sector: f.sector.value.trim(), info: f.info.value.trim(), liquid: f.liquid.checked }, { transferFee: +f.fee.value || 0, settleDays: +f.settle.value || c.policy.settleDays }); toast('Company updated'); viewAdmin(main, 'companies'); }); w.scrollIntoView({ behavior: 'smooth', block: 'start' }); });
}
// Client page for staff: status, accounts, orders, requests, messages, notes.
function viewClient(main, id) {
  if (!D.isStaff()) return staffOnly(main);
  const c = D.client(id); if (!c) { main.innerHTML = '<div class="page"><div class="card empty">Client not found.</div></div>'; return; }
  const badge = s_ => s_ === 'verified' ? '<span class="badge verified">Verified</span>' : s_ === 'pending' ? '<span class="badge pending">Pending review</span>' : '<span class="badge status">Unverified</span>';
  const orders = c.you ? D.myOrders() : D.allOrders().filter(o => o.clientId === c.id).sort((x, y) => y.created - x.created); const reqs = c.you ? D.requests() : []; const msgs = c.you ? D.messages().slice(-6).reverse() : []; const stl = c.you ? D.settlements() : [];
  main.innerHTML = `<div class="page narrow">${pageHead({ icon: esc(c.name.split(' ').map(x => x[0]).join('').slice(0, 2)), iconClass: 'txt', crumb: '<a class="link" href="#/admin/clients">← Clients</a>', title: `${esc(c.name)} ${badge(c.status)}`, sub: `${esc(D.INVESTOR_TYPES[c.type] || c.type)} · rep ${esc(D.rep(c.rep).name)} · ${esc(c.email)}`, actions: `${c.status === 'pending' ? `<button class="btn bid sm" data-ver-approve="${c.id}">Approve verification</button><button class="btn danger sm" data-ver-reject="${c.id}">Send back</button>` : c.status === 'verified' ? `<button class="btn ghost sm" data-ver-reject="${c.id}">Revoke</button>` : ''}<a class="btn outline sm" href="#/admin/inbox/${c.id}">Messages</a>` })}
    <div class="kpis"><div class="kpi"><span class="label">Assets on platform</span><div class="v">${compact(c.aum || 0)}</div></div><div class="kpi"><span class="label">Cash</span><div class="v">${compact(c.cash || 0)}</div></div><div class="kpi"><span class="label">Live orders</span><div class="v">${c.liveOrders}</div></div><div class="kpi"><span class="label">Pending requests</span><div class="v">${c.requests}</div></div></div>
    <div class="two-col"><div class="stack">
      <div class="card"><div class="card-head"><span class="label">Verification file</span></div><table class="kv tight" style="padding:0 20px"><tr><th>Declared as</th><td>${esc(D.INVESTOR_TYPES[c.type] || c.type)}</td></tr><tr><th>Basis</th><td>${(c.basis || []).join(', ') || '—'}</td></tr><tr><th>Firm</th><td>${esc(c.firm || '—')}</td></tr><tr><th>Submitted</th><td>${c.submittedAt ? fmtPlaced(c.submittedAt) : '—'}</td></tr><tr><th>Documents</th><td class="small muted">Brokerage statement.pdf · CPA letter.pdf (placeholders)</td></tr>${c.note ? `<tr><th>Last note</th><td>${esc(c.note)}</td></tr>` : ''}</table></div>
      ${c.you || orders.length ? `<div class="card"><div class="card-head"><span class="label">Orders</span>${c.you ? '' : '<span class="small muted">Recorded by Rainmaker</span>'}</div>${orders.length ? `<table class="table compact">${orders.slice(0, 10).map(o => `<tr class="clickable" data-href="#/order/${o.id}"><td><span class="row" style="gap:6px">${sideBadge(o)}<span class="oid">${esc(o.id)}</span></span></td><td>${esc(D.company(o.companyId).name)}</td><td class="num">${num(o.qty)} @ ${money(o.price)}</td><td><span class="badge status">${esc(o.status)}</span></td></tr>`).join('')}</table>` : '<div class="card-body small muted">No orders.</div>'}</div>
      <div class="card"><div class="card-head"><span class="label">Requests</span></div>${reqs.length ? `<table class="table compact">${reqs.map(r => `<tr><td><span class="oid">${esc(r.id)}</span></td><td>${esc(r.what)}</td><td><span class="badge status">${esc(r.status)}</span></td><td class="num">${r.status === 'pending' ? `<button class="btn bid sm" data-req-approve="${r.id}">Approve</button> <button class="btn danger sm" data-req-reject="${r.id}">Decline</button>` : ''}</td></tr>`).join('')}</table>` : '<div class="card-body small muted">No requests.</div>'}</div>` : '<div class="card card-body small muted">Order, request and message history for sample clients is not generated in this prototype. Your own profile shows the full picture.</div>'}
    </div><div class="stack">
      ${c.you ? `<div class="card"><div class="card-head"><span class="label">Recent messages</span></div><div class="msg-list compact" style="padding:14px 20px">${msgs.length ? msgs.map(bubble).join('') : '<div class="small muted">None.</div>'}</div></div>
      <div class="card"><div class="card-head"><span class="label">Settlements</span></div><div class="card-body stack scroll-y">${stl.length ? stl.map(x => `<div><div class="small" style="margin-bottom:6px"><b>${esc(D.company(x.companyId).name)}</b> · ${x.side === 'buy' ? 'buying' : 'selling'} ${num(x.qty)} @ ${money(x.price)}</div>${trackerBlock(x, { compact: true })}</div>`).join('') : '<div class="small muted">None.</div>'}</div></div>` : ''}
      ${(() => { const rr = D.repRequestFor(c.id); const canAdmin = D.can('users'); const canDecide = D.role() === 'rep' || canAdmin; return `<div class="card"><div class="card-head"><span class="label">Primary representative</span>${rr ? '<span class="badge pending">Change requested</span>' : ''}</div><div class="card-body stack" style="gap:10px"><div class="small"><b>${esc(D.rep(c.rep).name)}</b> · ${esc(D.rep(c.rep).title)}</div>${rr ? `<div class="callout"><b>${esc(D.rep(rr.to).name)}</b> has been asked to become the primary representative (${esc(rr.by.replace('staff:', 'by '))}, ${fmtPlaced(rr.ts)}).${rr.note ? ' ' + esc(rr.note) : ''}${canDecide ? ` <span class="row" style="gap:6px;margin-top:8px"><button class="btn bid sm" type="button" data-rr-approve="${esc(rr.id)}">Accept as primary</button><button class="btn danger sm" type="button" data-rr-deny="${esc(rr.id)}">Deny</button></span>` : ' Waiting for the representative to accept or deny.'}</div>` : ''}${canAdmin ? `<form class="row" id="rep-change" style="gap:6px"><select name="rep" class="mini" style="flex:1">${D.REPS.filter(r => r.id !== c.rep).map(r => `<option value="${r.id}">${esc(r.name)} · ${esc(r.title)}</option>`).join('')}</select><button class="btn outline sm" type="submit">${rr ? 'Propose a different rep' : 'Change primary rep'}</button></form><div class="tiny muted">The representative must accept before the change takes effect; the client is told either way.</div>` : '<div class="tiny muted">Only an administrator can propose a change; the representative accepts or denies it.</div>'}</div></div>`; })()}
      <div class="card card-body small"><span class="label dim">Compliance notes</span><form id="cl-note" class="row" style="margin-top:8px"><input class="mini" name="text" placeholder="Add a note to the file…" style="flex:1"><button class="btn sm dark" type="submit">Save</button></form><div class="stack" style="gap:6px;margin-top:10px">${((D.state.clientNotes || {})[c.id] || []).map(n => `<div class="note-card small">${esc(n.text)}<div class="ts">${fmtPlaced(n.ts)} · ${esc(n.by)}</div></div>`).join('')}</div></div>
    </div></div></div>`;
  main.querySelector('#cl-note').addEventListener('submit', e => { e.preventDefault(); const f = e.target; const t = f.text.value.trim(); if (!t) return; D.state.clientNotes = D.state.clientNotes || {}; (D.state.clientNotes[c.id] = D.state.clientNotes[c.id] || []).unshift({ ts: Date.now(), text: t, by: D.ROLES[D.role()] }); D.save(); toast('Note saved'); render(); });
  const rcf = main.querySelector('#rep-change'); if (rcf) rcf.addEventListener('submit', e => { e.preventDefault(); const r = D.requestPrimaryRep(c.id, rcf.rep.value); if (r.error) { toast(r.error, false); return; } toast(`${D.rep(rcf.rep.value).name} asked to become ${c.name}'s primary representative`); render(); });
}

// ---------------- structured arrangements: options, forwards, SPVs, special-terms bids/asks ----------------
