/* ==============================================================
   Rainmaker X · app · orders
   Order detail, settlement page, new bid / ask form, custom order builder, My Orders,
   and structured arrangements (options, forwards, SPVs, special terms, own contract).
   ============================================================== */
'use strict';

// Settlement page for a settlement with no order behind it.
function viewSettlement(main, st) { viewMatch(main, st.id); }   // legacy settlements (seeded holdings, desk trades) open as a match record
// Order detail: terms, bids on it, negotiation, settlement panel, closing record.
function viewOrder(main, id) {
  const o = D.order(id); if (!o) { const st = D.settlement(id); if (st) return viewSettlement(main, st); main.innerHTML = '<div class="page"><div class="card empty">Order not found.</div></div>'; return; }
  const c = D.company(o.companyId); const isL = o.side === 'listing'; const done = o.status === 'sold' || o.status === 'completed' || o.status === 'cancelled';
  const bids = isL ? D.listingBids(o.id) : [];
  const details = `<div class="card">
      <div class="order-hero"><div class="oh-head"><h1>${sideBadge(o)}${customBadge(o)}${fillBadge(o)}<span class="oid" style="font-size:20px">${esc(o.id)}</span></h1><a class="company-chip" href="#/company/${c.id}">${logo(c, 'sm')}${esc(c.name)}</a></div>
        <div class="qp-box"><div class="cell"><span class="label">Shares</span><div class="v">${num(o.qty)}</div></div><div class="at">@ ${money(o.price)}</div><div class="cell"><span class="label">Total</span><div class="v">${money(o.price * o.qty, 0)}</div></div></div>
        <div class="note">Share count is rounded from the actual number of shares${o.custom && o.custom.pricing === 'pegged' ? ' · price re-pegs to the RX price' : ''}</div></div>
      <div class="card-body stack">
        <div class="expires"><span class="label">${done && o.status !== 'cancelled' ? 'Entered' : 'Expires'}</span><span>${done && o.status !== 'cancelled' ? fmtPlaced(o.created) : o.custom && o.custom.gtc ? 'Good till cancelled' : `${fmtPlaced(o.expires)} · ${daysLeft(o)} days`}</span>${o.mine ? '<span class="badge mine" style="margin-left:auto">Your order</span>' : ''}${done ? `<span class="badge status" style="margin-left:${o.mine ? '6px' : 'auto'}">${o.status === 'cancelled' ? 'Cancelled' : 'Filled'}</span>` : ''}${o.soldQty ? `<span class="pill" style="margin-left:6px"><b>${num(o.soldQty)}</b> of ${num(o.origQty || o.qty + o.soldQty)} matched</span>` : ''}</div>
        <div class="type-cards"><div class="type-card"><span class="label">Share type</span><span>${esc(o.shareType)}</span></div><div class="type-card"><span class="label">Transfer type</span><span>${esc(o.transferType)}</span></div><div class="type-card"><span class="label">Fill rule</span><span>${esc(D.fillLabel(o))}</span></div></div>
        ${customTermsBlock(o)}
        <div><div class="label" style="margin-bottom:8px">Activity</div><div class="row" style="flex-wrap:wrap">${isL ? `<span class="pill"><b>${o.bidsCount || 0}</b> ${o.bidsCount === 1 ? 'bid' : 'bids'}</span>` : `<span class="pill">Placed <b>${fmtDateShort(o.created)}</b></span>`}<span class="pill">Settles in ~<b>${c.policy.settleDays}</b> days</span>${o.recorded ? `<span class="pill" title="${esc(o.recorded.note || '')}">Recorded by Rainmaker <b>${fmtDateShort(o.recorded.ts)}</b></span>` : ''}${D.isStaff() ? (() => { const cl = D.orderClient(o); const rp = D.rep(D.assignedRep(o)); return `<span class="pill">Client <a class="link" href="#/client/${cl.id}"><b>${esc(cl.name)}</b></a></span><span class="pill">Rep <b>${esc(rp.name)}</b></span>`; })() : ''}</div></div>
        ${o.disclosures ? `<div class="tiny muted">Disclosures v${esc(o.disclosures.version)} accepted ${fmtPlaced(o.disclosures.acceptedAt)} · recorded with this order</div>` : ''}${D.flagged(o.id) && D.isStaff() ? `<div class="callout coral">Flagged by ${esc(D.flagged(o.id).by)} on ${fmtDate(D.flagged(o.id).ts)}.</div>` : ''}
        ${(() => { const ms = D.matchRecords().filter(r => r.m && (r.m.bidId === o.id || r.m.askId === o.id || bids.some(b => b.id === r.m.bidId))).filter(r => D.isStaff() || r.mine); return ms.length ? `<div><div class="label" style="margin-bottom:8px">Matches on this order</div>${matchesTable(ms)}<div class="tiny muted" style="margin-top:6px">Open a match to follow Rainmaker's approval and the settlement steps. Orders themselves carry no settlement state.</div></div>` : ''; })()}
        ${bids.length ? `<div><div class="label" style="margin-bottom:8px">Your bids on this ask</div><table class="table compact"><thead><tr><th>Bid</th><th class="num">Shares</th><th class="num">Price</th><th>Status</th><th></th></tr></thead><tbody>${bids.map(b => `<tr><td><span class="oid">${esc(b.id)}</span></td><td class="num">${num(b.qty)}</td><td class="num">${money(b.price)}</td><td><span class="badge status">${esc(b.status)}</span></td><td class="num">${b.status === 'live' ? `<button class="btn danger sm" data-cancel="${b.id}">Cancel</button>` : ''}</td></tr>`).join('')}</tbody></table></div>` : ''}
      </div>
      ${o.mine && o.status === 'live' ? `<div class="card-foot between" style="flex-wrap:wrap"><span>This is your ${isL ? 'ask' : 'bid'}. Cancelling removes it from the market immediately.</span><span class="row"><button class="btn outline sm" data-reconfirm="${o.id}">Reconfirm 30 days</button><button class="btn danger sm" data-cancel="${o.id}">Cancel ${isL ? 'ask' : 'bid'}</button></span></div>` : ''}
    </div>`;
  const action = o.mine ? `<div class="card card-body"><div class="callout">You cannot ${isL ? 'bid on' : 'sell into'} your own order. Share this ${isL ? 'ask' : 'bid'} ID with a counterparty: <b class="oid">${esc(o.id)}</b></div></div>`
      : done ? `<div class="card card-body"><div class="callout">This ${isL ? 'ask' : 'bid'} is no longer open. <a class="link" href="#/company/${c.id}">See other ${esc(c.name)} orders.</a></div></div>`
      : isL ? `<form class="card" id="bid-form"><div class="card-head"><h2 style="font-size:18px">Match</h2><span class="small muted">Seller wants ${money(o.price)}</span></div><div class="card-body stack">${D.canTrade() ? '' : gateCard('this bid')}
          <p style="margin:0;color:var(--ink-2)">Make an offer at, below, or above the seller's price. At or above matches immediately.</p>
          <div class="grid-2"><div class="field"><label>Number of shares</label><input name="qty" type="number" min="1" step="1" value="${o.qty}" required></div><div class="field"><label>Price per share</label><input name="price" type="number" min="0.01" step="0.01" value="${o.price}" required></div></div>
          <div class="field"><label>Bid valid for (days)</label><input name="days" type="number" min="1" max="90" value="7" required></div>
          <div class="gross"><div><div class="label">Gross value of your bid</div><div class="small strong" id="gross-l">—</div></div><div class="amt" id="gross-v">—</div></div>
          <div id="fee-box"></div>
          <div class="callout" id="cross-note"></div>
          ${disclosureBlock()}
          <label class="check"><input type="checkbox" name="ack" required><span>I understand that by placing this bid I am communicating a serious intention to complete an investment on these terms.</span></label>
        </div><div class="card-foot form-foot" style="background:#fff"><a class="link small" href="#/new/custom/${c.id}">Need a ladder or fill rules? Build a custom bid</a><button class="btn bid" type="submit">${ICON.cart} <span class="bl">${D.canTrade() ? 'Place bid' : 'Submit request'}</span></button></div></form>`
      : `<form class="card" id="sell-form"><div class="card-head"><h2 style="font-size:18px">Match</h2><span class="small muted">Buyer offers ${money(o.price)}</span></div><div class="card-body stack">${D.canTrade() ? '' : gateCard('this sale')}
          <p style="margin:0;color:var(--ink-2)">Accept the buyer's bid at their price, or counter at a higher price per share.</p>
          <div class="grid-2"><div class="field"><label>Number of shares</label><input name="qty" type="number" min="1" step="1" value="${o.qty}" required></div><div class="field"><label>Price per share</label><input name="price" type="number" min="0.01" step="0.01" value="${o.price}" required></div></div>
          <div class="gross"><div><div class="label">Gross value of your sale</div><div class="small strong" id="gross-l">—</div></div><div class="amt" id="gross-v">—</div></div>
          <div id="fee-box"></div>
          <div class="callout" id="cross-note"></div>
          ${disclosureBlock()}
          <label class="check"><input type="checkbox" name="ack" required><span>I confirm I have the ability to sell these shares and intend to complete a transaction on these terms.</span></label>
        </div><div class="card-foot form-foot" style="background:#fff"><a class="link small" href="#/new/custom/${c.id}/ask">Build a custom ask instead</a><button class="btn ask" type="submit">${ICON.cash} <span class="bl">Accept bid</span></button></div></form>`;
  const negOpen = D.negotiation(o.id).length && !D.negotiation(o.id).some(e => e.type === 'agreed' || e.type === 'decline');
  main.innerHTML = `<div class="page narrow"><div class="two-col" style="grid-template-columns:minmax(0,1fr) minmax(0,1.15fr)">
    <div class="stack">${negotiationCard(o)}${negOpen ? '' : action}${askRainmakerCard(c, o)}</div>
    <div class="stack">${details}<div class="card"><div class="card-head"><span class="label">${esc(c.name)} at a glance</span>${watchBtn(c, true)}</div><div class="card-body stack">${pricingStrip(c)}<div class="between">${activityPills(c)}<a class="link small" href="#/company/${c.id}">Full order book →</a></div></div></div></div>
  </div></div>`;
  const form = main.querySelector('#bid-form, #sell-form');
  if (form) {
    const upd = () => { const q = +form.qty.value || 0, p = +form.price.value || 0; form.querySelector('#gross-l').textContent = `${num(q)} shares @ ${money(p)}`; form.querySelector('#gross-v').textContent = money(q * p); form.querySelector('#fee-box').innerHTML = feeBlock(c.id, q * p, isL ? 'buy' : 'sell'); const n = form.querySelector('#cross-note');
      const fillNo = !D.fillOk(o, Math.min(q, o.qty)); const fillMsg = `<b>Price meets the ${isL ? 'ask' : 'bid'}, but its fill rule does not.</b> This ${isL ? 'ask' : 'bid'} is ${D.fillLabel(o).toLowerCase()}${D.fillRule(o).fill === 'aon' ? `: ${isL ? 'bid for' : 'sell'} all ${num(o.qty)} shares to match` : `: ${isL ? 'bid for' : 'sell'} at least ${num(Math.min(D.fillRule(o).min, o.qty))} shares to match`}. Otherwise it goes to your primary representative as a negotiation.`;
      if (isL) { n.className = 'callout ' + (p >= o.price && !fillNo ? 'green' : ''); n.innerHTML = p >= o.price && fillNo ? fillMsg : p >= o.price ? `<b>Matches now.</b> At or above the ask: ${num(Math.min(q, o.qty))} shares fill immediately at ${money(o.price)}/sh${q > o.qty ? ` (the ask only has ${num(o.qty)})` : ''}.` : `<b>Opens a negotiation.</b> ${pct((p - o.price) / o.price)} vs the seller's ask of ${money(o.price)}. ${esc(D.rep(D.profile().rep).name.split(' ')[0])} relays it; the seller can accept, counter or decline, and you respond on this page.`; }
      else { n.className = 'callout ' + (p <= o.price && !fillNo ? 'green' : ''); n.innerHTML = p <= o.price && fillNo ? fillMsg : p <= o.price ? `<b>Matches now.</b> At or below the bid: ${num(Math.min(q, o.qty))} shares fill immediately at ${money(o.price)}/sh.` : `<b>Opens a negotiation.</b> ${pct((p - o.price) / o.price)} above the buyer's bid. Sent as a counter-offer through your primary representative.`; }
      const sub = form.querySelector('[type=submit] .bl') || form.querySelector('[type=submit]'); if (!D.canTrade()) sub.textContent = 'Submit request'; else if (!isL) sub.textContent = p <= o.price ? 'Accept bid' : 'Send counter-offer'; };
    form.addEventListener('input', upd); upd();
    form.addEventListener('submit', e => { e.preventDefault(); const q = +form.qty.value, p = +form.price.value; if (!(q > 0 && p > 0)) return;
      if (!D.canTrade()) { const rq = D.submitRequest({ kind: isL ? 'bid-on-ask' : 'sell-into-bid', companyId: c.id, orderId: o.id, price: p, qty: q, days: isL ? +form.days.value : 7 }); toast(`Request ${rq.id} sent to your primary representative`); go('#/orders/requests'); return; }
      if (isL) { const r = D.bidOnListing(o.id, p, q, +form.days.value); toast(r.match ? `Matched ${num(r.match.qty)} shares @ ${money(r.match.price)}` : `Bid ${r.bid.id} placed on ${o.id}`); go('#/order/' + o.id); render(); }
      else { const r = D.sellIntoBid(o.id, p, q); toast(r.match ? `Sold ${num(r.match.qty)} shares @ ${money(r.match.price)}` : 'Counter-offer sent'); render(); } });
  }
  wireAskRainmaker(main, c, o); wireNegotiation(main, o); wireFeeForms(main);
}

// Standard bid / ask form.
function viewNewOrder(main, side, companyId) {
  const isL = side === 'listing';
  const opts = D.COMPANIES.slice().sort((a, b) => a.name.localeCompare(b.name));
  const c0 = D.company(companyId) || null;
  main.innerHTML = `<div class="page narrow">
    ${pageHead({ icon: PH.order, title: isL ? 'New ask' : 'New bid', tag: isL ? 'Ask' : 'Bid', tagClass: isL ? 'ask' : 'bid', sub: isL ? 'Post an ask for shares you have the ability to sell. A bid at or above your price matches immediately.' : 'Post a bid that any seller can accept. A bid at or above the lowest ask matches immediately.', actions: `<a class="btn outline custom sm" href="#/new/custom${c0 ? '/' + c0.id : ''}${isL ? (c0 ? '/ask' : '') : ''}">${ICON.sliders} Need more control? Build a custom ${isL ? 'ask' : 'bid'}</a>` })}
    <div class="two-col" style="grid-template-columns: 3fr 2fr">
    <form class="card" id="new-form"><div class="card-body stack">${D.canTrade() ? '' : gateCard(isL ? 'this ask' : 'this bid')}
      ${companyPicker('cpick', c0 ? c0.id : '')}
      <div id="ctx"></div>
      <div class="grid-2"><div class="field"><label>Number of shares</label><input name="qty" type="number" min="1" step="1" placeholder="e.g. 2,500" required></div><div class="field"><label>Price per share</label><input name="price" type="number" min="0.01" step="0.01" placeholder="$" required></div></div>
      <div class="grid-2"><div class="field"><label>Share type</label><select name="shareType"><option>Common</option><option>Preferred</option></select></div><div class="field"><label>Transfer type</label><select name="transferType"><option>Direct</option><option>SPV</option><option>Forward</option></select><span class="hint">Direct transfers may be subject to company approval and transfer fees.</span></div></div>
      <div class="grid-2"><div class="field"><label>Order type</label><select name="fill"><option value="partial">Partial fills accepted</option><option value="aon">All-or-none (entire quantity only)</option><option value="min">Minimum fill (at least N shares at a time)</option></select><span class="hint" id="fill-hint">Any amount can match; the rest stays live on the book.</span></div><div class="field fill-min hidden"><label>Minimum shares per fill</label><input name="minFill" type="number" min="1" step="1" placeholder="e.g. 1,000"></div></div>
      <div class="field"><label>${isL ? 'Ask' : 'Bid'} valid for (days)</label><input name="days" type="number" min="1" max="180" value="30" required><span class="hint">Orders expire after 30 days by default so the book stays fresh. Reconfirm from the order page to extend.</span></div>
      <div class="gross"><div><div class="label">Gross value of your ${isL ? 'ask' : 'bid'}</div><div class="small strong" id="gross-l">—</div></div><div class="amt" id="gross-v">—</div></div>
      <div id="fee-box"></div>
      <div class="callout" id="cross-note">Select a company to see the current market.</div>
      ${disclosureBlock()}
      <label class="check"><input type="checkbox" name="ack" required><span>${isL ? 'I confirm I have the ability to sell these shares and understand that by posting this ask I am communicating a serious intention to transact on these terms.' : 'I understand that by placing this bid I am communicating a serious intention to complete an investment on these terms.'}</span></label>
    </div><div class="card-foot form-foot" style="background:#fff"><a class="btn ghost" href="${c0 ? '#/company/' + c0.id : '#/dashboard'}">Cancel</a><button class="btn ${isL ? 'ask' : 'bid'}" type="submit">${isL ? ICON.cash : ICON.cart} <span class="bl">${D.canTrade() ? (isL ? 'Place ask' : 'Place bid') : 'Submit request'}</span></button></div></form>
    <div class="stack" id="side-panel"></div></div></div>`;
  const form = main.querySelector('#new-form'); const side_ = main.querySelector('#side-panel'); const ctx = main.querySelector('#ctx');
  const drawCtx = () => { const c = D.company(form.company.value); if (!c) { ctx.innerHTML = ''; side_.innerHTML = '<div class="card empty">Pick a company to see its current pricing and live orders.</div>'; return; }
    ctx.innerHTML = pricingStrip(c);
    const list = isL ? D.liveBids(c.id) : D.liveListings(c.id);  // every live order; the list scrolls inside the card
    side_.innerHTML = `<div class="card"><div class="card-head"><div class="row">${logo(c)}<b>${esc(c.name)}</b></div><a class="link small" href="#/company/${c.id}">Company page</a></div><div class="card-body" style="padding:0 0 4px"><div class="label" style="padding:12px 20px 4px">${isL ? 'Highest bids' : 'Lowest asks'} right now</div>${list.length ? `<div class="scroll-y"><table class="table compact"><tbody>${list.map(o => `<tr class="clickable" data-href="#/order/${o.id}"><td><span class="oid">${esc(o.id)}</span>${o.custom ? ' ' + customBadge(o) : ''}</td><td class="num">${num(o.qty)}</td><td class="num strong">${money(o.price)}</td><td class="dim small">${esc(o.shareType)} · ${esc(o.transferType)}</td></tr>`).join('')}</tbody></table></div>` : `<div class="muted" style="padding:8px 20px 16px">No live ${isL ? 'bids' : 'asks'} for ${esc(c.name)} yet.</div>`}</div></div>`;
    if (!form.price.value) form.price.value = D.price(c.id).toFixed(2); upd(); };
  const upd = () => { const c = D.company(form.company.value); const q = +form.qty.value || 0, p = +form.price.value || 0; form.querySelector('#gross-l').textContent = `${num(q)} shares @ ${money(p)}`; form.querySelector('#gross-v').textContent = money(q * p); form.querySelector('#fee-box').innerHTML = c ? feeBlock(c.id, q * p, isL ? 'sell' : 'buy') : ''; const n = form.querySelector('#cross-note'); if (!c || !p) { n.className = 'callout'; n.textContent = 'Select a company to see the current market.'; return; }
    n.className = 'stack'; n.style.gap = '8px'; n.innerHTML = matchPreview(c, isL ? 'listing' : 'bid', p, q, form.fill.value, +form.minFill.value || 0);
    if (!isL) { const bp = D.buyingPower(); if (q * p > bp) n.innerHTML += `<div class="callout coral"><b>Heads up:</b> this bid (${money(q * p, 0)}) exceeds your buying power of ${money(bp, 0)}. <a class="link" href="#/account">Deposit funds</a> so it can settle.</div>`; } };
  wireCompanyPicker(form, 'cpick', () => { form.price.value = ''; drawCtx(); });
  const FILL_HINT = { partial: 'Any amount can match; the rest stays live on the book.', aon: 'Only matches if the entire quantity executes in one go. Smaller counterparties go to your primary representative as negotiations.', min: 'Only matches when at least this many shares execute at a time.' };
  const syncFill = () => { const k = form.fill.value; form.querySelector('.fill-min').classList.toggle('hidden', k !== 'min'); form.querySelector('#fill-hint').textContent = FILL_HINT[k]; form.minFill.required = k === 'min'; };
  form.fill.addEventListener('change', () => { syncFill(); upd(); }); syncFill();
  form.addEventListener('input', upd); drawCtx();
  form.addEventListener('submit', e => { e.preventDefault(); const c = D.company(form.company.value); if (!c) return;
    if (!D.canTrade()) { const rq = D.submitRequest({ kind: isL ? 'ask' : 'bid', companyId: c.id, price: +form.price.value, qty: +form.qty.value, transferType: form.transferType.value, shareType: form.shareType.value, days: +form.days.value, fill: form.fill.value, minFill: +form.minFill.value || 0 }); toast(`Request ${rq.id} sent to your primary representative`); go('#/orders/requests'); return; }
    const r = D.placeOrder({ companyId: c.id, side, price: +form.price.value, qty: +form.qty.value, transferType: form.transferType.value, shareType: form.shareType.value, days: +form.days.value, fill: form.fill.value, minFill: +form.minFill.value || 0 });
    toast(r.match ? `${r.order.id} matched ${num(r.match.qty)} shares @ ${money(r.match.price)}` : `${isL ? 'Ask' : 'Bid'} ${r.order.id} is live`); go('#/order/' + r.order.id); });
}

// ---------------- custom order builder ----------------
function viewCustomOrder(main, companyId, sideParam) {
  const opts = D.COMPANIES.slice().sort((a, b) => a.name.localeCompare(b.name));
  const c0 = D.company(companyId) || null; const rx0 = c0 ? D.price(c0.id) : 0;
  const r2 = v => Math.round(v * 100) / 100;
  const spec = { companyId: c0 ? c0.id : '', side: sideParam === 'ask' || sideParam === 'listing' ? 'listing' : 'bid', pricing: 'single', price: rx0 ? r2(rx0) : '', qty: 1000, tiers: [], offset: -3, fill: 'partial', minFill: 500, shareClass: 'Any', transfers: ['Direct', 'SPV'], days: 30, autoReconfirm: true, gtc: false, guard: 0, visibility: 'public', note: '' };
  const isBid = () => spec.side === 'bid';
  const company = () => D.company(spec.companyId);
  const seedTiers = () => { const c = company(); const rx = c ? r2(D.price(c.id)) : 0; spec.price = rx || ''; spec.tiers = [0, 1].map(i => ({ qty: 1000, price: rx ? r2(rx * (isBid() ? 1 - i * 0.03 : 1 + i * 0.03)) : '' })); };
  seedTiers();
  const effPrice = () => { const c = company(); if (!c) return 0; return spec.pricing === 'pegged' ? r2(D.price(c.id) * (1 + (+spec.offset || 0) / 100)) : +spec.price || 0; };
  const tiers = () => spec.pricing === 'ladder' ? spec.tiers.map(t => ({ qty: +t.qty || 0, price: +t.price || 0 })) : [{ qty: +spec.qty || 0, price: effPrice() }];
  const optCard = (k, v, title, sub, on) => `<label class="opt-card ${on ? 'on' : ''}"><input type="radio" name="${k}" value="${v}" data-k="${k}" data-rerender="1" ${on ? 'checked' : ''}><b>${title}</b><span>${sub}</span></label>`;
  const render = () => {
    const c = company(); const rx = c ? D.price(c.id) : 0;
    main.innerHTML = `<div class="page narrow">
      ${pageHead({ icon: PH.custom, title: `Custom order · ${isBid() ? 'bid' : 'ask'} with custom terms`, sub: `Set every term yourself. Anything you leave at its default behaves like a standard ${isBid() ? 'bid' : 'ask'}. Options, forwards, SPVs and special-terms deals are the other tiles.`, actions: `<a class="btn outline sm" href="#/new/${spec.side}${c ? '/' + c.id : ''}">Use the simple form instead</a>` })}
      ${arrChooser('order', c ? c.id : companyId)}
      <form class="builder" id="cb-form" autocomplete="off" style="margin-top:14px">
        <div class="card">
          <div class="bsec"><div class="bsec-h"><span class="bnum">1</span><h3>Which way, and what</h3></div>
            <div class="row" style="gap:18px;align-items:flex-end;flex-wrap:wrap"><div class="side-toggle"><button type="button" class="bid ${isBid() ? 'on' : ''}" data-side="bid">Bid · I'm buying</button><button type="button" class="ask ${isBid() ? '' : 'on'}" data-side="listing">Ask · I'm selling</button></div>
              <div style="flex:1;min-width:300px">${companyPicker('cpick', spec.companyId)}</div></div>
            ${c ? `<div style="margin-top:14px">${pricingStrip(c)}</div>` : ''}</div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>Pricing</h3></div>
            <div class="opt-cards">${optCard('pricing', 'single', 'Single price', 'One price for the whole order', spec.pricing === 'single')}${optCard('pricing', 'ladder', 'Price ladder', `Several tiers, ${isBid() ? 'buying more as the price falls' : 'selling more as the price rises'}`, spec.pricing === 'ladder')}${optCard('pricing', 'pegged', 'Pegged to RX price', 'Floats with the RX price at a % offset', spec.pricing === 'pegged')}</div>
            <div style="margin-top:14px">${spec.pricing === 'single' ? `<div class="grid-2"><div class="field"><label>Number of shares</label><input type="number" min="1" step="1" data-k="qty" value="${esc(spec.qty)}"></div><div class="field"><label>Price per share</label><input type="number" min="0.01" step="0.01" data-k="price" value="${esc(spec.price)}"></div></div>`
              : spec.pricing === 'ladder' ? `<div class="ladder"><div class="ladder-row head"><span></span><span class="t">Shares</span><span class="t">Price / sh</span><span class="t">Subtotal</span><span></span></div>${spec.tiers.map((t, i) => `<div class="ladder-row"><span class="t">T${i + 1}</span><input type="number" min="1" step="1" data-tier="${i}" data-k="qty" value="${esc(t.qty)}"><input type="number" min="0.01" step="0.01" data-tier="${i}" data-k="price" value="${esc(t.price)}"><span class="sub" data-sub="${i}">${money((+t.qty || 0) * (+t.price || 0), 0)}</span><button type="button" class="icon-btn xs" data-del-tier="${i}" ${spec.tiers.length <= 1 ? 'disabled' : ''} title="Remove tier">✕</button></div>`).join('')}<div class="row" style="margin-top:4px"><button type="button" class="btn outline sm" id="add-tier" ${spec.tiers.length >= 5 ? 'disabled' : ''}>${ICON.plus} Add tier</button><span class="tiny muted">Each tier becomes its own order on the book, linked as one group you can manage together.</span></div></div>`
              : `<div class="grid-2"><div class="field"><label>Number of shares</label><input type="number" min="1" step="1" data-k="qty" value="${esc(spec.qty)}"></div><div class="field"><label>Offset from RX price (%)</label><input type="number" step="0.5" min="-50" max="50" data-k="offset" value="${esc(spec.offset)}"><span class="hint">${c ? `RX price is ${money(rx)} now, so your ${isBid() ? 'bid' : 'ask'} rests at <b id="peg-now">${money(effPrice())}</b> and re-pegs whenever the RX price moves.` : 'Pick a company to see the pegged price.'}</span></div></div>`}</div></div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">3</span><h3>Fill rules</h3></div>
            <div class="opt-cards">${optCard('fill', 'partial', 'Partial fills OK', 'Match any amount; the rest stays live', spec.fill === 'partial')}${optCard('fill', 'min', 'Minimum fill', 'Only match at least N shares at a time', spec.fill === 'min')}${optCard('fill', 'aon', 'All-or-none', 'Only match the entire order in one go', spec.fill === 'aon')}</div>
            ${spec.fill === 'min' ? `<div class="field" style="margin-top:12px;max-width:260px"><label>Minimum shares per fill</label><input type="number" min="1" step="1" data-k="minFill" value="${esc(spec.minFill)}"></div>` : ''}</div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">4</span><h3>Shares and transfer</h3></div>
            <div class="grid-2"><div class="field"><label>Share class ${isBid() ? 'you will accept' : 'you are selling'}</label><select data-k="shareClass">${['Any', 'Common', 'Preferred'].map(v => `<option ${spec.shareClass === v ? 'selected' : ''}>${v}</option>`).join('')}</select><span class="hint">${isBid() ? 'Any lets you match asks in either class.' : 'Buyers who only want the other class will not match.'}</span></div>
              <div class="field"><label>Transfer types ${isBid() ? 'you will accept' : 'you can offer'}</label><div class="row" style="gap:16px;height:42px">${['Direct', 'SPV', 'Forward'].map(t => `<label class="check" style="align-items:center"><input type="checkbox" data-transfer="${t}" ${spec.transfers.includes(t) ? 'checked' : ''}><span>${t}</span></label>`).join('')}</div><span class="hint">Direct transfers may need company approval and carry a transfer fee. SPV and forward structures stay off the cap table.</span></div></div></div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">5</span><h3>Timing</h3></div>
            <div class="grid-2"><div class="field"><label>Valid for (days)</label><input type="number" min="1" max="365" data-k="days" value="${esc(spec.days)}" ${spec.gtc ? 'disabled' : ''}></div>
              <div class="stack" style="gap:10px;padding-top:26px"><label class="check"><input type="checkbox" data-k="gtc" data-rerender="1" ${spec.gtc ? 'checked' : ''}><span>Good till cancelled</span></label><label class="check"><input type="checkbox" data-k="autoReconfirm" ${spec.autoReconfirm ? 'checked' : ''} ${spec.gtc ? 'disabled' : ''}><span>Auto-reconfirm every 30 days <span class="tiny muted">so it never goes stale on the book</span></span></label></div></div></div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">6</span><h3>Guardrail and visibility</h3></div>
            <div class="grid-2"><div class="field"><label>Cancel automatically if the RX price moves against you by more than</label><div class="row"><input type="number" min="0" max="50" step="1" data-k="guard" value="${esc(spec.guard)}" style="max-width:120px"><span class="muted">% &nbsp;(0 = never)</span></div><span class="hint">${isBid() ? 'The bid is cancelled once the RX price rises this far above it, so you are not left chasing a market that has moved.' : 'The ask is cancelled once the RX price falls this far below it.'}</span></div>
              <div class="field"><label>Who can see it</label><div class="opt-cards one-col">${optCard('visibility', 'public', 'Public', 'On the order book with your order ID', spec.visibility === 'public')}${optCard('visibility', 'anonymous', 'Anonymous', 'On the book, but never marked as yours', spec.visibility === 'anonymous')}${optCard('visibility', 'rep', 'Representative only', 'Off the book. Your rep works it as a private indication', spec.visibility === 'rep')}</div></div></div></div>
          <div class="bsec"><div class="bsec-h"><span class="bnum">7</span><h3>Note to your primary representative <span class="muted" style="font-weight:500">(optional)</span></h3></div>
            <div class="field"><textarea data-k="note" placeholder="e.g. Happy to take a blend of common and preferred if the blended price works. Can sign this week.">${esc(spec.note)}</textarea></div></div>
        </div>
        <div class="stack summary"><div class="card"><div class="card-head"><span class="label">Order summary</span>${c ? `<a class="link small" href="#/company/${c.id}">${esc(c.name)}</a>` : ''}</div><div class="card-body" id="cb-summary"></div>
          <div class="card-foot" style="background:#fff">${D.canTrade() ? '' : `<div style="margin-bottom:12px">${gateCard('this custom order')}</div>`}<div style="margin-bottom:10px">${disclosureBlock()}</div><label class="check" style="margin-bottom:12px"><input type="checkbox" name="ack" required><span>${isBid() ? 'I understand that placing this bid communicates a serious intention to complete an investment on these terms.' : 'I confirm I have the ability to sell these shares and intend to transact on these terms.'}</span></label><button class="btn block ${isBid() ? 'bid' : 'ask'}" type="submit" id="cb-submit">Place custom ${isBid() ? 'bid' : 'ask'}</button></div></div></div>
      </form></div>`;
    wire(); drawSummary();
  };
  const drawSummary = () => {
    const box = main.querySelector('#cb-summary'); const c = company(); const sub = main.querySelector('#cb-submit');
    sub.textContent = !D.canTrade() ? 'Submit as request' : spec.visibility === 'rep' ? 'Send to my representative' : `Place custom ${isBid() ? 'bid' : 'ask'}`;
    if (!c) { box.innerHTML = '<div class="muted">Pick a company to see pricing, fees and how this order would sit on the book.</div>'; return; }
    const ts = tiers(); const shares = ts.reduce((s, t) => s + t.qty, 0); const gross = ts.reduce((s, t) => s + t.qty * t.price, 0);
    const rx = D.price(c.id), hb = D.highestBid(c.id), la = D.lowestAsk(c.id);
    const opp = isBid() ? D.liveListings(c.id) : D.liveBids(c.id);
    const ok = o => (spec.shareClass === 'Any' || o.shareType === spec.shareClass) && (!spec.transfers.length || spec.transfers.includes(o.transferType));
    const need = q => spec.fill === 'aon' ? q : spec.fill === 'min' ? Math.min(+spec.minFill || 1, q) : 1;
    const preview = ts.map((t, i) => { const label = ts.length > 1 ? `Tier ${i + 1}` : 'This order';
      if (!(t.qty > 0 && t.price > 0)) return `<div class="sum-note">${label}: enter shares and a price.</div>`;
      if (spec.visibility === 'rep') return `<div class="sum-note">${label}: stays off the book. ${esc(D.rep(D.profile().rep).name)} works it privately.</div>`;
      const m = opp.find(o => ok(o) && (isBid() ? o.price <= t.price : o.price >= t.price) && Math.min(t.qty, o.qty) >= need(t.qty));
      if (m) return `<div class="sum-note green">${label}: matches now against ${esc(m.id)} · ${num(Math.min(t.qty, m.qty))} sh @ ${money(m.price)}</div>`;
      const ref = isBid() ? la : hb; const d = ref ? (t.price - ref) / ref : null;
      return `<div class="sum-note">${label}: rests on the book${d != null ? `, ${pct(d)} vs ${isBid() ? 'lowest ask' : 'highest bid'} ${money(ref)}` : ''}.</div>`; }).join('');
    const term = (k, v) => `<div class="term"><div class="k">${k}</div><div class="v wrap">${v}</div></div>`;
    box.innerHTML = `<div class="sum-row"><span>${isBid() ? 'Bid' : 'Ask'} for</span><span class="v">${num(shares)} shares</span></div>
      ${ts.length > 1 ? ts.map((t, i) => `<div class="sum-row small"><span>Tier ${i + 1}</span><span class="v">${num(t.qty)} @ ${money(t.price)}</span></div>`).join('') : `<div class="sum-row"><span>${spec.pricing === 'pegged' ? `Pegged price now (RX ${spec.offset >= 0 ? '+' : ''}${(+spec.offset || 0).toFixed(1)}%)` : 'Price per share'}</span><span class="v">${money(ts[0].price)}</span></div>`}
      <div style="margin:12px 0">${feeBlock(c.id, gross, isBid() ? 'buy' : 'sell')}</div>
      <div class="sum-row"><span>Market now</span><span class="v small">Bid ${money(hb)} · Ask ${money(la)} · RX ${money(rx)}</span></div>
      <div class="sum-notes">${preview}</div>
      <div class="term-list" style="margin-top:14px">${term('Fill', spec.fill === 'aon' ? 'All-or-none' : spec.fill === 'min' ? `Min ${num(+spec.minFill || 0)} sh` : 'Partial OK')}${term('Class', esc(spec.shareClass))}${term('Transfer', spec.transfers.map(esc).join(', ') || '<span class="down">none selected</span>')}${term('Expiry', spec.gtc ? 'Good till cancelled' : `${+spec.days || 30} days${spec.autoReconfirm ? ', auto-reconfirm' : ''}`)}${term('Guardrail', +spec.guard > 0 ? `${+spec.guard}% against` : 'None')}${term('Visibility', spec.visibility === 'rep' ? 'Rep only' : spec.visibility === 'anonymous' ? 'Anonymous' : 'Public')}</div>`;
  };
  const wire = () => {
    const form = main.querySelector('#cb-form');
    form.querySelectorAll('[data-side]').forEach(b => b.onclick = () => { spec.side = b.dataset.side; seedTiers(); render(); });
    wireCompanyPicker(form, 'cpick', id => { spec.companyId = id; seedTiers(); render(); });
    const handle = e => {
      const el = e.target; const k = el.dataset.k;
      if (el.dataset.tier != null) { spec.tiers[+el.dataset.tier][k] = el.value; const s = form.querySelector(`[data-sub="${el.dataset.tier}"]`); if (s) { const t = spec.tiers[+el.dataset.tier]; s.textContent = money((+t.qty || 0) * (+t.price || 0), 0); } }
      else if (el.dataset.transfer) spec.transfers = [...form.querySelectorAll('[data-transfer]:checked')].map(x => x.dataset.transfer);
      else if (k) spec[k] = el.type === 'checkbox' ? el.checked : el.value;
      if (k === 'offset') { const p = form.querySelector('#peg-now'); if (p) p.textContent = money(effPrice()); }
      if (el.dataset.rerender) { if (k === 'companyId') seedTiers(); render(); return; }
      drawSummary();
    };
    form.addEventListener('input', e => { if (['checkbox', 'radio', 'select-one'].includes(e.target.type)) return; handle(e); });
    form.addEventListener('change', e => { if (!['checkbox', 'radio', 'select-one'].includes(e.target.type)) return; handle(e); });
    const add = form.querySelector('#add-tier'); if (add) add.onclick = () => { const last = spec.tiers[spec.tiers.length - 1]; spec.tiers.push({ qty: last.qty, price: r2((+last.price || 0) * (isBid() ? 0.97 : 1.03)) }); render(); };
    form.querySelectorAll('[data-del-tier]').forEach(b => b.onclick = () => { spec.tiers.splice(+b.dataset.delTier, 1); render(); });
    form.addEventListener('submit', e => { e.preventDefault(); const c = company(); if (!c) { toast('Pick a company first', false); return; }
      const ts = tiers(); if (ts.some(t => !(t.qty > 0 && t.price > 0))) { toast('Every tier needs a share count and a price', false); return; }
      if (spec.fill === 'min' && +spec.minFill > Math.max(...ts.map(t => t.qty))) { toast('Minimum fill cannot exceed the order size', false); return; }
      if (!spec.transfers.length) { toast('Pick at least one transfer type', false); return; }
      const payload = Object.assign({}, spec, { qty: +spec.qty, price: effPrice(), offset: (+spec.offset || 0) / 100, guard: (+spec.guard || 0) / 100, minFill: +spec.minFill || 0, days: +spec.days || 30, tiers: ts });
      if (!D.canTrade()) { const rq = D.submitRequest({ kind: 'custom', companyId: c.id, spec: payload, summary: `${ts.length} ${ts.length === 1 ? 'tier' : 'tiers'}, ${num(ts.reduce((s_, t) => s_ + t.qty, 0))} shares`, note: spec.note }); toast(`Request ${rq.id} sent to your primary representative`); go('#/orders/requests'); return; }
      const r = D.placeCustomOrder(payload);
      if (r.private) { toast(`Sent to ${D.rep(D.profile().rep).name} as a private indication`); go('#/orders/iois'); return; }
      const m = r.matches.length; toast(m ? `${r.groupId}: ${m} of ${r.orders.length} ${r.orders.length === 1 ? 'order' : 'tiers'} matched immediately` : `Custom ${isBid() ? 'bid' : 'ask'} ${r.groupId} is live${r.orders.length > 1 ? ` (${r.orders.length} tiers)` : ''}`);
      go('#/order/' + r.orders[0].id); });
  };
  render();
}

// ---------------- brokerage account ----------------

// My Orders filter and tab, kept across renders.
let ordersFilter = 'all'; let ordersTab = 'orders';
// My Orders: bids, asks, bids on others, requests, arrangements, history.
function viewOrders(main) {
  const tabBtn = (k, l, n) => `<button class="${ordersTab === k ? 'on' : ''}" data-otab="${k}">${l}${n != null ? ` <span class="cnt">${n}</span>` : ''}</button>`;
  if (ordersTab === 'settlements') ordersTab = 'matches';
  const myM = D.matchRecords().filter(r => r.mine), iois = D.myIOIs().filter(i => i.status === 'active'), alerts = D.alerts(), desk = D.deskTrades(), reqs = D.requests();
  const tabsHtml = `<div class="tabs" style="margin-bottom:18px">${tabBtn('orders', 'Orders')}${tabBtn('matches', 'Matches', myM.filter(r => r.label === 'Awaiting approval' || r.label === 'Settling').length)}${tabBtn('desk', 'Desk trades', desk.length)}${tabBtn('iois', 'Indications', iois.length)}${tabBtn('alerts', 'Alerts', alerts.length)}${tabBtn('requests', 'Requests', reqs.filter(r => r.status === 'pending').length)}${tabBtn('arrangements', 'Arrangements', D.arrangements().filter(x => ['submitted', 'structuring', 'term sheet'].includes(x.status)).length)}</div>`;
  if (ordersTab !== 'orders') {
    let body = '';
    if (ordersTab === 'matches') body = `<div class="card"><div class="card-head"><span class="label">Your matches</span><span class="small muted">A match is a bid and an ask that crossed. Rainmaker approves it, then settlement runs here.</span></div>${matchesTable(myM, { empty: 'No matches yet. When one of your bids or asks crosses with another member, it appears here awaiting Rainmaker\'s approval.' })}</div>` + myM.filter(r => r.settlement && r.label === 'Settling').map(r => `<div class="card"><div class="card-head"><span class="row">${logo(r.c, 'sm')}<b>${esc(r.c.name)}</b><span class="badge ${r.buyer.id === 'you' ? 'bid' : 'listing'}">${r.buyer.id === 'you' ? 'Buy' : 'Sell'}</span>${r.desk ? '<span class="badge gold">Desk</span>' : ''}</span><a class="link small" href="${r.href}">Match ${esc(r.id)} · ${fmtDate(r.ts)}</a></div><div class="card-body">${trackerBlock(r.settlement)}</div></div>`).join('');
    if (ordersTab === 'desk') body = `<div class="card">${desk.length ? `<table class="table"><thead><tr><th>Date</th><th>Company</th><th>Side</th><th class="num">Shares</th><th class="num">Desk price</th><th class="num">Market mid</th><th class="num">Spread paid</th><th class="num">Notional</th></tr></thead><tbody>${desk.map(t => { const c = D.company(t.companyId); return `<tr class="clickable" data-href="#/company/${c.id}"><td>${fmtPlaced(t.ts)}</td><td><span class="row">${logo(c, 'sm')}${esc(c.name)}</span></td><td><span class="badge ${t.side === 'buy' ? 'bid' : 'listing'}">${t.side === 'buy' ? 'Bought from desk' : 'Sold to desk'}</span></td><td class="num">${num(t.qty)}</td><td class="num strong">${money(t.price)}</td><td class="num">${money(t.mid)}</td><td class="num">${(t.half * 100).toFixed(1)}% · ${money(t.capture, 0)}</td><td class="num strong">${money(t.price * t.qty, 0)}</td></tr>`; }).join('')}</tbody></table>` : '<div class="empty">No desk trades yet. Use "Buy from us · Sell to us" on any company page.</div>'}</div>`;
    if (ordersTab === 'iois') body = `<div class="card">${iois.length ? `<table class="table"><thead><tr><th>Company</th><th>Interest</th><th class="num">Price</th><th class="num">Shares</th><th>Recorded</th><th></th></tr></thead><tbody>${iois.map(i => { const c = D.company(i.companyId); return `<tr class="clickable" data-href="#/company/${c.id}"><td><span class="row">${logo(c, 'sm')}${esc(c.name)}</span></td><td>${i.side === 'buy' ? 'Buy up to' : 'Sell from'}</td><td class="num strong">${money(i.price)}</td><td class="num">${num(i.qty)}</td><td>${fmtPlaced(i.created)}</td><td class="num"><button class="btn ghost sm" data-withdraw="${i.id}">Withdraw</button></td></tr>`; }).join('')}</tbody></table>` : '<div class="empty">No active indications of interest. Record one on any company page and your primary representative will call when the market moves.</div>'}</div>`;
    if (ordersTab === 'requests') body = `<div class="card"><div class="card-head"><span class="label">Requests worked by your primary representative</span><span class="small muted">${D.canTrade() ? 'Verified: new orders go straight to the book' : 'Placed automatically once verification is approved'}</span></div>${reqs.length ? `<table class="table compact"><thead><tr><th>Request</th><th>What</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>${reqs.map(r => `<tr><td><span class="oid">${esc(r.id)}</span></td><td>${esc(r.what)}${r.result && r.status === 'converted' ? ` <span class="tiny muted">→ ${esc(String(r.result))}</span>` : ''}</td><td>${fmtPlaced(r.created)}</td><td><span class="badge ${r.status === 'converted' ? 'verified' : r.status === 'pending' ? 'pending' : 'status'}">${esc(r.status)}</span></td><td class="num">${r.status === 'pending' ? `<button class="btn danger sm" data-withdraw-req="${r.id}">Withdraw</button>` : ''}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">No requests. Members who are not yet verified can submit bids, asks, custom orders, desk quotes, allocations and data room access as requests.</div>'}</div>`;
    if (ordersTab === 'arrangements') body = `<div class="card"><div class="card-head"><span class="label">Structured arrangements</span><a class="btn outline custom sm" href="#/new/arrange">New structured deal</a></div>${arrangementsTable(D.arrangements(), false)}</div>`;
    if (ordersTab === 'alerts') body = `<div class="card">${alerts.length ? `<table class="table"><thead><tr><th>Company</th><th>Condition</th><th class="num">Price</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${alerts.map(a => { const c = D.company(a.companyId); return `<tr class="clickable" data-href="#/company/${c.id}"><td><span class="row">${logo(c, 'sm')}${esc(c.name)}</span></td><td>${esc(D.ALERT_TYPES[a.type])}</td><td class="num strong">${D.ALERT_NO_PRICE.includes(a.type) ? (a.basis ? money(a.basis) : '—') : money(a.price)}</td><td>${a.triggered ? `<span class="badge verified">Fired ${fmtDateShort(a.triggered)}</span>` : '<span class="badge status">Armed</span>'}</td><td>${fmtDate(a.created)}</td><td class="num"><button class="btn ghost sm" data-alert-del="${a.id}">Remove</button></td></tr>`; }).join('')}</tbody></table>` : '<div class="empty">No alerts. Use the Alerts button on a company page.</div>'}</div>`;
    main.innerHTML = `<div class="page wide">${pageHead({ icon: PH.orders, title: 'My Orders', sub: 'Everything you have on the exchange: live bids and asks, matches and their settlement, desk trades, indications, alerts, requests and structured arrangements.', actions: `<a class="btn ask sm" href="#/new/listing">${ICON.cash} New ask</a><a class="btn bid sm" href="#/new/bid">${ICON.cart} New bid</a><a class="btn outline custom sm" href="#/new/custom">Custom order</a>` })}${tabsHtml}<div class="stack">${body}</div></div>`;
    main.querySelectorAll('[data-otab]').forEach(b => b.onclick = () => { ordersTab = b.dataset.otab; viewOrders(main); });
    return;
  }
  const all = D.myOrders().map(o => Object.assign({ kind: o.side === 'listing' ? 'Ask' : 'Bid' }, o)).concat(D.myListingBids().map(b => Object.assign({ kind: 'Bid on ask', side: 'bid' }, b))).sort((a, b) => b.created - a.created);
  const live = all.filter(o => o.status === 'live'), matched = all.filter(o => ['sold', 'completed', 'matched'].includes(o.status)), cancelled = all.filter(o => o.status === 'cancelled');
  const shown = ordersFilter === 'all' ? all : ordersFilter === 'live' ? live : ordersFilter === 'matched' ? matched : cancelled;
  const chip = (k, l) => `<button class="chip ${ordersFilter === k ? 'on' : ''}" data-f="${k}">${l}</button>`;
  main.innerHTML = `<div class="page wide">
    ${pageHead({ icon: PH.orders, title: 'My Orders', sub: 'Everything you have on the exchange: live bids and asks, matches and their settlement, desk trades, indications, alerts, requests and structured arrangements.', actions: `<a class="btn ask sm" href="#/new/listing">${ICON.cash} New ask</a><a class="btn bid sm" href="#/new/bid">${ICON.cart} New bid</a><a class="btn outline custom sm" href="#/new/custom">Custom order</a>`, stats: [['Live orders', live.length], ['Live value', compact(live.reduce((s, o) => s + o.price * o.qty, 0)), 'in open bids and asks'], ['Matched', matched.length], ['Cancelled', cancelled.length]] })}${tabsHtml}
    <div class="card"><div class="card-head"><div class="chips">${chip('all', 'All')}${chip('live', 'Live')}${chip('matched', 'Matched')}${chip('cancelled', 'Cancelled')}</div><span class="muted small">${shown.length} orders</span></div>
      ${shown.length ? `<table class="table"><thead><tr><th>Order</th><th>Type</th><th>Company</th><th class="num">Shares</th><th class="num">Price / sh</th><th class="num">Total</th><th>Placed</th><th>Status</th><th></th></tr></thead><tbody>${shown.map(o => { const c = D.company(o.companyId); const href = o.listingId ? '#/order/' + o.listingId : '#/order/' + o.id; return `<tr class="clickable" data-href="${href}"><td><span class="oid">${esc(o.id)}</span></td><td><span class="row" style="gap:6px"><span class="badge ${o.side === 'listing' ? 'listing' : 'bid'}">${o.kind}</span>${customBadge(o)}</span></td><td><span class="row">${logo(c, 'sm')}${esc(c.name)}</span></td><td class="num">${num(o.qty)}</td><td class="num">${money(o.price)}</td><td class="num">${money(o.price * o.qty, 0)}</td><td>${fmtPlaced(o.created)}${o.status === 'live' ? `<div class="tiny"><span class="exp-chip ${daysLeft(o) <= 3 ? 'urgent' : daysLeft(o) <= 7 ? 'soon' : ''}">expires in ${daysLeft(o)}d</span></div>` : ''}</td><td><span class="badge status">${o.status === 'live' ? (o.soldQty ? 'Partially filled' : 'Live') : o.status === 'cancelled' ? 'Cancelled' : o.status === 'matched' ? 'Matched · pending' : 'Filled'}</span>${o.cancelReason ? `<div class="tiny muted">${esc(o.cancelReason)}</div>` : o.soldQty ? `<div class="tiny muted">${num(o.soldQty)} matched${D.matchesFor(o.id).length ? ` · <a class="link" href="#/match/${esc(D.matchesFor(o.id)[0].id)}">${esc(D.matchesFor(o.id)[0].id)}</a>` : ''}</div>` : ''}</td><td class="num" style="white-space:nowrap">${o.status === 'live' ? `${daysLeft(o) <= 7 && !o.listingId ? `<button class="btn outline sm" data-reconfirm="${o.id}">Reconfirm</button> ` : ''}<button class="btn danger sm" data-cancel="${o.id}">Cancel</button>` : ''}</td></tr>`; }).join('')}</tbody></table>` : `<div class="empty"><b>Nothing here yet.</b><div class="small" style="margin-top:4px">Bids and asks you place appear here with their status, expiry and settlement. Start from <a class="link" href="#/browse">Browse Companies</a>.</div></div>`}</div></div>`;
  main.querySelectorAll('.chip').forEach(b => b.onclick = () => { ordersFilter = b.dataset.f; viewOrders(main); });
  main.querySelectorAll('[data-otab]').forEach(b => b.onclick = () => { ordersTab = b.dataset.otab; viewOrders(main); });
}

// ---------------- rep desk (internal) ----------------

// Titles and blurbs for each structured deal type in the custom order flow.
const ARR_META = { order: { t: 'Bid / ask with custom terms', s: 'Price ladders, pegged prices, fill rules, guardrails', href: '#/new/custom' }, option: { t: 'Option contract', s: 'Buy or write a call or put on private shares', href: '#/new/arrange/option' }, forward: { t: 'Forward purchase / sale', s: 'Agree a price now, settle on a date or liquidity event', href: '#/new/arrange/forward' }, spv: { t: 'SPV', s: 'Join a Rainmaker SPV or form one around a block', href: '#/new/arrange/spv' }, structured: { t: 'Special terms', s: 'Contingent pricing, collars, tranches, seller financing, swaps', href: '#/new/arrange/structured' } };
// Tiles to pick a structured deal type.
function arrChooser(active, companyId) {
  const suf = companyId ? '/' + companyId : '';
  return `<div class="label" style="margin-bottom:8px">Step 1 · What kind of order</div><div class="arr-types">${Object.entries(ARR_META).map(([k, m]) => `<a class="arr-type ${k === active ? 'on' : ''}" href="${k === 'order' ? '#/new/custom' + suf : '#/new/arrange/' + k + suf}"><b>${m.t}</b><span>${m.s}</span></a>`).join('')}</div>`;
}
// Structured deal forms: option, forward, SPV, special terms, DP interest, Liquid Security, own contract.
function viewArrangement(main, type, companyId) {
  if (!ARR_META[type] || type === 'order') { main.innerHTML = `<div class="page narrow">${pageHead({ icon: PH.custom, title: 'Custom order', sub: 'Standard orders go straight to the book. Everything else is structured by your primary representative and the Rainmaker desk, and comes back to you as a term sheet.', actions: '<a class="btn outline sm" href="#/alternatives">Alternatives</a>' })}${arrChooser(null, companyId)}</div>`; return; }
  const opts = D.COMPANIES.slice().sort((a, b) => a.name.localeCompare(b.name)); const c0 = D.company(companyId) || null; const rep_ = D.rep(D.profile().rep);
  const spvs = D.FUNDS.filter(f => f.type === 'spv');
  const spec = { type, companyId: c0 ? c0.id : (type === 'spv' ? '' : opts[0].id), side: 'buy', qty: 1000, note: '',
    optKind: 'call', strike: c0 ? +(D.price(c0.id) * 1.15).toFixed(2) : '', months: 12, style: 'American', settle: 'Physical', premium: '', counterparty: 'desk',
    fwdPrice: c0 ? +D.price(c0.id).toFixed(2) : '', trigger: 'date', trigMonths: 12, deposit: 20, rofr: 'refund',
    mode: spvs.some(f => f.status !== 'Closed') ? 'join' : 'form', fundId: (spvs.find(f => f.status === 'Open') || {}).id || '', amount: 50000, target: 10, ticket: 25000, commit: 250000, mgmt: 1, carry: 10, open: true,
    basis: 'fixed', price: c0 ? +D.price(c0.id).toFixed(2) : '', discount: 20, ref: '409a', collarMin: '', collarMax: '', conts: ['rofr'], ipoMonths: 18, roundVal: '', tranches: 1, trancheMonths: 3, payment: 'cash', down: 50, finMonths: 12, swapCompany: '', trueUp: 0, excl: 14, expiry: 30 };
  const company = () => D.company(spec.companyId);
  const optCard = (k, v, title, sub, on) => `<label class="opt-card ${on ? 'on' : ''}"><input type="radio" name="${k}" value="${v}" data-k="${k}" data-rerender="1" ${on ? 'checked' : ''}><b>${title}</b><span>${sub}</span></label>`;
  const companyField = () => companyPicker('cpick', spec.companyId, 'Underlying company');
  const sideToggle = (a, b) => `<div class="side-toggle"><button type="button" class="bid ${spec.side === 'buy' ? 'on' : ''}" data-side="buy">${a}</button><button type="button" class="ask ${spec.side === 'sell' ? 'on' : ''}" data-side="sell">${b}</button></div>`;
  const what = () => { const c = company(); const q = num(+spec.qty || 0);
    if (type === 'option') return `${spec.side === 'buy' ? 'buy' : 'write'} ${spec.optKind} on ${q} ${c ? c.name : '?'} sh, strike ${money(+spec.strike)}, ${spec.months}m ${spec.style}, ${spec.settle.toLowerCase()} settlement${spec.premium ? ', premium ' + money(+spec.premium) + '/sh' : ''}, vs ${spec.counterparty === 'desk' ? 'the Rainmaker desk' : 'the market'}`;
    if (type === 'forward') return `forward ${spec.side} of ${q} ${c ? c.name : '?'} sh @ ${money(+spec.fwdPrice)} settling ${spec.trigger === 'date' ? 'in ' + spec.trigMonths + ' months' : 'on ' + { ipo: 'IPO', acq: 'acquisition', round: 'the next priced round' }[spec.trigger]}, ${spec.deposit}% deposit`;
    if (type === 'spv') { const f = D.fund(spec.fundId); return spec.mode === 'join' ? `join ${f ? f.name : 'an SPV'} with ${money(+spec.amount, 0)}` : `form an SPV around ${c ? c.name : '?'}: target ${money(+spec.target * 1e6, 0)}, min ticket ${money(+spec.ticket, 0)}, my commitment ${money(+spec.commit, 0)}, ${spec.mgmt}% mgmt + ${spec.carry}% carry${spec.open ? ', open to other Rainmaker clients' : ', private'}`; }
    const basis = spec.basis === 'fixed' ? money(+spec.price) : spec.basis === 'round' ? `${spec.discount}% discount to the next priced round` : spec.basis === 'ref' ? `${spec.discount}% ${+spec.discount >= 0 ? 'premium' : 'discount'} to the last ${spec.ref === '409a' ? '409A' : 'RX price at close'}` : `collar ${money(+spec.collarMin)}–${money(+spec.collarMax)} around RX at close`;
    const conts = spec.conts.map(k => ({ rofr: 'ROFR waived', ipo: `IPO within ${spec.ipoMonths}m`, round: `next round ≥ ${spec.roundVal || '?'}`, approval: 'company approves buyer', board: 'board consent' })[k]).join(', ');
    return `${spec.side === 'buy' ? 'bid' : 'ask'} for ${q} ${c ? c.name : '?'} sh at ${basis}${conts ? '; contingent on ' + conts : ''}${+spec.tranches > 1 ? `; ${spec.tranches} tranches every ${spec.trancheMonths}m` : ''}; ${spec.payment === 'cash' ? 'cash' : spec.payment === 'finance' ? `seller financing (${spec.down}% down, balance over ${spec.finMonths}m)` : `exchange for ${(D.company(spec.swapCompany) || {}).name || 'other private shares'}`}${+spec.trueUp ? `; ±${spec.trueUp}% true-up to next round` : ''}; ${spec.excl}d exclusivity`; };
  const render = () => {
    const c = company(); const rx = c ? D.price(c.id) : 0; const meta = ARR_META[type];
    let form = '';
    if (type === 'option') { const sig = c ? D.sigmaFor(c) : 0.5; const fair = c ? D.optionPrice({ S: rx, K: +spec.strike, T: +spec.months / 12, sigma: sig, type: spec.optKind }) : 0;
      form = `<div class="bsec"><div class="bsec-h"><span class="bnum">1</span><h3>Position</h3></div><div class="row" style="gap:18px;align-items:flex-end;flex-wrap:wrap">${sideToggle('Buy the option', 'Write (sell) the option')}<div style="flex:1;min-width:300px">${companyField()}</div></div>
        <div class="opt-cards" style="margin-top:14px">${optCard('optKind', 'call', 'Call', spec.side === 'buy' ? 'Right to buy shares at the strike' : 'Obligation to deliver shares at the strike', spec.optKind === 'call')}${optCard('optKind', 'put', 'Put', spec.side === 'buy' ? 'Right to sell shares at the strike' : 'Obligation to buy shares at the strike', spec.optKind === 'put')}</div>${c ? `<div style="margin-top:14px">${pricingStrip(c)}</div>` : ''}</div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>Terms</h3></div><div class="grid-2"><div class="field"><label>Shares covered</label><input type="number" min="100" step="100" data-k="qty" value="${esc(spec.qty)}"></div><div class="field"><label>Strike price ($ / sh)</label><input type="number" step="0.01" data-k="strike" value="${esc(spec.strike)}"><span class="hint">RX price now ${money(rx)}${spec.strike ? ` · ${pct((+spec.strike - rx) / rx)} ${+spec.strike >= rx ? 'above' : 'below'}` : ''}</span></div></div>
        <div class="grid-2"><div class="field"><label>Term (months)</label><input type="number" min="1" max="60" data-k="months" value="${esc(spec.months)}"></div><div class="field"><label>Style</label><select data-k="style">${['American', 'European'].map(v => `<option ${spec.style === v ? 'selected' : ''}>${v}</option>`).join('')}</select><span class="hint">American can be exercised any time; European only at expiry.</span></div></div>
        <div class="grid-2"><div class="field"><label>Settlement</label><select data-k="settle">${['Physical', 'Cash'].map(v => `<option ${spec.settle === v ? 'selected' : ''}>${v}</option>`).join('')}</select><span class="hint">Physical delivers shares (subject to ROFR); cash pays the difference to RX price at exercise.</span></div><div class="field"><label>Premium you ${spec.side === 'buy' ? 'offer' : 'ask'} ($ / sh, optional)</label><input type="number" step="0.01" data-k="premium" value="${esc(spec.premium)}" placeholder="${fair.toFixed(2)}"><span class="hint">Leave blank to let the desk quote. Indicative fair value ${money(fair)} (σ ${(sig * 100).toFixed(0)}%).</span></div></div></div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">3</span><h3>Counterparty</h3></div><div class="opt-cards"><label class="opt-card ${spec.counterparty === 'desk' ? 'on' : ''}"><input type="radio" name="counterparty" value="desk" data-k="counterparty" data-rerender="1" ${spec.counterparty === 'desk' ? 'checked' : ''}><b>Rainmaker desk</b><span>Rainmaker writes or buys the option as principal. Fastest.</span></label><label class="opt-card ${spec.counterparty === 'market' ? 'on' : ''}"><input type="radio" name="counterparty" value="market" data-k="counterparty" data-rerender="1" ${spec.counterparty === 'market' ? 'checked' : ''}><b>Another client</b><span>Your rep finds a holder or investor to take the other side.</span></label></div><div class="callout" style="margin-top:12px">Options on private stock are bilateral contracts, not listed derivatives. Transfer on exercise is subject to the company's transfer policy${c ? ` (${esc(c.policy.label)})` : ''}. The desk may require collateral from option writers.</div></div>`; }
    if (type === 'forward') form = `<div class="bsec"><div class="bsec-h"><span class="bnum">1</span><h3>Position</h3></div><div class="row" style="gap:18px;align-items:flex-end;flex-wrap:wrap">${sideToggle('Forward purchase', 'Forward sale')}<div style="flex:1;min-width:300px">${companyField()}</div></div>${c ? `<div style="margin-top:14px">${pricingStrip(c)}</div>` : ''}</div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>Terms</h3></div><div class="grid-2"><div class="field"><label>Shares</label><input type="number" min="100" step="100" data-k="qty" value="${esc(spec.qty)}"></div><div class="field"><label>Forward price ($ / sh, fixed today)</label><input type="number" step="0.01" data-k="fwdPrice" value="${esc(spec.fwdPrice)}"><span class="hint">RX price now ${money(rx)}${spec.fwdPrice ? ` · ${pct((+spec.fwdPrice - rx) / rx)}` : ''}</span></div></div>
        <div class="field"><label>Settles on</label><div class="opt-cards" style="grid-template-columns:repeat(4,1fr)">${[['date', 'A date', 'Fixed months from signing'], ['ipo', 'IPO', 'Shares deliver after lock-up'], ['acq', 'Acquisition', 'Proceeds pass through'], ['round', 'Next priced round', 'Settles at signing of the round']].map(([v, t, s]) => optCard('trigger', v, t, s, spec.trigger === v)).join('')}</div></div>
        ${spec.trigger === 'date' ? `<div class="field" style="max-width:240px"><label>Months until settlement</label><input type="number" min="1" max="60" data-k="trigMonths" value="${esc(spec.trigMonths)}"></div>` : ''}
        <div class="grid-2"><div class="field"><label>Deposit at signing (%)</label><input type="number" min="0" max="100" data-k="deposit" value="${esc(spec.deposit)}"><span class="hint">Held in escrow; balance due at settlement.</span></div><div class="field"><label>If the company blocks the transfer</label><select data-k="rofr">${[['refund', 'Refund deposit, contract void'], ['retry', 'Retry at the next window'], ['cash', 'Cash-settle at RX price']].map(([v, t]) => `<option value="${v}" ${spec.rofr === v ? 'selected' : ''}>${t}</option>`).join('')}</select></div></div>
        <div class="callout">A forward moves economic exposure now and legal title later. Rainmaker papers it as a purchase agreement with a delayed closing; the seller keeps voting rights until delivery.</div></div>`;
    if (type === 'spv') { const f = D.fund(spec.fundId); form = `<div class="bsec"><div class="bsec-h"><span class="bnum">1</span><h3>Join or form</h3></div><div class="opt-cards" style="grid-template-columns:1fr 1fr">${optCard('mode', 'join', 'Join an existing Rainmaker SPV', 'Buy units in a vehicle that already holds or is buying a block', spec.mode === 'join')}${optCard('mode', 'form', 'Form a new SPV', 'Rainmaker aggregates tickets around a block you want', spec.mode === 'form')}</div></div>
        ${spec.mode === 'join' ? `<div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>Vehicle</h3></div><div class="field"><label>SPV</label><select data-k="fundId" data-rerender="1">${spvs.map(x => `<option value="${x.id}" ${spec.fundId === x.id ? 'selected' : ''} ${x.status === 'Closed' ? 'disabled' : ''}>${esc(x.name)} · ${x.status}${x.filled != null ? ' · ' + Math.round(x.filled * 100) + '% filled' : ''}</option>`).join('')}</select></div>
          ${f ? `<table class="kv tight"><tr><th>Underlying</th><td><a class="link" href="#/company/${f.underlying}">${esc(D.company(f.underlying).name)}</a> · entry ${money(f.entryPrice)} vs RX ${money(D.price(f.underlying))} (${pct((D.price(f.underlying) - f.entryPrice) / f.entryPrice)})</td></tr><tr><th>Capacity</th><td>${compact(f.aum)} of ${compact(f.capacity)} · closes ${fmtDate(f.closeDate)}</td></tr><tr><th>Fees</th><td>${(f.fee * 100).toFixed(1)}% management · ${(f.carry * 100).toFixed(0)}% carry</td></tr><tr><th>Minimum</th><td>${money(f.min, 0)}</td></tr></table>` : ''}
          <div class="field" style="max-width:260px"><label>Amount (USD)</label><input type="number" min="${f ? f.min : 25000}" step="5000" data-k="amount" value="${esc(spec.amount)}"></div></div>`
        : `<div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>The block</h3></div>${companyField()}${c ? `<div style="margin-top:14px">${pricingStrip(c)}</div>` : ''}
          <div class="grid-2" style="margin-top:14px"><div class="field"><label>Target vehicle size ($M)</label><input type="number" min="1" step="0.5" data-k="target" value="${esc(spec.target)}"></div><div class="field"><label>Your commitment (USD)</label><input type="number" min="25000" step="5000" data-k="commit" value="${esc(spec.commit)}"></div></div>
          <div class="grid-2"><div class="field"><label>Minimum ticket for others (USD)</label><input type="number" min="10000" step="5000" data-k="ticket" value="${esc(spec.ticket)}"></div><div class="field"><label>Proposed economics</label><div class="row"><input type="number" step="0.25" data-k="mgmt" value="${esc(spec.mgmt)}" style="max-width:90px"><span class="muted">% mgmt</span><input type="number" step="1" data-k="carry" value="${esc(spec.carry)}" style="max-width:90px"><span class="muted">% carry</span></div></div></div>
          <label class="check"><input type="checkbox" data-k="open" ${spec.open ? 'checked' : ''}><span>Let Rainmaker offer the remaining capacity to other clients</span></label>
          <div class="callout">Rainmaker forms the vehicle, sources the block through the exchange or the desk, and administers it. Units keep investors off the company's cap table, which many transfer policies require for small tickets.</div></div>`}`; }
    if (type === 'structured') form = `<div class="bsec"><div class="bsec-h"><span class="bnum">1</span><h3>Position</h3></div><div class="row" style="gap:18px;align-items:flex-end;flex-wrap:wrap">${sideToggle('Bid · I\'m buying', 'Ask · I\'m selling')}<div style="flex:1;min-width:300px">${companyField()}</div><div class="field" style="width:160px"><label>Shares</label><input type="number" min="100" step="100" data-k="qty" value="${esc(spec.qty)}"></div></div>${c ? `<div style="margin-top:14px">${pricingStrip(c)}</div>` : ''}</div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">2</span><h3>How the price is set</h3></div><div class="opt-cards" style="grid-template-columns:repeat(4,1fr)">${optCard('basis', 'fixed', 'Fixed', 'A number today', spec.basis === 'fixed')}${optCard('basis', 'round', 'Discount to next round', 'Price set when the company next raises', spec.basis === 'round')}${optCard('basis', 'ref', 'Relative to a reference', '409A or RX price at close', spec.basis === 'ref')}${optCard('basis', 'collar', 'Collar', 'RX at close, bounded', spec.basis === 'collar')}</div>
        <div style="margin-top:12px">${spec.basis === 'fixed' ? `<div class="field" style="max-width:240px"><label>Price ($ / sh)</label><input type="number" step="0.01" data-k="price" value="${esc(spec.price)}"><span class="hint">RX price now ${money(rx)}</span></div>` : spec.basis === 'round' ? `<div class="field" style="max-width:280px"><label>Discount to the next priced round (%)</label><input type="number" step="1" data-k="discount" value="${esc(spec.discount)}"><span class="hint">Common in pre-round secondaries; the price is unknown until the round prices.</span></div>` : spec.basis === 'ref' ? `<div class="grid-2"><div class="field"><label>Reference</label><select data-k="ref">${[['409a', 'Last 409A valuation'], ['rx', 'RX price on closing day']].map(([v, t]) => `<option value="${v}" ${spec.ref === v ? 'selected' : ''}>${t}</option>`).join('')}</select></div><div class="field"><label>Premium (+) or discount (−) to it (%)</label><input type="number" step="1" data-k="discount" value="${esc(spec.discount)}"></div></div>` : `<div class="grid-2"><div class="field"><label>Floor ($ / sh)</label><input type="number" step="0.01" data-k="collarMin" value="${esc(spec.collarMin)}" placeholder="${(rx * 0.9).toFixed(2)}"></div><div class="field"><label>Cap ($ / sh)</label><input type="number" step="0.01" data-k="collarMax" value="${esc(spec.collarMax)}" placeholder="${(rx * 1.1).toFixed(2)}"></div></div>`}</div>
        <div class="field" style="margin-top:12px;max-width:280px"><label>True-up to the next round (± %)</label><input type="number" min="0" max="50" data-k="trueUp" value="${esc(spec.trueUp)}"><span class="hint">0 = none. Otherwise the price adjusts by up to this much toward the next round price.</span></div></div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">3</span><h3>Contingencies</h3></div><div class="stack" style="gap:8px">${[['rofr', 'Company waives its right of first refusal'], ['approval', 'Company approves the buyer'], ['board', 'Board consent to the transfer'], ['ipo', `Company files for IPO within <input type="number" min="1" max="60" data-k="ipoMonths" value="${esc(spec.ipoMonths)}" class="mini" style="width:70px;height:30px"> months`], ['round', `Next priced round at or above <input data-k="roundVal" value="${esc(spec.roundVal)}" class="mini" placeholder="$5b" style="width:90px;height:30px"> post-money`]].map(([k, t]) => `<label class="check" style="font-weight:500;align-items:center"><input type="checkbox" data-cont="${k}" ${spec.conts.includes(k) ? 'checked' : ''}><span>${t}</span></label>`).join('')}</div></div>
        <div class="bsec"><div class="bsec-h"><span class="bnum">4</span><h3>Closing and payment</h3></div><div class="grid-2"><div class="field"><label>Tranches</label><div class="row"><input type="number" min="1" max="12" data-k="tranches" value="${esc(spec.tranches)}" style="max-width:80px"><span class="muted">closings, every</span><input type="number" min="1" max="24" data-k="trancheMonths" value="${esc(spec.trancheMonths)}" style="max-width:80px"><span class="muted">months</span></div></div><div class="field"><label>Exclusivity (days)</label><input type="number" min="0" max="180" data-k="excl" value="${esc(spec.excl)}"><span class="hint">Counterparty agrees not to shop the block while you diligence.</span></div></div>
        <div class="field"><label>Payment</label><div class="opt-cards">${optCard('payment', 'cash', 'Cash at close', 'Wire to escrow', spec.payment === 'cash')}${optCard('payment', 'finance', 'Seller financing', 'Part now, balance over time', spec.payment === 'finance')}${optCard('payment', 'swap', 'Exchange for other shares', 'Swap private stock you hold', spec.payment === 'swap')}</div></div>
        ${spec.payment === 'finance' ? `<div class="grid-2"><div class="field"><label>Down payment (%)</label><input type="number" min="0" max="100" data-k="down" value="${esc(spec.down)}"></div><div class="field"><label>Balance paid over (months)</label><input type="number" min="1" max="60" data-k="finMonths" value="${esc(spec.finMonths)}"></div></div>` : spec.payment === 'swap' ? `<div class="field"><label>Shares you would exchange</label><select data-k="swapCompany"><option value="">Select…</option>${D.holdings().map(h => `<option value="${h.c.id}" ${spec.swapCompany === h.c.id ? 'selected' : ''}>${esc(h.c.name)} · you hold ${num(h.qty)} @ RX ${money(h.price)}</option>`).join('')}</select><span class="hint">Valued at RX price unless both sides agree otherwise.</span></div>` : ''}
        <div class="field"><label>Offer valid for (days)</label><input type="number" min="1" max="180" data-k="expiry" value="${esc(spec.expiry)}" style="max-width:160px"></div></div>`;
    main.innerHTML = `<div class="page narrow">${pageHead({ icon: PH.custom, title: `Custom order · ${esc(meta.t)}`, sub: `${esc(meta.s)}. Structured by ${esc(rep_.name)} and the Rainmaker desk; you receive a term sheet before anything is binding.`, actions: '<a class="btn outline sm" href="#/alternatives">Alternatives</a>' })}
      ${arrChooser(type, spec.companyId || companyId)}
      <form class="builder" id="arr-form" autocomplete="off" style="margin-top:14px"><div class="card">${form}<div class="bsec"><div class="bsec-h"><span class="bnum">${type === 'option' ? 4 : type === 'forward' ? 3 : type === 'spv' ? 3 : 5}</span><h3>Note to your primary representative <span class="muted" style="font-weight:500">(optional)</span></h3></div><div class="field"><textarea data-k="note" placeholder="Anything the desk should know: timing, tax considerations, why these terms.">${esc(spec.note)}</textarea></div></div></div>
      <div class="stack summary"><div class="card"><div class="card-head"><span class="label">Term sheet preview</span><span class="badge custom">${esc(meta.t)}</span></div><div class="card-body" id="arr-summary"></div><div class="card-foot" style="background:#fff">${D.canRequest() ? '' : ''}<label class="check" style="margin-bottom:12px"><input type="checkbox" name="ack" required><span>I understand this is a request for Rainmaker to structure a bilateral arrangement. Nothing is binding until I sign the term sheet and definitive documents.</span></label><button class="btn block bid" type="submit">Send to the desk</button></div></div></div></form></div>`;
    wire(); drawSummary();
  };
  const drawSummary = () => {
    const box = main.querySelector('#arr-summary'); const c = company(); const rx = c ? D.price(c.id) : 0; const q = +spec.qty || 0;
    const term = (k, v) => `<div class="term"><div class="k">${k}</div><div class="v wrap">${v}</div></div>`;
    let rows = '', extra = '';
    if (type === 'option') { const sig = c ? D.sigmaFor(c) : 0.5; const fair = c ? D.optionPrice({ S: rx, K: +spec.strike, T: +spec.months / 12, sigma: sig, type: spec.optKind }) : 0; const prem = +spec.premium || fair; const intrinsic = spec.optKind === 'call' ? Math.max(0, rx - +spec.strike) : Math.max(0, +spec.strike - rx);
      rows = `${term('Contract', `${spec.side === 'buy' ? 'Long' : 'Short'} ${spec.optKind} · ${spec.style} · ${spec.settle}`)}${term('Shares · strike', `${num(q)} @ ${money(+spec.strike)}`)}${term('Term', `${spec.months} months`)}${term('Premium / sh', `${money(prem)}${spec.premium ? '' : ' (indicative)'}`)}${term('Total premium', money(prem * q, 0))}${term('Breakeven', money(spec.optKind === 'call' ? +spec.strike + prem : +spec.strike - prem))}${term('Intrinsic now', money(intrinsic))}${term('Time value', money(Math.max(0, prem - intrinsic)))}`;
      const scen = [0.7, 0.85, 1, 1.15, 1.3, 1.5].map(m => { const S = rx * m; const pay = spec.optKind === 'call' ? Math.max(0, S - +spec.strike) : Math.max(0, +spec.strike - S); const pl = (spec.side === 'buy' ? pay - prem : prem - pay) * q; return `<tr><td>${money(S)} <span class="tiny muted">(${pct(m - 1)})</span></td><td class="num">${money(pay)}</td><td class="num ${cls(pl)}">${money(pl, 0)}</td></tr>`; }).join('');
      extra = `<div class="label dim" style="margin:12px 0 6px">P&amp;L at expiry by RX price</div><table class="table compact"><thead><tr><th>RX price</th><th class="num">Payoff / sh</th><th class="num">Your P&amp;L</th></tr></thead><tbody>${scen}</tbody></table>`; }
    if (type === 'forward') { const px = +spec.fwdPrice || 0; rows = `${term('Contract', `Forward ${spec.side} · ${spec.trigger === 'date' ? spec.trigMonths + ' months' : { ipo: 'on IPO', acq: 'on acquisition', round: 'on next round' }[spec.trigger]}`)}${term('Shares · price', `${num(q)} @ ${money(px)}`)}${term('Notional', money(px * q, 0))}${term('Deposit now', `${spec.deposit}% · ${money(px * q * spec.deposit / 100, 0)}`)}${term('Balance at settlement', money(px * q * (1 - spec.deposit / 100), 0))}${term('If transfer blocked', { refund: 'Refund, void', retry: 'Retry next window', cash: 'Cash-settle at RX' }[spec.rofr])}`;
      extra = `<div class="label dim" style="margin:12px 0 6px">Value at settlement by RX price</div><table class="table compact"><thead><tr><th>RX then</th><th class="num">vs forward</th><th class="num">Your P&amp;L</th></tr></thead><tbody>${[0.7, 0.85, 1, 1.15, 1.3, 1.5].map(m => { const S = rx * m; const pl = (spec.side === 'buy' ? S - px : px - S) * q; return `<tr><td>${money(S)} <span class="tiny muted">(${pct(m - 1)})</span></td><td class="num">${pct((S - px) / px)}</td><td class="num ${cls(pl)}">${money(pl, 0)}</td></tr>`; }).join('')}</tbody></table>`; }
    if (type === 'spv') { const f = D.fund(spec.fundId); if (spec.mode === 'join' && f) { const u = D.company(f.underlying); const units = +spec.amount / f.nav; rows = `${term('Vehicle', esc(f.name))}${term('Underlying', `${esc(u.name)} · entry ${money(f.entryPrice)}`)}${term('Your amount', money(+spec.amount, 0))}${term('Units (at NAV ' + money(f.nav) + ')', num(Math.round(units)))}${term('Look-through shares', `≈ ${num(Math.round(+spec.amount / D.price(u.id)))}`)}${term('Fees', `${(f.fee * 100).toFixed(1)}% + ${(f.carry * 100).toFixed(0)}% carry`)}${term('Closes', fmtDate(f.closeDate))}${term('Capacity left', money(Math.max(0, f.capacity - f.aum), 0))}`; }
      else rows = `${term('Vehicle', `New SPV · ${c ? esc(c.name) : '—'}`)}${term('Target size', money(+spec.target * 1e6, 0))}${term('Your commitment', money(+spec.commit, 0))}${term('Share of vehicle', pct(+spec.commit / (+spec.target * 1e6 || 1)))}${term('Min ticket', money(+spec.ticket, 0))}${term('Economics', `${spec.mgmt}% mgmt · ${spec.carry}% carry`)}${term('Look-through shares', c ? `≈ ${num(Math.round(+spec.target * 1e6 / rx))} at RX` : '—')}${term('Distribution', spec.open ? 'Open to Rainmaker clients' : 'Private')}`; }
    if (type === 'structured') { const basisPx = spec.basis === 'fixed' ? +spec.price : spec.basis === 'collar' ? rx : spec.basis === 'ref' && spec.ref === 'rx' ? rx * (1 + +spec.discount / 100) : null;
      rows = `${term('Position', `${spec.side === 'buy' ? 'Bid' : 'Ask'} · ${num(q)} shares`)}${term('Pricing', spec.basis === 'fixed' ? money(+spec.price) : spec.basis === 'round' ? `${spec.discount}% off next round` : spec.basis === 'ref' ? `${spec.discount}% vs ${spec.ref === '409a' ? '409A' : 'RX at close'}` : `${money(+spec.collarMin || rx * 0.9)}–${money(+spec.collarMax || rx * 1.1)} collar`)}${term('Indicative notional', basisPx ? money(basisPx * q, 0) : 'Set at close')}${term('Contingencies', spec.conts.length ? spec.conts.map(k => ({ rofr: 'ROFR waived', ipo: 'IPO ≤ ' + spec.ipoMonths + 'm', round: 'Round ≥ ' + (spec.roundVal || '?'), approval: 'Buyer approved', board: 'Board consent' })[k]).join(', ') : 'None')}${term('Closing', +spec.tranches > 1 ? `${spec.tranches} tranches / ${spec.trancheMonths}m` : 'Single close')}${term('Payment', spec.payment === 'cash' ? 'Cash' : spec.payment === 'finance' ? `${spec.down}% down, ${spec.finMonths}m` : 'Share exchange')}${term('True-up', +spec.trueUp ? `±${spec.trueUp}%` : 'None')}${term('Valid', `${spec.expiry} days · ${spec.excl}d exclusivity`)}`;
      if (spec.basis === 'round' && c) extra = `<div class="label dim" style="margin:12px 0 6px">Price by next-round outcome</div><table class="table compact"><thead><tr><th>Round prices at</th><th class="num">Your price</th><th class="num">Notional</th></tr></thead><tbody>${[0.8, 1, 1.25, 1.5, 2].map(m => { const rp = rx * m; const p = rp * (1 - +spec.discount / 100); return `<tr><td>${money(rp)} <span class="tiny muted">(${pct(m - 1)} vs RX)</span></td><td class="num">${money(p)}</td><td class="num">${money(p * q, 0)}</td></tr>`; }).join('')}</tbody></table>`; }
    box.innerHTML = `<div class="term-list">${rows}</div>${extra}<div class="callout" style="margin-top:12px"><b>Route:</b> ${esc(rep_.name)} reviews, the desk prices or sources the other side, compliance clears the structure, and you get a term sheet under My Orders → Arrangements.</div>`;
  };
  const wire = () => {
    const form = main.querySelector('#arr-form');
    form.querySelectorAll('[data-side]').forEach(b => b.onclick = () => { spec.side = b.dataset.side; render(); });
    wireCompanyPicker(form, 'cpick', id => { spec.companyId = id; const c = company(); if (c) { const rx = D.price(c.id); spec.strike = +(rx * 1.15).toFixed(2); spec.fwdPrice = +rx.toFixed(2); spec.price = +rx.toFixed(2); } render(); });
    const handle = e => { const el = e.target; const k = el.dataset.k; if (el.dataset.cont) { spec.conts = [...form.querySelectorAll('[data-cont]:checked')].map(x => x.dataset.cont); drawSummary(); return; } if (!k) return; spec[k] = el.type === 'checkbox' ? el.checked : el.value; if (el.dataset.rerender) { if (k === 'companyId') { const c = company(); if (c) { const rx = D.price(c.id); spec.strike = +(rx * 1.15).toFixed(2); spec.fwdPrice = +rx.toFixed(2); spec.price = +rx.toFixed(2); } } render(); return; } drawSummary(); };
    form.addEventListener('input', e => { if (['checkbox', 'radio', 'select-one'].includes(e.target.type)) return; handle(e); });
    form.addEventListener('change', e => { if (!['checkbox', 'radio', 'select-one'].includes(e.target.type)) return; handle(e); });
    form.addEventListener('submit', e => { e.preventDefault(); const c = company(); if (type !== 'spv' && !c) { toast('Pick a company', false); return; } if (type === 'spv' && spec.mode === 'form' && !c) { toast('Pick the company for the block', false); return; }
      const a = D.submitArrangement(Object.assign({}, spec, { what: what(), companyId: type === 'spv' && spec.mode === 'join' ? (D.fund(spec.fundId) || {}).underlying || null : spec.companyId })); toast(`${a.id} sent to ${rep_.name} and the desk`); go('#/orders/arrangements'); });
  };
  render();
}
// Table of arrangements with stage badges.
function arrangementsTable(list, staff) {
  const badge = s => `<span class="badge ${s === 'executed' ? 'verified' : s === 'declined' || s === 'withdrawn' ? 'status' : 'pending'}">${esc(s)}</span>`;
  return list.length ? `<table class="table compact"><thead><tr><th>Ref</th><th>Type</th><th>Terms</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>${list.map(a => `<tr><td><span class="oid">${esc(a.id)}</span></td><td><span class="badge custom">${esc(D.ARRANGEMENT_TYPES[a.type])}</span></td><td class="small">${esc(a.what)}${a.note ? `<div class="tiny muted">Client: ${esc(a.note)}</div>` : ''}${a.staffNote ? `<div class="tiny muted">Desk: ${esc(a.staffNote)}</div>` : ''}<div class="tiny muted">${a.history.map(h => `${esc(h.status)} ${fmtDateShort(h.ts)}`).join(' → ')}</div></td><td class="small">${fmtPlaced(a.created)}</td><td>${badge(a.status)}</td><td class="num" style="white-space:nowrap">${staff ? (['submitted', 'structuring', 'term sheet'].includes(a.status) ? `<span class="row" style="justify-content:flex-end;gap:6px">${a.status === 'submitted' ? `<button class="btn outline sm" data-arr="structuring" data-aid="${a.id}">Start structuring</button>` : ''}${a.status !== 'term sheet' ? `<button class="btn bid sm" data-arr="term sheet" data-aid="${a.id}">Issue term sheet</button>` : `<button class="btn bid sm" data-arr="executed" data-aid="${a.id}">Mark executed</button>`}<button class="btn danger sm" data-arr="declined" data-aid="${a.id}">Decline</button></span>` : '') : (a.status === 'term sheet' ? `<a class="btn bid sm" href="#/messages">Review term sheet</a> ` : '') + (['submitted', 'structuring', 'term sheet'].includes(a.status) ? `<button class="btn ghost sm" data-arr-withdraw="${a.id}">Withdraw</button>` : '')}</td></tr>`).join('')}</tbody></table>` : `<div class="empty"><b>No structured arrangements yet.</b><div class="small" style="margin-top:4px">Options, forwards, SPV units and bids or asks with special terms are requested from <a class="link" href="#/new/arrange">Structured deal</a> and come back as term sheets here.</div></div>`;
}

// ---------------- router ----------------
